#!/usr/bin/env python3
"""tests/base/gen_clspack_atoms.py -- writes tests/base/clspack_atoms.rxt,
[OPT-CLSPACK]'s answer corpus (docs/spec/tuning.md §2.35; D131 item 6).

The shipped corpus has NO artifact whose VM program reads 11 or more class
tables (measured: the most is 6 -- docs/dev/lanes/clspack_report.md §2), so
the atom row's population there is EMPTY, and every block here is a
constructed witness. Every expectation is python3 `re` (re.search on bytes,
group 1's span), computed here and written unmodified.

The blocks:
  atom-11        eleven scattered classes, one captured (a capture routes the
                 default compile to the VM): exactly the row's threshold.
  site-10        the first ten of them: one class short, per-class bitmaps.
  atom-reads     twelve table-read classes read from several byte
                 expressions: a span-loop cursor, a lazy loop, a counted
                 repeat and `\\b` (the word set is a pool class too).
  atom-64        (both crafted blocks `engine vm`: their default route is
                 the DFA) eleven classes built from distinct 11-bit membership codes
                 over 63 bytes: 63 non-empty atoms plus the empty one = 64,
                 the mask's width -- the row fires.
  atom-65        the same over 64 bytes: 65 atoms -- the row declines and the
                 classes keep their bitmaps.
tests/codegen/run_clspack.sh asserts which of these took the atom table
(the artifact's `RX_VM_CLS_ATOMS`); this file asserts the ANSWERS.

Usage: python3 tests/base/gen_clspack_atoms.py > tests/base/clspack_atoms.rxt
"""
import re
import sys

VOWELS = ["[aeiou]", "[bcdfg]", "[hjklm]", "[npqrs]", "[tvwxz]",
          "[AEIOU]", "[BCDFG]", "[HJKLM]", "[NPQRS]", "[TVWXZ]", "[02468]"]

# printable bytes a subject can carry unescaped: no `"`, no `\`
SAFE = [b for b in range(0x21, 0x7F) if b not in (0x22, 0x5C)]


def crafted(nbytes, nclass=11):
    """nclass classes over the first `nbytes` SAFE bytes, byte i carrying a
    distinct non-zero nclass-bit membership code: nbytes + 1 atoms."""
    codes, top = [], (1 << nclass) - 1
    for i in range(top):          # stride 29 walks every code once (gcd 1)
        c = (i * 29) % top + 1
        if bin(c).count("1") >= 2 and len(codes) < nbytes:
            codes.append(c)
    classes = [[SAFE[i] for i in range(nbytes) if (codes[i] >> k) & 1]
               for k in range(nclass)]
    for m in classes:     # a table-read class: not a byte, a range or a pair
        assert len(m) >= 3 and m[-1] - m[0] + 1 != len(m), m
    assert len({tuple(m) for m in classes}) == nclass
    atoms = {tuple((codes[i] >> k) & 1 for k in range(nclass)) if i < nbytes
             else (0,) * nclass for i in range(256)}
    assert len(atoms) == nbytes + 1
    return ["[" + "".join("\\x%02x" % b for b in m) + "]" for m in classes], classes


def members(cls):
    """A bracketed class spelled with literal members and a-z ranges."""
    body = cls[1:-1]
    out = []
    for m in re.finditer(r"\\x([0-9a-f]{2})|(.)", body):
        out.append(int(m.group(1), 16) if m.group(1) else ord(m.group(2)))
    return out


def outside(ms):
    return next(b for b in SAFE if b not in ms)


def cases(pattern, subjects):
    rx = re.compile(pattern.encode("latin-1"))
    out = []
    for s in subjects:
        m = rx.search(s)
        q = s.decode("latin-1")
        assert '"' not in q and "\\" not in q
        if m:
            out.append('m "%s" %d %d' % (q, m.start(), m.end()))
            if m.re.groups:
                g = m.span(1)
                out.append("g 1 %d %d" % g if g[0] >= 0 else "g 1 -1 -1")
        else:
            out.append('n "%s"' % q)
    return out


def chain_subjects(sets):
    """A matching subject, one off-by-one failure per position, and the
    match found mid-subject."""
    good = bytes(ms[i % len(ms)] for i, ms in enumerate(sets))
    subs = [good, b"~~" + good + b"~", bytes(ms[-1] for ms in sets)]
    for j, ms in enumerate(sets):
        subs.append(good[:j] + bytes([outside(ms)]) + good[j + 1:])
    return subs


def block(name, pattern, comment, subjects, out, features=None, engine=None):
    out.append("# case: %s" % name)
    out.append("pattern %s" % pattern)
    if features:
        out.append("features %s" % features)
    if engine:
        out.append("engine %s" % engine)
    for line in comment:
        out.append("# " + line)
    out.extend(cases(pattern, subjects))
    out.append("")


def main():
    out = [l for l in """# tests/base/clspack_atoms.rxt — [OPT-CLSPACK]: VM byte classes that
# share ONE atom table, as ANSWERS (docs/spec/tuning.md §2.35).
#
# GENERATED by tests/base/gen_clspack_atoms.py (its header says why every
# block is a constructed witness); edit the generator, not this file.
# tests/codegen/run_clspack.sh asserts which blocks take the atom table.
#
# All expectations python3-re verified (re.search spans and group-1 spans,
# computed by the generator, transcribed unmodified).
""".splitlines()]
    out.append("")
    v11 = "(" + VOWELS[0] + ")" + "".join(VOWELS[1:])
    sets11 = [members(c) for c in VOWELS]
    block("atom-11", v11, ["eleven table-read classes: the atom row's threshold"],
          chain_subjects(sets11), out)
    v10 = "(" + VOWELS[0] + ")" + "".join(VOWELS[1:10])
    block("site-10", v10, ["ten: one short of the threshold, a bitmap per class"],
          chain_subjects(sets11[:10]), out)
    reads = (r"(\b[aeiou][bcdfg]+)[hjklm]*?[npqrs]{2,3}[tvwxz][AEIOU][BCDFG]"
             r"[HJKLM][NPQRS][TVWXZ][02468]\b")
    block("atom-reads", reads,
          ["twelve table-read classes (the word set of \\b among them), read",
           "by a span-loop cursor, a lazy loop, a counted repeat and \\b"],
          [b"abbhnptEBHNT0", b"aebcdfghhhnnptEBHNT2", b"ab hnptEBHNT0",
           b"xabhnptEBHNT0", b"abhnptEBHNT0x", b"abhnnnptEBHNT0", b"ab",
           b"abhhnptEBHNT01", b" ebcnqtOGMST8 ", b"abhnpEBHNT0"], out,
          features="assertions")
    for n, name, what in ((63, "atom-64", "64 atoms, the mask's width: fires"),
                          (64, "atom-65", "65 atoms: declines, bitmaps")):
        spelled, sets = crafted(n)
        pat = "(" + spelled[0] + ")" + "".join(spelled[1:])
        block(name, pat, ["eleven classes over %d bytes with distinct membership" % n,
                          "codes: " + what,
                          "(forced onto the VM: the default route takes the DFA here)"],
              chain_subjects(sets), out, engine="vm")
    sys.stdout.write("\n".join(out).rstrip("\n") + "\n")


if __name__ == "__main__":
    main()
