#!/usr/bin/env python3
"""tests/findings/gen_adversarial.py — THE ADVERSARIAL ANALYSES and their
reach ([FINDINGS] B2; docs/design/findings/design.md §11.1, [r2 S-F3]).

A rate may change SPEED and never an ANSWER or a GIVE-UP (§6.2a). The check
of that promise runs the corpus under bundles built to be as wrong as a
bundle can be, and it proves nothing about a reader whose choice the bundle
never moved. So there are two kinds of bundle here:

  SHAPES   uniform, inverted (the default's ranks reversed), onehot-e,
           onehot-80, floor-but-one (all mass on '/'), random-<seed>:
           fixed, derived from nothing but their own definition.
  FIRE     fire-c1, fire-c2a, fire-c2b, fire-c3, fire-c4: ONE PER READER,
           each the candidate table that moves THAT reader's choice on the
           most corpus artifacts — derived from that reader's census alone,
           because one `fire-all` table cannot maximise five readers at once
           and a reader it happens not to move would be untested with
           nobody told.

Every bundle declares `serves byte-rate when byte,utf8`, so the readers are
exercised under both encodings, including the `utf8` arms the default
leaves at NONE.

A reader's CHOICE is read from its own stamp in the artifact, never from
anything the generator computes:
  c1   RX_REQ_BYTE                        the necessary set's scanned member
  c2a  RX_REQ_RUN after '@'               the run's scanned member index
  c2b  RX_REQ_RUN before '@'              the emitted 8-byte window
  c3   RX_REQ_WHY                         G1's emitted/dominated decision
  c4   RX_DFA_PREFILTER_OFFSETS           the offset-k selection

Subcommands:
  gen    [slow; run by hand, output COMMITTED] the census over every distinct
         corpus pattern x {byte, utf8}: writes adversarial/*.rxt,
         adversarial/census.tsv (every candidate's move count per reader)
         and adversarial/reach.tsv (for each fire bundle, the artifacts its
         reader moved on — the population `reach` re-measures).
  reach  [fast; make test] re-compiles reach.tsv's population under the
         default and under each fire bundle, and prints one line per bundle
         with its live REACH count. A zero is red: a fire bundle that moves
         nothing proves nothing (design §11.1).
  witness [fast; make test] the §11.9 witnesses (witness/witness.tsv): one
         constructed pattern + bundle per reader, each stamp pinned both
         under the default and under its bundle.
"""
import glob
import hashlib
import os
import random
import re
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
ADV = os.path.join(HERE, "adversarial")
PCREC = os.environ.get("PCREC", os.path.join(ROOT, "build", "pcrec"))
DEFAULT_RXT = os.path.join(ROOT, "src", "findings", "default.rxt")
READERS = ["c1", "c2a", "c2b", "c3", "c4"]
ENCS = ["byte", "utf8"]
SEED = 20260927
SAMPLE = 1200


def default_counts():
    """The shipped default's counts, read from its committed text."""
    c = [0] * 256
    for ln in open(DEFAULT_RXT, encoding="utf-8"):
        m = re.match(r"\s+row ([0-9a-f]{2}) (\d+)$", ln)
        if m:
            c[int(m.group(1), 16)] = int(m.group(2))
    return c


def bundle_text(name, counts, why):
    """One adversarial bundle as `.rxt` text."""
    out = [f"# tests/findings/adversarial/{name}.rxt — GENERATED by",
           "# tests/findings/gen_adversarial.py gen; never edit by hand.",
           f"# {why}",
           f"analysis {name}",
           f"    description adversarial analysis '{name}' (design §11.1)",
           "    freq",
           "        question None: a table built to be wrong, for the answer-identity check",
           "        reader byte-rate",
           "        analyzer tests/findings/gen_adversarial.py",
           "        encoding bytes",
           "        serves byte-rate when byte,utf8 via unigram"]
    for b in range(256):
        if counts[b]:
            out.append(f"        row {b:02x} {counts[b]}")
    out += ["        provenance",
            "            source authored",
            "            retrieved 2026-09-27",
            "            attribution tests/findings/gen_adversarial.py (constructed, no exemplar)"]
    return "\n".join(out) + "\n"


def shapes():
    """The fixed-shape bundles: name -> (counts, why)."""
    d = default_counts()
    order = sorted(range(256), key=lambda b: (d[b], b))
    vals = sorted(d)
    inv = [0] * 256
    for i, b in enumerate(order):
        inv[b] = vals[255 - i]
    rnd = random.Random(SEED)
    r = [rnd.randrange(0, 1000000) for _ in range(256)]
    oh = lambda byte: [1000000 if b == byte else 0 for b in range(256)]
    return {
        "uniform": ([1] * 256, "every byte equal"),
        "inverted": (inv, "the default's ranks reversed: its commonest byte is rarest"),
        "onehot-e": (oh(0x65), "all mass on 'e', every other byte at the floor"),
        "onehot-80": (oh(0x80), "all mass on 0x80, every other byte at the floor"),
        "floor-but-one": (oh(0x2f), "255 bytes at the floor, the remainder on '/'"),
        f"random-{SEED}": (r, f"seeded (random.Random({SEED}).randrange(0, 10**6) per byte)"),
    }


def stamp(text, name):
    m = re.search(r'^#define RX_' + name + r' "([^"]*)"', text, re.M)
    return m.group(1) if m else ""


def choices(text):
    """Each reader's choice, read from its stamp."""
    run = stamp(text, "REQ_RUN")
    win, _, idx = run.partition("@")
    return {"c1": stamp(text, "REQ_BYTE"), "c2a": idx, "c2b": win,
            "c3": stamp(text, "REQ_WHY"),
            "c4": stamp(text, "DFA_PREFILTER_OFFSETS")}


def compile_one(pat, enc, extra, d):
    out = os.path.join(d, "x.c")
    try:
        r = subprocess.run([PCREC, "-p", "rx", "--features", "all", "-e", enc,
                            "-o", out] + extra + ["--pattern", pat],
                           capture_output=True, timeout=120)
    except subprocess.TimeoutExpired:
        return None
    if r.returncode != 0:
        return None
    return choices(open(out, "rb").read().decode("latin-1"))


def corpus_patterns():
    seen, pats = set(), []
    for path in sorted(glob.glob(f"{ROOT}/tests/**/*.rxt", recursive=True)):
        if "/findings/" in path:
            continue
        for ln in open(path, "rb").read().decode("utf-8", "surrogateescape").splitlines():
            if ln.startswith("pattern ") and ln[8:] not in seen:
                seen.add(ln[8:])
                pats.append(ln[8:])
    return pats


def run_pool(jobs, extra, tmp):
    """{(pat, enc): choices or None} for every job under `extra` flags."""
    def one(j):
        i, (pat, enc) = j
        d = os.path.join(tmp, str(i))
        os.makedirs(d, exist_ok=True)
        return (pat, enc), compile_one(pat, enc, extra, d)
    with ThreadPoolExecutor(max_workers=int(os.environ.get("PROCS", "6"))) as ex:
        return dict(ex.map(one, enumerate(jobs)))


def anti_tables(base):
    """Candidates built from the DEFAULT's own choices: the bytes a reader
    picks under the default become the commonest, so its choice must move
    wherever it has an alternative. One per reader that picks a byte."""
    tabs = {}
    for rd in ("c1", "c2a"):
        hits = [1] * 256
        for (pat, enc), ch in base.items():
            if not ch:
                continue
            if rd == "c1" and ch["c1"].lstrip("-").isdigit() and int(ch["c1"]) >= 0:
                hits[int(ch["c1"])] += 1000
            if rd == "c2a" and ch["c2a"].isdigit() and ch["c2b"]:
                w = bytes.fromhex(ch["c2b"])
                i = int(ch["c2a"])
                if i < len(w):
                    hits[w[i]] += 1000
        tabs[f"anti-{rd}"] = (hits, f"the bytes reader {rd} scans under the default made the commonest")
    return tabs


def write(name, counts, why):
    open(os.path.join(ADV, f"{name}.rxt"), "w").write(bundle_text(name, counts, why))


def gen():
    os.makedirs(ADV, exist_ok=True)
    pats = corpus_patterns()
    jobs = [(p, e) for p in pats for e in ENCS]
    tmp = tempfile.mkdtemp(prefix="findadv.")
    base = run_pool(jobs, [], os.path.join(tmp, "base"))
    live = [j for j in jobs if base.get(j) and any(base[j][r] not in ("", "none", "-1") for r in READERS)]
    # A FIXED SAMPLE of the reader-bearing population, by hash order, so the
    # census is repeatable and costs minutes rather than an hour.
    live.sort(key=lambda j: hashlib.sha1((j[0] + "\0" + j[1]).encode("utf-8", "surrogateescape")).hexdigest())
    nlive = len(live)
    live = live[:SAMPLE]
    sys.stderr.write(f"gen: {len(jobs)} artifact-configs, {nlive} with a reader stamp, census over {len(live)}\n")
    cands = dict(shapes())
    cands.update(anti_tables(base))
    for b in b" etaoinsrlcd/._-:0=,":
        cands[f"onehot-{b:02x}"] = ([1000000 if x == b else 0 for x in range(256)],
                                   f"all mass on 0x{b:02x}")
    cdir = os.path.join(tmp, "cand")
    os.makedirs(cdir, exist_ok=True)
    census, moved = {}, {}
    for name, (counts, why) in cands.items():
        open(os.path.join(cdir, f"{name}.rxt"), "w").write(bundle_text(name, counts, why))
        res = run_pool(live, ["-I", cdir, "--analysis", name], os.path.join(tmp, "r_" + name))
        census[name] = {r: 0 for r in READERS}
        moved[name] = {r: [] for r in READERS}
        for j in live:
            a, b = res.get(j), base[j]
            if not a:
                continue
            for r in READERS:
                if a[r] != b[r]:
                    census[name][r] += 1
                    moved[name][r].append(j)
        sys.stderr.write(f"gen: {name}: " + " ".join(f"{r}={census[name][r]}" for r in READERS) + "\n")
    for name, (counts, why) in shapes().items():
        write(name, counts, why)
    with open(os.path.join(ADV, "census.tsv"), "w") as f:
        f.write("# GENERATED by gen_adversarial.py gen: per candidate table, how many\n"
                f"# of a fixed {len(live)}-config sample (hash order) of the {nlive}\n"
                f"# reader-bearing corpus artifact-configs (of {len(jobs)})\n"
                "# each reader's stamp moved on against the default.\n")
        f.write("#candidate\t" + "\t".join(READERS) + "\n")
        for name in cands:
            f.write(name + "\t" + "\t".join(str(census[name][r]) for r in READERS) + "\n")
    with open(os.path.join(ADV, "reach.tsv"), "w") as f:
        f.write("# GENERATED by gen_adversarial.py gen: for each fire-<reader> bundle, the\n"
                "# artifacts (pattern, encoding) that reader moved on in the census, at\n"
                "# most 25, the population `reach` re-measures under make test.\n")
        f.write("#bundle\treader\tencoding\tpattern_hex\n")
        for r in READERS:
            best = max(cands, key=lambda n: (census[n][r], -list(cands).index(n)))
            counts, why = cands[best]
            write(f"fire-{r}", counts,
                  f"reader {r}'s argmax over {len(cands)} candidates: '{best}' ({why}); "
                  f"moved {census[best][r]} of {len(live)} artifact-configs")
            for pat, enc in moved[best][r][:25]:
                f.write(f"fire-{r}\t{r}\t{enc}\t{pat.encode('utf-8', 'surrogateescape').hex()}\n")


def reach():
    rows = []
    for ln in open(os.path.join(ADV, "reach.tsv")):
        if ln.startswith("#") or not ln.strip():
            continue
        b, r, enc, hx = ln.rstrip("\n").split("\t")
        rows.append((b, r, enc, bytes.fromhex(hx).decode("utf-8", "surrogateescape")))
    tmp = tempfile.mkdtemp(prefix="findreach.")
    jobs = sorted({(p, e) for _, _, e, p in rows})
    base = run_pool(jobs, [], os.path.join(tmp, "base"))
    bad = 0
    for bundle in [f"fire-{r}" for r in READERS]:
        mine = [(r, e, p) for b, r, e, p in rows if b == bundle]
        res = run_pool([(p, e) for _, e, p in mine], ["-I", ADV, "--analysis", bundle],
                       os.path.join(tmp, bundle))
        n = sum(1 for r, e, p in mine
                if res.get((p, e)) and base.get((p, e)) and res[(p, e)][r] != base[(p, e)][r])
        print(f"REACH\t{bundle}\t{n}\tof {len(mine)}")
        if n == 0:
            bad += 1
    return 1 if bad else 0


def witness():
    """Design §11.9: each witness's reader stamp is its pinned default value
    with no analysis, and its pinned MOVED value under its own bundle."""
    wdir = os.path.join(HERE, "witness")
    tmp = tempfile.mkdtemp(prefix="findwit.")
    bad = 0
    for ln in open(os.path.join(wdir, "witness.tsv"), encoding="utf-8"):
        if ln.startswith("#") or not ln.strip():
            continue
        b, r, st, pat, want_d, want_m = ln.rstrip("\n").split("\t")
        got = []
        for extra in ([], ["-I", wdir, "--analysis", b]):
            out = os.path.join(tmp, "x.c")
            rc = subprocess.run([PCREC, "-p", "rx", "--features", "all", "-e", "byte",
                                 "-o", out] + extra + ["--pattern", pat],
                                capture_output=True).returncode
            got.append(stamp(open(out, "rb").read().decode("latin-1"), st) if rc == 0 else "REFUSED")
        ok = got == [want_d, want_m]
        print(f"{'PASS' if ok else 'FAIL'}\t{b}\t{r}\tRX_{st} default={got[0]!r} "
              f"(pinned {want_d!r}) under {b}={got[1]!r} (pinned {want_m!r})")
        bad += not ok
    return 1 if bad else 0


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "gen":
        gen()
    elif cmd == "reach":
        sys.exit(reach())
    elif cmd == "witness":
        sys.exit(witness())
    else:
        sys.stderr.write(__doc__)
        sys.exit(2)
