"""[DD-14] PROBE 1 -- what a DFA prefilter is worth on call-SHAPED patterns.

pcrec cannot compile a subroutine call today (module `recursion` has no
producer -- every call spelling REFUSES, see probe_spellings.py's A6/backrefs
spellings.rxt). So this probe cannot time a call directly. What it CAN do is
time the call's INLINED EQUIVALENT: textually substitute the callee's body
for each call site, drop the `(?(DEFINE)...)` wrapper where present, and
compile THAT with pcrec -- a pattern pcrec accepts today, with the same
literal/class/alternation shape a called body would have.

The INLINING TABLE is hand-written (§ ROWS below), not generated by a general
inliner: a reader needs to be able to see, in one glance, that the two sides
of a row say the same thing. A general inliner is exactly the mechanism
DD-14 is trying to decide whether pcrec should HAVE -- building one here to
answer the question would be circular.

METHOD, four stages:

  1. EQUIVALENCE. For every row, compare `sr.search(call_pat, subj)` against
     `sr.search(inl_pat, subj)` on >=25 subjects (matching / non-matching /
     near-miss / empty / long), BOTH answered by libpcre2 -- the call side
     because PCRE2 accepts calls and pcrec does not, the inlined side as the
     control. This is an apples-to-apples check of the hand-substitution
     against ONE oracle, not a cross-engine diff. A row where any subject
     disagrees is DISQUALIFIED from the timing table (reported, not fixed).

  2. THE GROUPLESS DISCOVERY (read before trusting a ratio near 1.00).
     Measured here, not assumed: an INLINED pattern that drops the DEFINE
     wrapper AND has no capturing group left over compiles to pcrec's PURE
     DFA ARTIFACT -- no `RX_ENGINE`/`RX_VM_PREFILTER` macros at all, and
     `-fno-prefilter` on such a pattern is a byte-identical no-op (verified
     below by diffing the two arms' emitted .c, not assumed from the flag's
     name). The DFA-idiom rows below (define bodies with no other group)
     fall in this bucket and are reported SEPARATELY, as a reference
     baseline, not in the ratio table -- their ratio would read close to
     1.00 for a reason that has nothing to do with whether a prefilter
     helps: there IS no prefilter/VM distinction to measure on them. Only a
     row whose inlined pattern keeps a capturing group (the numeric-reuse
     and \\g<name>-reuse idioms always do, because the call site sits next
     to the group that defines it) reaches `RX_ENGINE "vm"` /
     `RX_VM_PREFILTER "hybrid"` and is a live measurement of the question
     DD-14 is asking.

  3. TIMING. For each VERIFIED, VM-reaching row: compile the inlined pattern
     twice (default vs `-fno-prefilter`), build each against a small custom
     driver (bigdriver.c, written to $SR_PF_TMP at runtime -- NOT the
     `--emit-main` artifact; see the ARGV FINDING below), and run best-of-3
     over a >=1MB subject built so the pattern's candidate starts are sparse
     (a 'Z'-filled run: none of these patterns' leading literal/class/
     alternation alphabets contain 'Z', so the filler contributes zero
     candidate starts and the only real work is at the tail). Two subject
     variants per row: one with a genuine match near the end, one with no
     match anywhere -- the prefilter's "rule this whole region out fast"
     case.

  4. REACHABILITY GUARDS -- printed, and the run is marked VACUOUS if any
     fails: (a) at least one default-arm artifact must stamp
     `RX_VM_PREFILTER "hybrid"` (or the whole table measured no prefilter at
     all); (b) the default and `-fno-prefilter` arms must agree on the match
     answer for every timed subject; (c) the same binary's own three-run
     spread is reported alongside every ratio, so a small ratio can be seen
     against the noise floor that produced it.

THE ARGV FINDING (an instrument defect caught before it produced a wrong
number). The brief's literal invocation is `--emit-main ... ; run the
binary over a >=1MB subject`. `--emit-main`'s generated `main()` takes the
subject from `argv[1]` -- and Linux caps a SINGLE argv element at
`MAX_ARG_STRLEN`, 128KiB, regardless of the total argv/environment budget.
A >=1MB subject therefore cannot be passed to a `--emit-main` binary at
all; the shell fails it with "Argument list too long" before pcrec's own
code ever runs. Had this gone unnoticed, the probe would have silently
fallen back to some smaller subject (or errored out and reported nothing),
either of which would have hidden the story WITHOUT saying so. The fix:
this probe generates the SAME artifact `--emit-main` would generate, minus
`--emit-main` itself (the two are otherwise the same `-o OUT.c` compile,
same flags), and links it against a driver adapted from
`eng_brep_measurements/probes/tdriver.c`'s technique -- except reading the
subject from a FILE (no argv limit) rather than argv, since tdriver.c's own
subjects are always small (an awk-generated `((a)|b){0,N}c` driver string,
never megabyte-scale).
"""
import importlib.util
import os
import re
import statistics
import subprocess
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.normpath(os.path.join(_HERE, "..", "..", "..", ".."))
_spec = importlib.util.spec_from_file_location(
    "sr_oracle", os.path.join(_HERE, "sr_oracle.py"))
sr = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(sr)

PCREC_BIN = os.environ.get("SR_PF_PCREC",
                            os.path.join(_ROOT, "build", "pcrec"))
# Convention borrowed from probe_throughput.sh's ${BREP_TMP:-/tmp}: scratch
# artifacts (compiled .c/.h/binaries, subject files) go under a TMP dir this
# probe never assumes is inside the repo, default /tmp/sr_pf.
TMP = os.environ.get("SR_PF_TMP", "/tmp/sr_pf")
os.makedirs(TMP, exist_ok=True)

GNUTIMEOUT = "gnutimeout"  # NOT bare `timeout` -- see the probe brief: bare
                           # `timeout` here is uutils and sleeps 108ms/call.

print("libpcre2:", sr.version())
print("python3 :", sys.version.split()[0])
print("sr_oracle.SELFCHECK:", sr.SELFCHECK or "none")
print("pcrec   :", PCREC_BIN)
print("tmp     :", TMP)
print()

# ---------------------------------------------------------------------------
# FLAG-SPELLING SELF-CHECK -- the brief requires checking before assuming.
# FIRST ATTEMPT (kept as a comment because the wrong result is itself worth
# recording): grepping `pcrec --help`'s TEXT for "-fno-prefilter". That
# failed -- `--help` documents the major flags only; every `-fno-*` tuning
# knob (`-fno-possessify`, `-fno-revdet`, `-fno-prefilter`, ...) is a real,
# accepted flag that simply is not IN the help text (confirmed separately by
# `grep -n '"-fno-prefilter"' cli/main.c`, which is the ground truth `--help`
# does not fully mirror). A --help substring check would have reported a
# false "problem" and, worse, would have looked authoritative. The corrected
# check instead ACTUALLY INVOKES the flag on a trivial pattern and confirms
# pcrec accepts it (exit 0, no "unrecognized"/"unknown option" text) --
# behaviour, not documentation, the same principle sr_oracle's own
# SELFCHECK uses throughout this lane.
# ---------------------------------------------------------------------------
_PROBLEMS = []
_fc = subprocess.run([PCREC_BIN, "-p", "rx", "-fno-prefilter",
                       "-o", os.path.join(TMP, "_flagcheck.c"), "--", "a"],
                      capture_output=True, text=True)
if _fc.returncode != 0 or "unrecognized" in _fc.stderr.lower() \
        or "unknown option" in _fc.stderr.lower():
    _PROBLEMS.append("'-fno-prefilter' was NOT accepted by pcrec (rc=%d, "
                      "stderr=%r) -- the flag spelling this probe assumes "
                      "may be wrong" % (_fc.returncode, _fc.stderr[:200]))
_hc = subprocess.run([PCREC_BIN, "--help"], capture_output=True, text=True)
if "--emit-main" not in _hc.stdout:
    _PROBLEMS.append("'--emit-main' not found in `pcrec --help` output")
if _PROBLEMS:
    print("FLAG-SPELLING SELF-CHECK: PROBLEMS:")
    for p in _PROBLEMS:
        print("  -", p)
else:
    print("flag-spelling self-check: -fno-prefilter ACCEPTED (behaviourally "
          "confirmed, not just grepped from --help text, which does not "
          "list per-optimization -fno-* flags at all) and --emit-main is "
          "documented in --help (--emit-main itself is NOT used for the "
          "timed artifacts -- see the ARGV FINDING in this file's "
          "docstring).")
print()


def run(cmd, timeout=60, **kw):
    return subprocess.run([GNUTIMEOUT, str(timeout)] + list(cmd),
                           capture_output=True, text=True, **kw)


# ---------------------------------------------------------------------------
# THE INLINING TABLE. One row per (call_pat, inl_pat) hand-written pair.
#   idiom   'define'  -- (?(DEFINE)(?<w>BODY))(?&w)...(?&w)  library idiom
#           'numeric' -- (GROUP)...(?1)                       numeric reuse
#           'gname'   -- (?<name>GROUP)...\g<name>            named \g reuse
#   sl      pattern's first REAL (non-DEFINE-header) matched content is a
#           fixed literal (True) or a class/alternation (False)
#   cl      the CALLEE's own first byte is a fixed literal
#   cs      callee shape: 'L' literal / 'C' class+ / 'A' alternation
#   sites   number of call sites
#   compare_groups
#           whether the call/inline pair have the SAME group count and a
#           full (span, groups) comparison is meaningful. False for the
#           `define` idiom: dropping the wrapper also drops the DEFINE-only
#           group, which never participates in a match either way (it is
#           inside a branch PCRE2 never takes) -- comparing SPAN ONLY is the
#           correct equivalence check there; comparing the padded groups
#           vector would flag a structural non-difference as a disagreement.
# ---------------------------------------------------------------------------
ROWS = [
    dict(id="R01", idiom="define", sl=True, cl=True, cs="L", sites=1,
         call=r"go(?(DEFINE)(?<w>cat))(?&w)", inl=r"gocat",
         compare_groups=False,
         matches=["gocat", "gocatgocat", "xgocatx"],
         nomatches=["godog", "goca", "xyz"]),
    dict(id="R02", idiom="define", sl=False, cl=True, cs="L", sites=1,
         call=r"(?(DEFINE)(?<w>cat))(?&w)end", inl=r"catend",
         compare_groups=False,
         matches=["catend", "xcatendx", "catendcatend"],
         nomatches=["catens", "caten", "dogend"]),
    dict(id="R03", idiom="define", sl=True, cl=False, cs="C", sites=1,
         call=r"go(?(DEFINE)(?<w>[a-z]+))(?&w)", inl=r"go[a-z]+",
         compare_groups=False,
         matches=["gocat", "goz", "gothisisalongword"],
         nomatches=["go", "goX", "xyz"]),
    dict(id="R04", idiom="define", sl=True, cl=True, cs="A", sites=1,
         call=r"go(?(DEFINE)(?<w>cat|dog))(?&w)", inl=r"go(?:cat|dog)",
         compare_groups=False,
         matches=["gocat", "godog", "xgocatx"],
         nomatches=["gofish", "go", "xyz"]),
    dict(id="R05", idiom="define", sl=True, cl=True, cs="L", sites=2,
         call=r"go(?(DEFINE)(?<w>cat))(?&w)-(?&w)", inl=r"gocat-cat",
         compare_groups=False,
         matches=["gocat-cat", "xgocat-catx", "gocat-catgocat-cat"],
         nomatches=["gocat-dog", "gocat-", "gocatcat"]),
    dict(id="R06", idiom="define", sl=True, cl=True, cs="L", sites=3,
         call=r"go(?(DEFINE)(?<w>cat))(?&w)-(?&w)-(?&w)",
         inl=r"gocat-cat-cat",
         compare_groups=False,
         matches=["gocat-cat-cat", "xgocat-cat-catx",
                  "gocat-cat-catgocat-cat-cat"],
         nomatches=["gocat-cat-dog", "gocat-cat-", "gocatcatcat"]),
    dict(id="R07", idiom="define", sl=False, cl=False, cs="C", sites=2,
         call=r"(?(DEFINE)(?<w>[0-9]+))(?&w)-(?&w)", inl=r"[0-9]+-[0-9]+",
         compare_groups=False,
         matches=["12-34", "0-0", "999-1"],
         nomatches=["12-", "-34", "abc"]),
    dict(id="R08", idiom="define", sl=True, cl=False, cs="C", sites=3,
         call=r"id(?(DEFINE)(?<w>[a-z0-9]+))(?&w)\.(?&w)\.(?&w)",
         inl=r"id[a-z0-9]+\.[a-z0-9]+\.[a-z0-9]+",
         compare_groups=False,
         matches=["idabc.def.ghi", "id1.2.3", "xidabc.def.ghix"],
         nomatches=["idabc.def", "id..", "xyz"]),
    dict(id="R09", idiom="numeric", sl=True, cl=True, cs="L", sites=1,
         call=r"(cat)x(?1)", inl=r"(cat)xcat",
         compare_groups=True,
         matches=["catxcat", "xcatxcatx", "catxcatcatxcat"],
         nomatches=["catxdog", "catx", "xcatx"]),
    dict(id="R10", idiom="numeric", sl=True, cl=True, cs="L", sites=2,
         call=r"(cat)x(?1)y(?1)", inl=r"(cat)xcatycat",
         compare_groups=True,
         matches=["catxcatycat", "xcatxcatycatx", "catxcatycatcatxcatycat"],
         nomatches=["catxcatydog", "catxdogycat", "catx"]),
    dict(id="R11", idiom="numeric", sl=True, cl=False, cs="C", sites=1,
         call=r"([a-z]+)#(?1)", inl=r"([a-z]+)#[a-z]+",
         compare_groups=True,
         matches=["ab#cd", "z#z", "hello#world"],
         nomatches=["ab#", "#cd", "123#456"]),
    dict(id="R12", idiom="numeric", sl=True, cl=False, cs="A", sites=1,
         call=r"(cat|dog)!(?1)", inl=r"(cat|dog)!(?:cat|dog)",
         compare_groups=True,
         matches=["cat!dog", "dog!cat", "cat!cat"],
         nomatches=["cat!fish", "cat!", "!dog"]),
    dict(id="R13", idiom="gname", sl=True, cl=True, cs="L", sites=1,
         call=r"(?<w>cat)mid\g<w>", inl=r"(?<w>cat)midcat",
         compare_groups=True,
         matches=["catmidcat", "xcatmidcatx", "catmidcatcatmidcat"],
         nomatches=["catmiddog", "catmid", "xmidcat"]),
    dict(id="R14", idiom="gname", sl=True, cl=True, cs="L", sites=2,
         call=r"(?<w>cat)mid\g<w>-\g<w>", inl=r"(?<w>cat)midcat-cat",
         compare_groups=True,
         matches=["catmidcat-cat", "xcatmidcat-catx",
                  "catmidcat-catcatmidcat-cat"],
         nomatches=["catmidcat-dog", "catmiddog-cat", "catmid"]),
    dict(id="R15", idiom="gname", sl=True, cl=False, cs="C", sites=1,
         call=r"(?<w>[a-z]+)#\g<w>", inl=r"(?<w>[a-z]+)#[a-z]+",
         compare_groups=True,
         matches=["ab#cd", "hello#world", "z#z"],
         nomatches=["ab#", "#cd", "123#456"]),
]


def battery(matches, nomatches):
    """>=25 subjects covering matching / non-matching / near-miss / empty /
    long, built generically from a row's canonical matches/nomatches so the
    table above stays a table, not 15 hand-typed 25-line subject lists."""
    subs = ["", "Z" * 5000, "Z" * 20000 + matches[0]]
    for m in matches:
        subs += [m, "Z" + m, m + "Z", "ZZ" + m + "ZZ", m + m]
    for nm in nomatches:
        subs += [nm, "Z" + nm + "Z", nm + nm]
    subs.append("ZZZ")
    return subs


def check_equivalence(row):
    """Compare libpcre2's answer for call_pat against libpcre2's answer for
    inl_pat over battery(). Returns (cells, disagreements)."""
    subs = battery(row["matches"], row["nomatches"])
    disagreements = []
    for subj in subs:
        rc = sr.search(row["call"], subj)
        ri = sr.search(row["inl"], subj)
        if rc == "ERR" or ri == "ERR":
            disagreements.append((subj, rc, ri, "compile-error"))
            continue
        if (rc is None) != (ri is None):
            disagreements.append((subj, rc, ri, "match/nomatch split"))
            continue
        if rc is None:
            continue
        span_c, groups_c = rc
        span_i, groups_i = ri
        if span_c != span_i:
            disagreements.append((subj, rc, ri, "span differs"))
            continue
        if row["compare_groups"] and groups_c != groups_i:
            disagreements.append((subj, rc, ri, "groups differ"))
            continue
    return len(subs), disagreements


# ---------------------------------------------------------------------------
# COMPILE / BUILD / TIME
# ---------------------------------------------------------------------------
_BIGDRIVER_C = r"""
/* bigdriver.c -- [DD-14] PROBE 1 timing driver, written at runtime by
 * probe_prefilter.py (not committed). See the ARGV FINDING in that file's
 * docstring: reads the subject from a FILE (argv[1] is a PATH) rather than
 * from argv itself, because a single argv element is capped by the kernel's
 * MAX_ARG_STRLEN (128KiB) and this probe's subjects are >=1MB. Prints
 *   <rc-word>\t<ns>\t<span0>\t<span1>
 * rc-word is match/nomatch/giveup; ns is CLOCK_MONOTONIC elapsed around the
 * ONE rx_search call (the file read is outside the timed region). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <stddef.h>

int rx_search(const unsigned char *s, size_t n, size_t startpos,
              ptrdiff_t (*caps)[2]);

int main(int argc, char **argv)
{
    if (argc < 2) { fprintf(stderr, "usage: bigdriver SUBJECT_FILE\n"); return 2; }
    FILE *f = fopen(argv[1], "rb");
    if (!f) { perror("fopen"); return 2; }
    if (fseek(f, 0, SEEK_END) != 0) { perror("fseek"); return 2; }
    long sz = ftell(f);
    if (sz < 0) { perror("ftell"); return 2; }
    rewind(f);
    unsigned char *buf = malloc((size_t)sz + 1);
    if (!buf) { fprintf(stderr, "malloc failed\n"); return 2; }
    size_t got = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    if (got != (size_t)sz) { fprintf(stderr, "short read\n"); return 2; }

    ptrdiff_t caps[64][2];
    memset(caps, 0, sizeof caps);

    struct timespec a, b;
    clock_gettime(CLOCK_MONOTONIC, &a);
    int rc = rx_search(buf, (size_t)sz, 0, caps);
    clock_gettime(CLOCK_MONOTONIC, &b);
    double ns = (double)(b.tv_sec - a.tv_sec) * 1e9
              + (double)(b.tv_nsec - a.tv_nsec);

    if (rc == 1)
        printf("match\t%.1f\t%lld\t%lld\n", ns,
               (long long)caps[0][0], (long long)caps[0][1]);
    else if (rc == 0)
        printf("nomatch\t%.1f\n", ns);
    else
        printf("giveup\t%.1f\t%d\n", ns, rc);
    free(buf);
    return 0;
}
"""

_BIGDRIVER_PATH = os.path.join(TMP, "bigdriver.c")
with open(_BIGDRIVER_PATH, "w") as _f:
    _f.write(_BIGDRIVER_C)


def pcrec_compile(pattern, out_c, extra_flags=()):
    cmd = [PCREC_BIN, "-p", "rx", "--features", "all", *extra_flags,
           "-o", out_c, "--", pattern]
    return run(cmd, timeout=60)


def gcc_build(c_file, out_bin):
    cmd = ["gcc", "-O2", "-w", "-std=gnu11", "-o", out_bin,
           _BIGDRIVER_PATH, c_file]
    return run(cmd, timeout=60)


def stamps(c_text):
    d = {}
    for key in ("RX_ENGINE", "RX_ENGINE_WHY", "RX_VM_PREFILTER",
                "RX_VM_PRUNE_CEILING"):
        m = re.search(r'#define %s "([^"]*)"' % re.escape(key), c_text)
        d[key] = m.group(1) if m else None
    return d


BIG_FILLER = 1_000_000  # 'Z' bytes -- outside every row's leading alphabet


def write_subject(path, with_match, tail):
    subj = ("Z" * BIG_FILLER) + (tail if with_match else "")
    with open(path, "wb") as f:
        f.write(subj.encode("latin-1"))
    return len(subj)


def time_binary(bin_path, subj_path, reps=3):
    """Returns (list of (word, ns) over `reps` runs) or None on any failure."""
    out = []
    for _ in range(reps):
        r = run([bin_path, subj_path], timeout=60)
        if r.returncode != 0:
            return None
        parts = r.stdout.strip().split("\t")
        if len(parts) < 2:
            return None
        out.append((parts[0], float(parts[1])))
    return out


# ---------------------------------------------------------------------------
# RUN
# ---------------------------------------------------------------------------
print("=== STAGE 1: EQUIVALENCE VERIFICATION (libpcre2 call vs libpcre2 "
      "inlined, per row) ==================================================")
qualified = []
for row in ROWS:
    cells, dis = check_equivalence(row)
    status = "DISQUALIFIED" if dis else "verified-equivalent"
    print("  %-4s cells=%-3d disagreements=%-3d  %s" %
          (row["id"], cells, len(dis), status))
    if dis:
        for subj, rc, ri, why in dis[:5]:
            print("        %-30r call=%-40r inl=%-40r  (%s)" %
                  (subj, rc, ri, why))
        if len(dis) > 5:
            print("        ... and %d more" % (len(dis) - 5))
    else:
        qualified.append(row)
print()
print("qualified rows: %d / %d" % (len(qualified), len(ROWS)))
print()

def _strip_header_include(text):
    """The two arms differ only in the #include "<id>_{def,np}.h" line
    (the header BASENAME, generated per -o); everything else in a
    byte-identical artifact matches. Normalise that one line away so the
    diff is honest about what actually differs."""
    return re.sub(r'#include "[^"]+\.h"', '#include "HDR"', text)


print("=== STAGE 2: COMPILE + STAMPS (default arm; -fno-prefilter arm only "
      "when the default arm reaches the VM) =================================")
has_vm_rows = []
dfa_only_rows = []
compile_problems = []
for row in qualified:
    rid = row["id"]
    def_c = os.path.join(TMP, "%s_def.c" % rid)
    r = pcrec_compile(row["inl"], def_c)
    if r.returncode != 0:
        compile_problems.append((rid, "default-arm compile failed", r.stderr))
        print("  %-4s DEFAULT COMPILE FAILED: %s" % (rid, r.stderr.strip()))
        continue
    def_text = open(def_c).read()
    st = stamps(def_text)
    row["def_c"] = def_c
    row["def_stamps"] = st
    has_vm = st["RX_ENGINE"] == "vm"
    if has_vm:
        np_c = os.path.join(TMP, "%s_np.c" % rid)
        r2 = pcrec_compile(row["inl"], np_c, extra_flags=["-fno-prefilter"])
        if r2.returncode != 0:
            compile_problems.append((rid, "-fno-prefilter compile failed",
                                      r2.stderr))
            print("  %-4s NP COMPILE FAILED: %s" % (rid, r2.stderr.strip()))
            continue
        np_text = open(np_c).read()
        row["np_c"] = np_c
        row["np_stamps"] = stamps(np_text)
        print("  %-4s VM   engine=%s prefilter(def)=%s prefilter(np)=%s "
              "prune_ceiling(def)=%s" %
              (rid, st["RX_ENGINE"], st["RX_VM_PREFILTER"],
               row["np_stamps"]["RX_VM_PREFILTER"],
               st["RX_VM_PRUNE_CEILING"]))
        has_vm_rows.append(row)
    else:
        # groupless / pure-DFA inlined pattern -- verify -fno-prefilter is
        # really a no-op here (diff the two arms) rather than assuming it
        # from the flag's name.
        np_c = os.path.join(TMP, "%s_np.c" % rid)
        r2 = pcrec_compile(row["inl"], np_c, extra_flags=["-fno-prefilter"])
        np_text = open(np_c).read() if r2.returncode == 0 else None
        identical = (np_text is not None and
                     _strip_header_include(def_text) ==
                     _strip_header_include(np_text))
        print("  %-4s DFA  no RX_ENGINE/RX_VM_PREFILTER macros -- "
              "-fno-prefilter arm %s" %
              (rid, "byte-identical (verified)" if identical
               else "DIFFERS from default (unexpected)"))
        row["dfa_identical_verified"] = identical
        dfa_only_rows.append(row)
print()

print("=== STAGE 3: BUILD + TIME (VM-reaching rows only; the DFA-only rows "
      "have no prefilter to time -- see STAGE 2) =============================")
results = []
for row in has_vm_rows:
    rid = row["id"]
    def_bin = os.path.join(TMP, "%s_def.bin" % rid)
    np_bin = os.path.join(TMP, "%s_np.bin" % rid)
    b1 = gcc_build(row["def_c"], def_bin)
    b2 = gcc_build(row["np_c"], np_bin)
    if b1.returncode != 0 or b2.returncode != 0:
        print("  %-4s gcc build FAILED (def rc=%d, np rc=%d)" %
              (rid, b1.returncode, b2.returncode))
        continue
    for variant, with_match in (("match", True), ("nomatch", False)):
        subj_path = os.path.join(TMP, "%s_%s_subj.bin" % (rid, variant))
        n = write_subject(subj_path, with_match, row["matches"][0])
        def_runs = time_binary(def_bin, subj_path)
        np_runs = time_binary(np_bin, subj_path)
        if def_runs is None or np_runs is None:
            print("  %-4s %-7s RUN FAILED" % (rid, variant))
            continue
        def_words = {w for w, _ in def_runs}
        np_words = {w for w, _ in np_runs}
        agree = (def_words == np_words) and len(def_words) == 1
        def_ns = sorted(ns for _, ns in def_runs)
        np_ns = sorted(ns for _, ns in np_runs)
        ratio = np_ns[0] / def_ns[0] if def_ns[0] > 0 else float("nan")
        results.append(dict(id=rid, variant=variant, subj_len=n,
                             def_ns=def_ns, np_ns=np_ns, ratio=ratio,
                             agree=agree, def_word=def_runs[0][0],
                             np_word=np_runs[0][0]))
        print("  %-4s %-7s subj=%dB def(best/med/max ns)=%.0f/%.0f/%.0f "
              "np(best/med/max ns)=%.0f/%.0f/%.0f ratio(np/def)=%.2f "
              "answers-agree=%s (%s vs %s)" %
              (rid, variant, n,
               def_ns[0], statistics.median(def_ns), def_ns[-1],
               np_ns[0], statistics.median(np_ns), np_ns[-1],
               ratio, agree, def_runs[0][0], np_runs[0][0]))
print()

print("=== STAGE 4: DFA-only baseline (no prefilter distinction; reference "
      "only, NOT part of the ratio question) =================================")
for row in dfa_only_rows:
    rid = row["id"]
    def_bin = os.path.join(TMP, "%s_def.bin" % rid)
    b1 = gcc_build(row["def_c"], def_bin)
    if b1.returncode != 0:
        print("  %-4s gcc build FAILED" % rid)
        continue
    subj_path = os.path.join(TMP, "%s_match_subj.bin" % rid)
    n = write_subject(subj_path, True, row["matches"][0])
    def_runs = time_binary(def_bin, subj_path)
    if def_runs is None:
        print("  %-4s RUN FAILED" % rid)
        continue
    def_ns = sorted(ns for _, ns in def_runs)
    print("  %-4s subj=%dB dfa(best/med/max ns)=%.0f/%.0f/%.0f  answer=%s" %
          (rid, n, def_ns[0], statistics.median(def_ns), def_ns[-1],
           def_runs[0][0]))
print()

print("=== STAGE 5: REACHABILITY GUARDS ======================================")
guard1 = any(r["def_stamps"]["RX_VM_PREFILTER"] == "hybrid"
             for r in has_vm_rows)
print("  guard 1 (>=1 default-arm RX_VM_PREFILTER == 'hybrid'): %s"
      % ("PASS" if guard1 else "FAIL -- VACUOUS, no prefilter was ever "
                                "measured"))
guard2 = bool(results) and all(r["agree"] for r in results)
print("  guard 2 (default and -fno-prefilter arms agree on every timed "
      "subject): %s" % ("PASS" if guard2 else "FAIL -- see per-row "
                         "'answers-agree' column above"))
if results:
    spreads = [(r["id"], r["variant"],
                (r["def_ns"][-1] - r["def_ns"][0]) / r["def_ns"][0]
                if r["def_ns"][0] > 0 else float("nan"))
               for r in results]
    max_spread = max(s for _, _, s in spreads)
    print("  guard 3 (noise spread, same binary x3): max spread across all "
          "default-arm rows = %.1f%% (per-row list follows)" %
          (max_spread * 100))
    for rid, variant, s in spreads:
        print("     %-4s %-7s spread=%.1f%%" % (rid, variant, s * 100))
else:
    print("  guard 3: no timed rows -- VACUOUS")
print()
if not (guard1 and guard2 and results):
    print("OVERALL: VACUOUS -- one or more reachability guards failed; do "
          "not trust the ratio numbers above.")
else:
    print("OVERALL: guards satisfied; the ratio table in STAGE 3 is a real "
          "measurement of what the DFA prefilter buys on this population.")
if compile_problems:
    print()
    print("compile problems encountered:")
    for rid, why, err in compile_problems:
        print("  %-4s %s: %s" % (rid, why, err.strip()[:200]))
