#!/usr/bin/env python3
"""THE NULL CONTROL for the batch-2 pin pair: which capability artifacts are
PROGRAM-IDENTICAL between the ledger's BEFORE (8d716693, abi 29) and AFTER
(b1885a83, abi 30)?  A regressing cell sitting on one of these measures the
between-window component the D119 bar's within-window IQR cannot see.

Both sides write to the SAME -o basename in their OWN directory (the house's
recorded -o-basename trap).  Ignored when comparing: the generated-by comment,
the .abi integer, and batch 2's own NEW stamp line RX_REQ_RUN -- everything
else, including the pre-check text and every other #define, is compared.
"""
import os, re, subprocess, json
SCR=os.environ["SCR"]
PATDIR="/Users/fdicostanzo/pcrec-bench/bench/capability/patterns"
BEFORE=f"{SCR}/src_before/build/pcrec"; AFTER=f"{SCR}/src_ledger/build/pcrec"
CONFIGS={"auto-caps":["--features","all"],
         "auto-nocaps":["--features","all","--no-captures"],
         "vm-caps":["--features","all","--engine=vm"]}
def norm(text):
    out=[]
    for ln in text.splitlines():
        if ln.startswith("/* Generated by pcrec"): continue
        if re.match(r'\s*\.abi\s*=', ln): continue
        if ln.startswith("#define RX_REQ_RUN"): continue
        out.append(ln)
    return "\n".join(out)
def emit(binp, pat, flags, d):
    os.makedirs(d, exist_ok=True); out=os.path.join(d,"a.c")
    r=subprocess.run([binp,"-p","rx","-o",out,"--pattern",pat]+flags,
                     capture_output=True,timeout=120)
    if r.returncode!=0: return None
    return open(out,errors="replace").read()
res={}
for fn in sorted(os.listdir(PATDIR)):
    if not fn.endswith(".rx"): continue
    name=fn[:-3]
    pat=open(os.path.join(PATDIR,fn),"rb").read().rstrip(b"\n").decode("utf-8","surrogateescape")
    for cfg,flags in CONFIGS.items():
        b=emit(BEFORE,pat,flags,f"{SCR}/n/b"); a=emit(AFTER,pat,flags,f"{SCR}/n/a")
        if b is None or a is None:
            res[f"{name}|{cfg}"]="refused" if (b is None and a is None) else "refusal-mismatch"
        else:
            res[f"{name}|{cfg}"]="identical" if norm(b)==norm(a) else "changed"
import collections
c=collections.Counter(res.values()); print(dict(c))
ident=sorted(k.split("|")[0] for k,v in res.items() if v=="identical")
allident=[p for p in sorted(set(ident)) if ident.count(p)==3]
print(f"\nartifact-configs program-identical: {c['identical']} of {sum(c.values())}")
print(f"patterns identical on ALL THREE configs: {len(allident)}")
for p in allident: print("   ",p)
json.dump(res,open(f"{SCR}/nullctl.json","w"),indent=1)
