/* Generated by pcrec. Pattern: a */
/* Feature set: std1 (modules: classes,modifiers) */
#ifndef PCREC_GEN_RX_H
#define PCREC_GEN_RX_H

#include <stddef.h>
#include <stdint.h>

#ifndef PCREC_RX_ABI_H
#define PCREC_RX_ABI_H

typedef struct rx_ctx {
    const unsigned char *subject;   /* whole subject, not a slice */
    size_t                len;      /* subject length */
    size_t                pos;      /* where to match, anchored */
    size_t                ncap;     /* capture slots known so far (watermark
                                        mid-match; ncaps on completion) */
    const ptrdiff_t     (*caps)[2]; /* [start,end); {-1,-1} = unset */
    void                 *user;     /* per-binding user data */
} rx_ctx;

/* returns matched length >= 0 (anchored at ctx->pos), -1 (fail), or a
 * typed give-up code in [PCREC_ERR_FLOOR, -2] -- one per way the
 * engine can give up (PCREC_ERR_STEPS/_FRAMES/_WORK/_RECURSE). D49: those
 * codes PROPAGATE, they are not collapsed to -1, and a caller doing
 * an exact `== -1` test sees them as distinct values. Values
 * strictly BELOW PCREC_ERR_FLOOR stay RESERVED for a future abort
 * semantic; PCREC_ERR_INTERNAL ([DD-14] wave A commit 2, D71
 * item 1) is its first producer -- the artifact's own
 * inconsistency check firing, never a resource give-up -- and a
 * generated call site that invokes an rx_matchfn traps on one.
 * Self-contained: must accept ctx->ncap == 0, ctx->caps == NULL. */
typedef ptrdiff_t rx_matchfn(const rx_ctx *ctx);

#define PCREC_ERR_STEPS   (-2)
#define PCREC_ERR_FRAMES  (-3)
#define PCREC_ERR_WORK    (-4)
#define PCREC_ERR_RECURSE (-5)  /* [DD-14] reserved: no producer yet (D71 item 1) */
#define PCREC_ERR_FLOOR   (-5)  /* give-ups: [FLOOR,-2]; below: reserved (D49) */

#define PCREC_ERR_INTERNAL (-6)  /* [DD-14] below PCREC_ERR_FLOOR: NOT a give-up, D71 item 1 */
#define PCREC_ERR_STARTPOS (-7)  /* [K50] below PCREC_ERR_FLOOR: NOT a give-up -- a mid-character startpos was REFUSED */

#define PCREC_UNSET ((ptrdiff_t)-1)

typedef struct rx_callout_ref {
    rx_matchfn *fn;
    void       *user;
} rx_callout_ref;

/* Emitted ONLY when a substitution template names it. Renders one
 * template segment from the same rx_ctx a callout receives. Writes at
 * most outcap bytes to out; returns the number of bytes produced, or
 * -1 to fail. Called with out == NULL and outcap == 0, it returns the
 * length it WOULD produce, writing nothing. */
typedef ptrdiff_t rx_renderfn(const rx_ctx *ctx,
                              unsigned char *out, size_t outcap);

typedef struct {
    const char *name;
    int         number;
    int         slot;   /* caps[] index this entry delivers, or -1 if
                           this build delivers no slot for it */
    const char *ref;    /* NULL/empty for the primary's own groups */
} rx_group_entry;

struct rx_info {
    unsigned      abi;             /* layout version */
    uint64_t      flags;           /* PCREC_* option bits, as compiled */
    int           encoding;        /* PCREC_ENC_* */
    int           ncaps;           /* == this artifact's own
                                       <PREFIX>_NCAPS: its caps[]
                                       slot count, all-in */
    int           ngroups;         /* capturing groups in the pattern's
                                       own TEXT (a lexical fact) */
    int           nnames;          /* entries in groups[], named only */
    unsigned      engine;          /* PCREC_ENGINE_DFA=1 /
                                       PCREC_ENGINE_VM=2 */
    int64_t       step_budget;     /* -1 = none */
    int64_t       work_budget;     /* -1 = none. The THIRD bound (D47
                                       SECOND ADDENDUM): per-iteration
                                       forward work the fail label
                                       never sees, in work units. A
                                       step is a backtrack resumption
                                       and is counted separately. */
    int64_t       frame_capacity;  /* -1 = unbounded */
    int64_t       subject_ceiling; /* 0 = unset/not applicable */
    int64_t       resume_frames;   /* stamped DEFAULT capacity, in
                                       frames; 0 = no resume stack */
    int64_t       trail_frames;    /* ditto, in trail entries */
    int32_t       resume_frame_size; /* bytes per resume frame */
    int32_t       trail_frame_size;  /* bytes per trail entry */
    const char           *pattern;     /* source pattern text */
    size_t                pattern_len; /* companion length (K9-proof) */
    const rx_group_entry *groups;       /* sorted, bsearch-able */
    const char           *engine_why;   /* forcing construct/reason, or NULL */
    const char           *scan;         /* the DFA scan this artifact
                                           CONTAINS: "unanchored" /
                                           "attempt" / "empty",
                                           mirroring <PREFIX>_DFA_SCAN.
                                           NULL when there is none --
                                           i.e. on a VM artifact that is
                                           not a hybrid. A non-NULL
                                           value on a VM artifact IS
                                           "this is a hybrid". */
    const char           *prefilter;    /* this artifact's CANDIDATE-START
                                           mechanism, in whichever
                                           engine's vocabulary applies:
                                           the DFA's five values
                                           (<PREFIX>_DFA_PREFILTER) when
                                           `scan` is non-NULL, and the
                                           VM's "none"
                                           (<PREFIX>_VM_PREFILTER) when
                                           it is NULL. Never NULL. */
    /* [ENG-ABS] HOW <prefix>_match answers: "unwrapped" (its own
       anchored machine, run from ctx->pos) or "search-filter" (the
       unanchored search, with non-ctx->pos starts rejected),
       mirroring <PREFIX>_DFA_MATCH. NULL on every artifact whose
       _match this engine did not write. */
    const char           *match_form;
    /* [DD-13b.W1.2] this artifact's own name: the `.rxt` block's
       `name` when a source named one, the <prefix> otherwise.
       NEVER NULL. */
    const char           *name;
    /* [DD-13b.W1.2] rows in groups[], ALL of them. `nnames` counts
       the PRIMARY pattern's own, which are a PREFIX of the array;
       the two are equal on every artifact pcrec emits today. */
    int                   nentries;
    /* [OPT-5 STEP 2] HOW <prefix>_search recovers the match START:
       "pinned" (the start is search_from by compile-time proof, and
       this artifact carries no reverse machine at all) or
       "reverse-pass" (the second, backwards scan), mirroring
       <PREFIX>_DFA_START. The two forms are ANSWER-IDENTICAL and
       differ only in cost. NON-NULL on every artifact that CONTAINS
       a DFA scan, a VM HYBRID INCLUDED -- a hybrid inlines this same
       search body as its prefilter, so unlike match_form the guard
       is "has a DFA scan" and not "the DFA emitter wrote _match".
       NULL only on a plain VM artifact. */
    const char           *search_form;
};

#define PCREC_ENGINE_DFA 1
#define PCREC_ENGINE_VM  2

#define PCREC_VM_RUNG_CURSOR           0x1u
#define PCREC_VM_RUNG_FRAMES_BOUNDED   0x2u
#define PCREC_VM_RUNG_FRAMES_UNBOUNDED 0x4u
#define PCREC_VM_RUNG_REVDET           0x8u
#define PCREC_VM_RUNG_COUNTER          0x10u
#define PCREC_VM_STRAT_POSSESSIVE      0x1u
#define PCREC_VM_STRAT_BACKTRACKING    0x2u
#define PCREC_VM_PRUNE_CLAMPED         0x1u
#define PCREC_VM_PRUNE_UNCLAMPED       0x2u

/* Every generated artifact also exports one RESIDUAL entry per
 * encoding (pcrec DD-12/D58), <prefix>-scoped and therefore declared
 * outside this shared block:
 *
 *   size_t <prefix>_next_pos(const unsigned char *s, size_t n,
 *                            size_t pos);
 *
 * It returns the next CHARACTER boundary strictly after pos (every
 * position >= n counts as a boundary), and it is the one place an
 * artifact's byte-vs-character distinction lives: a find-all loop
 * advances past a zero-length match with it and needs no change when
 * the same pattern is compiled for another encoding. Full contract:
 * that declaration's own comment, and pcrec's
 * docs/spec/match_api.md S3.1. */

#endif /* PCREC_RX_ABI_H */

#define RX_NCAPS 1

/* [DD-14.FB] The caller-provided working storage (spec §10).
 *
 *   RX_RESUME_FRAMES / _TRAIL_FRAMES   the capacities this artifact
 *       uses when it supplies the storage itself -- a DEFAULT, not a
 *       limit. 0 on a DFA artifact, which has neither array.
 *   RX_RESUME_FRAME_SIZE / _TRAIL_FRAME_SIZE   bytes per frame and
 *       per trail entry FOR THIS ARTIFACT. The layouts themselves are
 *       private; this is the arithmetic that replaces them.
 *   RX_BUFFER_ALIGN   the alignment both regions require. Storage
 *       from any ordinary allocator, mapping or object declaration
 *       already satisfies it; the macro is for a caller carving a
 *       region out of an arena.
 */
#define RX_RESUME_FRAMES 0
#define RX_TRAIL_FRAMES 0
#define RX_RESUME_FRAME_SIZE 0
#define RX_TRAIL_FRAME_SIZE 0
#define RX_BUFFER_ALIGN 1

/* Where one match attempt's working storage lives. Pass NULL to any
 * <prefix>_*_in entry and it is EXACTLY a call to the un-suffixed
 * sibling, with this artifact's own stamped default storage on that
 * entry's stack frame.
 *
 * THE COUNTS ARE CAPACITIES, NOT BYTE SIZES: `nframes` is how many
 * FRAMES the region holds, `ntrail` how many trail ENTRIES. A caller
 * that reserved `bytes` gets `bytes / RX_RESUME_FRAME_SIZE` and
 * `bytes / RX_TRAIL_FRAME_SIZE` -- BUT CHECK THE SIZE FIRST: a stamped
 * size of 0 means this artifact's engine takes no buffers at all (every
 * DFA artifact stamps 0), so dividing by it is a division by zero. Pass
 * NULL on such an artifact; the _in entries accept a descriptor and
 * ignore it either way. Both regions are required when the
 * descriptor is non-NULL, and both are pure scratch: their contents
 * after any call are unspecified and no call reads what a previous
 * one left. Two concurrent calls must not share one region -- that is
 * a race in the caller's code exactly as a shared caps array is. */
typedef struct {
    void   *frames;    /* storage for resume frames */
    size_t  nframes;   /* capacity in FRAMES, not bytes */
    void   *trail;     /* storage for trail entries */
    size_t  ntrail;    /* capacity in ENTRIES, not bytes */
} rx_buffers;

int rx_search(const unsigned char *subject, size_t subject_length, size_t search_from, ptrdiff_t (*capture_spans)[2]);
ptrdiff_t rx_match(const rx_ctx *ctx);
ptrdiff_t rx_match_caps(const rx_ctx *ctx, ptrdiff_t (*capture_spans_out)[2]);
extern const struct rx_info rx_info;
int rx_search_in(const unsigned char *subject, size_t subject_length, size_t search_from, ptrdiff_t (*capture_spans)[2], const rx_buffers *buffers);
ptrdiff_t rx_match_in(const rx_ctx *ctx, const rx_buffers *buffers);
ptrdiff_t rx_match_caps_in(const rx_ctx *ctx, ptrdiff_t (*capture_spans_out)[2], const rx_buffers *buffers);

/* rx_next_pos -- the ENCODING RESIDUAL entry (pcrec DD-12/D58).
 *
 * Returns the smallest position STRICTLY GREATER than pos that is a
 * CHARACTER BOUNDARY of this artifact's encoding, counting every position
 * >= n as a boundary. So the result is in (pos, n] whenever pos < n, and is
 * pos + 1 whenever pos >= n -- which is what lets a find-all loop advance
 * past a zero-length match and still terminate (see pcrec's
 * docs/spec/match_api.md S3.1, which writes that loop out).
 *
 * This entry is the ONE place an artifact's byte-vs-character distinction
 * lives. It reads s only at offsets in [pos, n), so the (s == NULL, n == 0)
 * subject rx_search accepts is legal here too, and it is never called from
 * this artifact's own engine: it is caller-facing residue, not hot-path
 * code.
 *
 * THIS artifact was compiled for the `byte` encoding, where one byte is one
 * character. An artifact compiled for another encoding exports this same
 * entry with that encoding's body and no caller loop changes. */
size_t rx_next_pos(const unsigned char *s, size_t n, size_t pos);

#endif /* PCREC_GEN_RX_H */
