#!/usr/bin/env python3
"""Stand-in for build/pcrec in `gapreport.sh --check`: the pattern text IS the
stamp source ("k=v;k=v" becomes `#define RX_K "v"`); text starting REFUSE is a
refusal.  Deterministic, so the fixture's stamp census never depends on a build."""
import sys

a = sys.argv[1:]
out = a[a.index("-o") + 1]
pat = a[a.index("--pattern") + 1]
if pat.startswith("REFUSE"):
    sys.stderr.write("pcrec: " + pat + "\n")
    sys.exit(1)
lines = ["/* Generated by pcrec fake (abi 99). */"]
for kv in pat.split(";"):
    k, v = kv.split("=")
    lines.append('#define RX_%s "%s"' % (k.upper(), v))
open(out, "w").write("\n".join(lines) + "\n")
open(out[:-2] + ".h", "w").write("/* header */\n")
