#!/usr/bin/env bash
# tests/codegen/run_comments_axis.sh -- [EMIT-VERB] (D112): the emitted-comment
# axis. `-fno-comments` removes the artifact's NON-ESSENTIAL prose and nothing
# else; `-fcomments` restores it.
#
# WHAT THIS SCRIPT IS FOR, stated as the four claims the axis makes and the
# way each is falsifiable here rather than as a list of greps:
#
#   (1) A DEFAULT artifact carries ONLY the ESSENTIAL comments -- the
#       generated-by/pattern-echo provenance line and the shared
#       `PCREC_RX_ABI_H` type block's doc-comments. Any other comment LINE in
#       a default artifact is a site somebody added without classifying it.
#   (2) `-fcomments` restores the rest. Checked as a STRICT inequality per
#       artifact, which is what stops (1) passing vacuously on an emitter that
#       had stopped emitting comments at all.
#   (3) The OBJECT FILE is identical under both settings. This is the axis's
#       central claim and the reason it is not a performance axis. Its own
#       positive control is in the same arm: the SOURCES must differ, so a
#       green cannot come from the flag being ignored.
#   (4) No SIZE decision moves. The comment-excluded size and every emitted
#       `#define` stamp read the same under both settings -- measured after
#       the entry-shape term was found reading a comment-INCLUSIVE byte count
#       (the lane report's SS3a; `pcrec_sb_len_uncut` is the fix).
#
# AND (5), the half-comment hazard, which is what an UNBALANCED region looks
# like from outside: a region opened and not closed mutes the rest of its
# buffer, and a comment whose opener is gated while its body is not leaves
# stray `*` lines in the C. Neither is visible to any byte-identity gate --
# the DEFAULT artifact is what changes -- so every artifact this script emits
# is COMPILED with the harness's own `-Wall -Wextra -Werror`.
set -u
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
PCREC="${PCREC:-$ROOT_DIR/build/pcrec}"
CC="${CC:-cc}"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
# THE TWO BUILDS GET THE SAME BASENAME IN DIFFERENT DIRECTORIES, and that is
# load-bearing rather than tidy: an artifact carries `#include "<basename>.h"`
# derived from `-o`, so two builds written to `x_def.c` and `x_full.c` differ
# on that line and on nothing else -- which makes this script's own
# "the sources differ" control pass for the wrong reason and its
# comment-excluded size comparison read a one-byte move that is not there.
# The trap has now been recorded five times in this tree (dd8 report SS3.1,
# scripts/emit_sweep.py's header); it is cheap to avoid and expensive to
# diagnose.
mkdir -p "$WORK/def" "$WORK/full"
. "$ROOT_DIR/tests/lib/gen_timeout.sh"

pass=0; fail=0
ok()  { printf 'PASS: %s\n' "$1"; pass=$((pass+1)); }
bad() { printf 'FAIL: %s\n' "$1"; fail=$((fail+1)); }
GENCFLAGS_TEST="-Wall -Wextra -Werror -O1"

# The population. Chosen to reach both engines, the hybrid, the offset-skip
# and scan-edge prefilters, the anchored form, a backreference, a lookaround
# and a counted repeat -- i.e. the emitters' comment-bearing families, not a
# pattern each from a list. `#` separates a label from the pattern.
CASES=(
  "dfa-plain#abc"
  "dfa-class#[a-z]+@[a-z]+"
  "dfa-anchored#^(?:foo|bar)*baz\$"
  "dfa-scanedge#a{2,40}Z"
  "dfa-wordctx#\\\\bword\\\\b"
  "vm-captures#a(b|c)+d"
  "vm-backref#(a)(b)(c)\\\\1"
  "vm-look#x(?=y)z(?<!q)"
  "vm-counted#(?:ab|cd){3,7}"
)

# ---- the ESSENTIAL set, as a RECOGNISER over the default artifact ----------
# A default artifact's comment lines must be exactly: the provenance line, and
# the lines of the shared `PCREC_RX_ABI_H` block. The block is recognised by
# its own guard rather than by a list of its sentences, so a doc-comment added
# INSIDE it stays essential with no edit here and one added OUTSIDE it fails.
# Prints every comment line that is neither.
unexpected_comments() {
    awk '
      /^#ifndef PCREC_RX_ABI_H/ { abi = 1 }
      /^#endif \/\* PCREC_RX_ABI_H/ { abi = 0; next }
      {
        line = $0; sub(/^[ \t]+/, "", line)
        if (inblk) { if (!abi) print FILENAME ": " $0; if (index($0, "*/") > 0) inblk = 0; next }
        if (line ~ /^\/\*/) {
          if (!abi && $0 !~ /^\/\* Generated by pcrec [^ ]+ \(abi [0-9]+\)\. Pattern: /) print FILENAME ": " $0
          rest = substr($0, index($0, "/*") + 2)
          if (index(rest, "*/") == 0) inblk = 1
          next
        }
        if (line ~ /^\/\//) { if (!abi) print FILENAME ": " $0 }
      }' "$@"
}

count_comment_lines() {
    awk '
      { line = $0; sub(/^[ \t]+/, "", line)
        if (inblk) { n++; if (index($0, "*/") > 0) inblk = 0; next }
        if (line ~ /^\/\*/) { n++; rest = substr($0, index($0, "/*") + 2)
                              if (index(rest, "*/") == 0) inblk = 1; next }
        if (line ~ /^\/\//) n++ }
      END { print n + 0 }' "$@"
}

# tests/lib/size_count.sh's definition, so arm 4 measures the same quantity
# the caps and the size log do rather than a second one.
. "$ROOT_DIR/tests/lib/size_count.sh"

total_unexpected=0
for case in "${CASES[@]}"; do
    label="${case%%#*}"; pat="${case#*#}"
    def_c="$WORK/def/${label}.c"; full_c="$WORK/full/${label}.c"
    if ! pcrec_run "$PCREC" -p rx --features all -o "$def_c" --pattern "$pat" >"$WORK/$label.log" 2>&1; then
        bad "[$label] the DEFAULT build failed: $(head -2 "$WORK/$label.log")"; continue
    fi
    if ! pcrec_run "$PCREC" -p rx --features all -fcomments -o "$full_c" --pattern "$pat" >>"$WORK/$label.log" 2>&1; then
        bad "[$label] the -fcomments build failed: $(head -2 "$WORK/$label.log")"; continue
    fi
    def_h="${def_c%.c}.h"; full_h="${full_c%.c}.h"

    # (1) only ESSENTIAL comments survive the default
    stray="$(unexpected_comments "$def_c" "$def_h" 2>/dev/null | head -6)"
    if [ -z "$stray" ]; then
        ok "[$label] the default artifact carries only its ESSENTIAL comments"
    else
        total_unexpected=$((total_unexpected+1))
        bad "[$label] the default artifact carries a NON-ESSENTIAL comment -- an emission site was added without an pcrec_sb_cmt_open class (D112 item 2). First: $(printf '%s' "$stray" | head -2 | tr '\n' ' ')"
    fi

    # (2) -fcomments restores strictly more, per artifact
    nd="$(count_comment_lines "$def_c" "$def_h")"
    nf="$(count_comment_lines "$full_c" "$full_h")"
    if [ "$nf" -gt "$nd" ] && [ "$nd" -gt 0 ]; then
        ok "[$label] -fcomments restores prose ($nd essential lines -> $nf), and the essential set is non-empty"
    else
        bad "[$label] comment-line counts are default=$nd forced=$nf -- the forced build must carry strictly more, and the default must carry its essential set (a zero here would make check (1) vacuous)"
    fi

    # (3) THE OBJECT FILES ARE IDENTICAL, with the sources' difference as the
    #     arm's own positive control.
    if cmp -s "$def_c" "$full_c"; then
        bad "[$label] the two SOURCES are byte-identical -- -fcomments changed nothing, so the object comparison below would pass vacuously"
    else
        ok "[$label] the two sources differ (the flag reached the emitter)"
    fi
    if "$CC" $GENCFLAGS_TEST -I"$WORK/def" -c -o "$WORK/${label}_def.o" "$def_c" 2>"$WORK/${label}_def.cc" \
       && "$CC" $GENCFLAGS_TEST -I"$WORK/full" -c -o "$WORK/${label}_full.o" "$full_c" 2>"$WORK/${label}_full.cc"; then
        ok "[$label] both artifacts compile under $GENCFLAGS_TEST (a half-removed comment is a C syntax error, not a silent one)"
        if cmp -s "$WORK/${label}_def.o" "$WORK/${label}_full.o"; then
            ok "[$label] the OBJECT FILES are byte-identical -- the axis costs no object byte"
        else
            bad "[$label] the object files DIFFER: something other than comment text moved. Check every size decision for a raw StrBuf length (pcrec_sb_len_uncut is the rule)"
        fi
    else
        bad "[$label] an artifact failed to compile: $(cat "$WORK/${label}_def.cc" "$WORK/${label}_full.cc" 2>/dev/null | grep -m2 error)"
    fi

    # (4) no SIZE decision and no STAMP moves
    sd="$(size_count_bytes "$def_c" "$def_h")"
    sf="$(size_count_bytes "$full_c" "$full_h")"
    if [ "$sd" = "$sf" ]; then
        ok "[$label] the comment-EXCLUDED size is identical ($sd) -- the emitted-size caps cannot move over this axis"
    else
        bad "[$label] the comment-excluded size moved: default=$sd forced=$sf. The caps are defined on this quantity (limits.def), so the refusal set would move with it"
    fi
    # LC_ALL=C on both sorts (K35): under the ambient locale punctuation is
    # ignorable, and a stamp line is mostly punctuation.
    grep -h '^#define ' "$def_c" "$def_h" 2>/dev/null | LC_ALL=C sort > "$WORK/${label}_def.stamps"
    grep -h '^#define ' "$full_c" "$full_h" 2>/dev/null | LC_ALL=C sort > "$WORK/${label}_full.stamps"
    if cmp -s "$WORK/${label}_def.stamps" "$WORK/${label}_full.stamps"; then
        ok "[$label] every emitted #define is identical -- stamps are not comments (D112 item 3)"
    else
        bad "[$label] an emitted #define moved: $(diff "$WORK/${label}_def.stamps" "$WORK/${label}_full.stamps" | head -4 | tr '\n' ' ')"
    fi
done

# ---- 6. deny beats force, the precedence every other pair in the enum has --
pcrec_run "$PCREC" -p rx -fcomments -fno-comments -o "$WORK/prec.c" --pattern 'abc' >/dev/null 2>&1
if [ -s "$WORK/prec.c" ]; then
    if [ -z "$(unexpected_comments "$WORK/prec.c" 2>/dev/null)" ]; then
        ok "[precedence] -fcomments -fno-comments is comment-free (deny wins over force)"
    else
        bad "[precedence] -fcomments -fno-comments kept non-essential prose -- force is beating deny, which inverts every other pair's precedence"
    fi
else
    bad "[precedence] the two-flag build produced nothing"
fi

# ---- 7. the axis is ADVERTISED and ACCEPTED (the registry's own half is in
#         axes_registry_check.sh; this is the artifact-side half) ------------
if pcrec_run "$PCREC" --list-axes 2>/dev/null | grep -q '^comments	'; then
    ok "[registry] --list-axes advertises the comments axis"
else
    bad "[registry] --list-axes does not advertise the comments axis"
fi

printf '\n== Summary ==\nchecks passed: %d\nchecks failed: %d\n' "$pass" "$fail"
[ "$fail" -eq 0 ]
