#!/usr/bin/env python3
"""tests/revend/gen_rev_end.py -- [OPT-REVEND] L2 (lane revbuild): write
tests/assertions/rev_end.rxt FROM libpcre2's answers (oracle first: every
m/n/ms/ns line is the oracle's answer, never pcrec's), the answer net of
docs/design/revend.md §9.3 for the `rev-end` LOCATE row: matching and
non-matching tails, the final newline with both seeds, lazy and greedy ties,
startpos at 0 / mid-match / n-1 / n, nullable bodies, mixed pins, the X1
trailing-lookaround shapes, utf8 tails and a utf8 tie. Capture groups are
tests/revend/stage2_captures.rxt's; these blocks are capture-free, so the
default build routes them to the DFA (the walk on its own) and
`--engine=vm` / `-fno-rev-end` (the axes sweep) to the other finishers.
Family G is the exception: stage 2's captures net (locate_finish.md §5 L3),
capture-bearing, so the default build routes it to the VM hybrid whose inlined
prefilter walks; its `g` lines are the oracle's group spans.

Usage: gen_rev_end.py ORACLE_BIN SCRATCH_DIR > tests/assertions/rev_end.rxt
ORACLE_BIN is tests/fuzz/pcre2_oracle.c built against libpcre2-8 (options=0:
`encoding utf8` is carried as a (*UTF) prefix). Re-check the written file
with `tests/revend/verify_stage2.py ORACLE_BIN SCRATCH tests/assertions/rev_end.rxt`,
which shares no code with this table. A subject's startpos is at most its
length: libpcre2 refuses a larger one, and pcrec's `search_from > n` NOMATCH
is held by the codegen check instead. K74's ill-formed-end cells are out of
scope (revend.md §9.3, X12)."""
import os, subprocess, sys

CELLS = []

def C(pat, why, subs, utf8=False):
    CELLS.append((pat, utf8, why, subs))

def S(*xs):
    return [(0, x) for x in xs]

def SP(s, *sps):
    return [(sp, s) for sp in sps]

HEADER = """# [OPT-REVEND] L2 THE `rev-end` ANSWER NET (lane revbuild; revend.md §9.3,
# locate_finish.md §5 L2). GENERATED by tests/revend/gen_rev_end.py from
# libpcre2 10.46's answers (every m/n/ms/ns line is the oracle's, never
# pcrec's); tests/revend/verify_stage2.py re-reads this file and re-asks the
# oracle. python `re` is not an oracle here (its `\\Z` is PCRE2's `\\z`), so
# every block is `# pcre2-only`. Family G aside, capture-free: the default build runs the
# reverse-from-end walk on the DFA (`<PREFIX>_DFA_SCAN "rev-end"`); the axes
# sweep runs the same cells under `-fno-rev-end`, `-fno-anchored-dfa` (the tie
# relocates instead of running the anchored machine) and `--engine=vm`. Family G
# (stage 2's captures net) carries groups: a VM hybrid whose inlined prefilter
# walks, its `g` lines the oracle's group spans.
#
# FAMILIES: T the two seeds and their ties (lazy and greedy); P startpos at 0,
# mid-match, n-1 and n; E empty matches and nullable bodies; X trailing
# lookarounds (a dead seed, X1); M mixed pins; U utf8 tails; W word context
# at the start edge; D declines; S a superset hybrid; G stage 2's captures;
# B bounded widths the end window also serves."""

# ---- T: the seeds and their ties ------------------------------------------
C(r"\d+$", "T: one seed: digits cannot take the final newline (no tie code)",
  S("abc123", "abc123\n", "123\n\n", "12a", "", "\n", "7"))
C(r"\s+$", "T: a TIE: whitespace can end at n or at n-1, greedy prefers n",
  S("a  ", "a  \n", "a \n", "\n", " \n", "a\n\n", "  \n\n", "a"))
C(r"\s+?$", "T: the LAZY tie: the anchored run picks n-1 where both ends reach the start",
  S("a  ", "a  \n", " \n", "\n", "  \n", "x"))
C(r"\s*$", "T: nullable greedy tie: (0,2) on a space then newline",
  S(" \n", "\n", "a \n", "ab", "a\n\n"))
C(r"\s*?$", "T: nullable lazy tie: (0,1) on a space then newline",
  S(" \n", "\n", "a \n", "ab", "a\n\n"))
C(r"[a-z]+\.txt$", "T: a literal tail, no tie possible",
  S("file.txt", "file.txt\n", "a.txt.bak", "dir/x.txt", ".txt", "file.dat\n"))
C(r"a\z", "T: `\\z`: one seed only",
  S("a", "ba", "a\n", "aa\n", ""))
C(r"a\Z", "T: `\\Z`: both seeds, no tie (a cannot be a newline)",
  S("a", "a\n", "a\n\n", "ba\n", "\n"))
C(r"[a\n]+$", "T: a class holding the newline: a tie at every subject ending in it",
  S("aa\n", "a\n\n", "\n", "a", "b\n"))
C(r"(?:a|a\n)$", "T: alternation priority between the ends (shorter arm first)",
  S("a\n", "a", "ba\n"))
C(r"(?:a\n|a)$", "T: alternation priority between the ends (longer arm first)",
  S("a\n", "a", "ba\n"))
# ---- P: startpos ------------------------------------------------------------
C(r"\w+$", "P: startpos at 0, mid-match, n-1 and n",
  SP("ab cd", 0, 1, 3, 4, 5) + SP("ab cd\n", 4, 5, 6))
C(r"\s*$", "P: an empty match at n and at n-1 from a startpos there",
  SP("ab\n", 0, 2, 3) + SP("ab", 1, 2))
C(r"b\z", "P: a seed below the startpos is skipped",
  SP("ab", 0, 1, 2) + SP("abb", 2, 3))
C(r"[^\n]*\n?$", "P: tie shapes from inside the match",
  SP("ab\n", 0, 1, 2, 3) + SP("ab\n\n", 3, 4))
# ---- E: empty and nullable --------------------------------------------------
C(r"a*$", "E: nullable: (2,2) at the end of 'bb'; (0,2) on 'aa\\n' from seed n-1",
  S("bb", "aa\n", "aa", "", "\n", "ba\n\n"))
C(r"$", "E: the empty pattern pinned at the end",
  S("", "a", "a\n", "\n\n"))
C(r"\z", "E: the empty pattern pinned at n",
  S("", "a", "a\n"))
C(r"(?:ab)?$", "E: an optional body: the empty end match when it cannot",
  S("ab", "xab\n", "x", "abab\n"))
# ---- X: trailing lookarounds (a speculative seed may be dead) --------------
C(r"\d+$(?=\n)", "X: the seed at n reads no byte: dead, skipped",
  S("12\n", "12", "12\n\n", "a1\n"))
C(r"\d$(?!\n)", "X: a negative lookahead after the end",
  S("1", "1\n", "12", "1\n\n"))
C(r"a\Z(?=\n)", "X: `\\Z` then a newline lookahead",
  S("a\n", "a", "ba\n"))
C(r"a$\b", "X: a trailing word boundary is zero-width",
  S("a", "a\n", "aa", "ba ", "a\n\n"))
# ---- M: mixed pins ----------------------------------------------------------
C(r"\d+$|\w+\z", "M: a `$` branch and a `\\z` branch: both seeds, the views reject `\\z` at n-1",
  S("ab12", "ab12\n", "ab\n", "ab", "x\n"))
C(r"\s*$|x\z", "M: a tie-capable mix",
  S(" \n", "x", "x\n", " x"))
# ---- U: utf8 ----------------------------------------------------------------
C("é+$", "U: a multi-byte tail; offsets are bytes", S("aéé", "aéé\n", "é", "ée"), utf8=True)
C(r"\s+?$", "U: a utf8 tie", S("é \n", " \n", "é"), utf8=True)
C(r".$", "U: one character before the end, after an ASCII and a multi-byte prefix",
  S("aé", "aé\n", "é\n", "ab\n"), utf8=True)
# ---- W: word context at the start edge -------------------------------------
C(r"\bab$", "W: a leading boundary reads the byte before the start",
  S("ab", "xab", "x ab", "ab\n") + SP("x ab", 1, 2))
C(r"\Bb$", "W: a non-boundary at the start", S("ab", "b", "a b\n") + SP("ab", 1))
# ---- D: declines (end_pin's three structural declines, and an optional pin) -
C(r"(?:a$)?", "D: an optional end-anchored group pins nothing (rmin == 0): the empty match at 0",
  S("b", "ab", "a", "a\n", ""))
C(r"(?:a$)?\b", "D: the same with a trailing zero-width item", S("b", "a", " a"))
C(r"(?m)a$", "D: a multiline `$` holds before every newline: not end-pinned",
  S("a\nb", "ba\nc\n", "b\na", "a"))
C(r"\Ga$|b$", "D: `\\G` anywhere declines (it reads the startpos)",
  SP("xa", 0, 1) + SP("ab", 0, 1) + S("a"))
# ---- S: a superset hybrid (lookaround erased: the walk's start is a bound) ---
C(r"\w{1,2}(?:(?=)|)$", "S: an erased lookaround makes the prefilter a superset; the VM decides",
  S("ab", "abc", "abc\n", "a b\n", " "))
# ---- G: stage 2's captures net (locate_finish.md §5 L3): VM hybrids --------
C(r"(\d+)$", "G: digits in a group: the hybrid's inlined walk, the VM places the group",
  S("abc123", "abc123\n", "12a", "\n", "7") + SP("ab12", 3))
C(r"(a+)$", "G: a run that cannot take the final newline", S("baa", "baa\n", "aa\n\n", "b"))
C(r"a\Kb$", "G: `\\K` moves the reported start; the walk's start bounds the attempt",
  S("ab", "xab\n", "abab", "b"))
C(r"([^c]{1,3})$", "G: the unclamped tie: the group can take the final newline",
  S("ab\n", "a\n", "\n", "abcd\n", "c"))
C(r"(\s+){2}$", "G: a clamped tie (count-collapsed body): greedy",
  S("a  \n", "a \n", "  ", " \n\n", "a"))
C(r"(\s$){1,3}", "G: a clamped tie with the pin inside the repeat", S(" \n", " ", "a \n", "\n"))
C(r"(\s+?){2}$", "G: the LAZY clamped tie (r2 E3's witness)", S("a  \n", " \n", "a   ", "  \n\n"))
C(r"(\w{1,2})(?:(?=)|)$", "G: the superset witness: an erased lookaround, the walk's start is a bound",
  S("abc", "abc\n", "a b\n", " "))
# ---- B: bounded widths (W1's population, now the walk's) -------------------
C(r"abc$", "B: a fixed literal tail", S("xxabc", "abc\n", "abcabc", "ab"))
C(r"[a-z]{2,4}$", "B: a bounded class run", S("abcdef", "ab\n", "a", "a bc\n"))
C(r"x[ab]?\z", "B: bounded with an optional tail", S("xa", "x", "xab", "xb\n"))

def esc(ch_s):
    out = []
    for ch in ch_s:
        if ch == "\n": out.append("\\n")
        elif ch == '"': out.append('\\"')
        elif ch == "\\": out.append("\\\\")
        elif 32 <= ord(ch) < 127: out.append(ch)
        else: out.append("".join("\\x%02x" % x for x in ch.encode("utf-8")))
    return "".join(out)

def oracle(binp, scratch, pat, utf8, subj, sp):
    f = os.path.join(scratch, "rsubj")
    with open(f, "wb") as h:
        h.write(subj.encode("utf-8"))
    r = subprocess.run([binp, ("(*UTF)" if utf8 else "") + pat, f, str(sp)],
                       capture_output=True, timeout=60)
    return r.stdout.decode().split()

def main():
    binp, scratch = sys.argv[1:3]
    os.makedirs(scratch, exist_ok=True)
    print(HEADER)
    for pat, utf8, why, subs in CELLS:
        print()
        print("# " + why)
        print("# pcre2-only")
        print("pattern " + pat)
        if utf8: print("encoding utf8")
        fs = []
        if any(t in pat for t in ("\\z", "\\Z", "\\b", "\\B", "\\G", "\\K", "(?m)")): fs.append("assertions")
        if any(t in pat for t in ("\\d", "\\w", "\\s", "[")): fs.append("classes")
        if "(?=" in pat or "(?!" in pat: fs.append("lookaround")
        if "(?m)" in pat: fs.append("modifiers")
        if fs: print("features " + ",".join(fs))
        for sp, s in subs:
            ans = oracle(binp, scratch, pat, utf8, s, sp)
            if not ans or ans[0] not in ("match", "nomatch"):
                sys.exit("oracle: %r on %r at %d: %s" % (pat, s, sp, ans))
            pre = "" if sp == 0 else "%d " % sp
            if ans[0] == "nomatch":
                print('%s %s"%s"' % ("n" if sp == 0 else "ns", pre, esc(s)))
            else:
                print('%s %s"%s" %s %s' % ("m" if sp == 0 else "ms", pre, esc(s), ans[1], ans[2]))
                v = ans[1:]
                for k in range(1, len(v) // 2):
                    print("g %d %s %s" % (k, v[2 * k], v[2 * k + 1]))

main()
