#!/bin/sh
# Regenerate every archived output in ../out/ that is cheap enough to re-run
# on demand, each with a D35-style source-information header so a number in
# k23_design.md can always be traced to the build that produced it.
#
#   archive.sh          the cheap set (~3 minutes)
#   archive.sh --all    adds the two differentials (~45 minutes) -- run it
#                       in the background and poll the files, never in the
#                       foreground.
#
# The two differentials and the three-level cell are NOT in the cheap set;
# they are the slow measurements and their archived outputs are committed
# rather than regenerated on every run.
LC_ALL=C; export LC_ALL

HERE=$(cd "$(dirname "$0")" && pwd)
OUT="$HERE/../out"
ROOT=$(cd "$HERE/../../../.." && pwd)
: "${PCREC:=$ROOT/build/pcrec}"
mkdir -p "$OUT"

hdr() {
    printf '# %s\n' "$1"
    printf '# generated by probes/%s on %s\n' "$2" "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    printf '# repo commit  %s\n' "$(cd "$ROOT" && git rev-parse --short HEAD 2>/dev/null)"
    printf '# gcc          %s\n' "$(gcc --version | head -1)"
    printf '# python3      %s\n' "$(python3 --version 2>&1)"
    printf '# pcrec        %s\n' "$PCREC"
    printf '#\n'
}

{
    hdr 'K23 exemplar: exact steps vs subject length' 'steps.sh'
    printf '# columns: n  steps  verdict\n'
    "$HERE/steps.sh" '(a{10,20}){10,50}' \
        95,99,100,101,105,110,120,130,140,145,149,150,151,160,200,300
} > "$OUT/steps_curve.txt"

{
    hdr 'The closed-form law, checked against measurement' 'model.py --check'
    python3 "$HERE/model.py" --check
    printf '\n'
    hdr 'Where the law crosses the 10^6 default budget' 'model.py --grid'
    python3 "$HERE/model.py" --grid
} > "$OUT/model.txt"

{
    hdr 'Baseline vs MRL-prune vs memoization' 'head2head.sh'
    printf '\n== (a{10,20}){10,50} ==\n'
    "$HERE/head2head.sh" '(a{10,20}){10,50}' 10 10 1 99,100,101,110,150,300 4096 2>&1
    printf '\n== (a{11,22}){11,50} ==\n'
    "$HERE/head2head.sh" '(a{11,22}){11,50}' 11 11 1 120,121,122,130,200 4096 2>&1
} > "$OUT/head2head.txt"

{
    hdr 'Clamp cost on the common path, with the placebo control' 'throughput.sh'
    printf '# SPARSE clamp density (empty follow: 9 of 50 sites clamped)\n'
    for spec in '(a{10,20}){10,50} 10 10 1 300 200000' \
                '(a{2,4}){10,50} 10 2 1 200 200000' \
                '(a{1,2}){10,50} 10 1 1 60 500000'; do
        printf '\n== %s ==\n' "$spec"
        # shellcheck disable=SC2086
        "$HERE/throughput.sh" $spec 9 2>/dev/null
    done
    printf '\n# FULL clamp density (non-empty follow: 50 of 50 sites), which is\n'
    printf '# what the note recommends shipping -- R26 E5 found the sparse rows\n'
    printf '# above measuring 18%% of it. Trailing arg pair is FOLLOW_MIN SUFFIX.\n'
    for spec in '(a{2,4}){10,50}b 10 2 1 200 200000' \
                '((?:aa){2,4}){10,50}b 10 2 2 400 200000' \
                '((?:aaa){2,4}){10,50}b 10 2 3 600 200000'; do
        printf '\n== %s (dense) ==\n' "$spec"
        # shellcheck disable=SC2086
        "$HERE/throughput.sh" $spec 9 1 b 2>/dev/null
    done
} > "$OUT/throughput.txt"

{
    hdr 'Forward scan work (LANE PROXY -- not D49 RX_ERR_WORK)' 'work.sh'
    printf '# one unit = one span-loop scan-body iteration (one stride of\n'
    printf '# greedy forward walking). See work.sh header for why this is NOT\n'
    printf '# the D49 meter and what re-anchoring against it would cost.\n'
    printf '# columns: n  steps  work  verdict\n'
    for spec in '(a{10,20}){10,50}|100|a|10 10 1 50' \
                '(a{11,22}){11,50}|121|a|11 11 1 50' \
                '((?:ab){10,20}){10,50}|200|ab|10 10 2 50'; do
        PAT=${spec%%|*}; R=${spec#*|}; N=${R%%|*}; R=${R#*|}
        U=${R%%|*}; A=${R#*|}
        set -- $A
        printf '\n== %s  n=%s ==\n' "$PAT" "$N"
        printf 'baseline    '; "$HERE/work.sh" "$PAT" "$N" "$U"
        printf 'prune       '; "$HERE/work.sh" "$PAT" "$N" "$U" \
            --outer-min "$1" --inner-min "$2" --stride "$3" --replicas "$4"
        printf 'prune+scan  '; "$HERE/work.sh" "$PAT" "$N" "$U" \
            --outer-min "$1" --inner-min "$2" --stride "$3" --replicas "$4" \
            --clamp-scan
    done
} > "$OUT/work.txt"

{
    hdr 'python re on the K23 family: the same tree, no pruning rule' 'archive.sh'
    printf '# NOTE: the last row costs ~6 minutes on a quiet box, and MORE\n'
    printf '# under contention -- a 1800 s bound lost it once when this ran\n'
    printf '# alongside a differential sweep. Run archive.sh alone.\n#\n'
    timeout 5400 python3 -u -c "
import re, time
for m, M, p, P, n in [(10,12,10,50,100),(10,15,10,40,100),(10,20,10,50,100),
                      (11,22,11,50,121),(12,24,12,50,144),(13,26,13,50,169)]:
    pat = '(a{%d,%d}){%d,%d}' % (m, M, p, P)
    t = time.time(); r = re.match(pat, 'a'*n); d = time.time() - t
    print('%-22s n=%-4d %12.2f ms  %s' % (pat, n, d*1000, r.span() if r else None))
"
} > "$OUT/python_growth.txt"

if [ "$1" = "--all" ]; then
    python3 "$HERE/diff3.py" --cases "$HERE/cases_prune.tsv" \
        --out "$OUT/diff3_prune.tsv"
    python3 "$HERE/diff3.py" --cases "$HERE/cases_random.tsv" \
        --out "$OUT/diff3_random.tsv"
fi
echo "archive.sh: wrote $OUT" >&2
