#!/bin/sh
# Regenerate every archived output in ../out/ that is cheap enough to re-run
# on demand, each with a D35-style source-information header so a number in
# k23_design.md can always be traced to the build that produced it.
#
#   archive.sh          the cheap set (~3 minutes)
#   archive.sh --all    adds the two differentials (~45 minutes) -- run it
#                       in the background and poll the files, never in the
#                       foreground.
#
# The two differentials and the three-level cell are NOT in the cheap set;
# they are the slow measurements and their archived outputs are committed
# rather than regenerated on every run.
LC_ALL=C; export LC_ALL

HERE=$(cd "$(dirname "$0")" && pwd)
OUT="$HERE/../out"
ROOT=$(cd "$HERE/../../../.." && pwd)
: "${PCREC:=$ROOT/build/pcrec}"
mkdir -p "$OUT"

hdr() {
    printf '# %s\n' "$1"
    printf '# generated by probes/%s on %s\n' "$2" "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    printf '# repo commit  %s\n' "$(cd "$ROOT" && git rev-parse --short HEAD 2>/dev/null)"
    printf '# gcc          %s\n' "$(gcc --version | head -1)"
    printf '# python3      %s\n' "$(python3 --version 2>&1)"
    printf '# pcrec        %s\n' "$PCREC"
    printf '#\n'
}

{
    hdr 'K23 exemplar: exact steps vs subject length' 'steps.sh'
    printf '# columns: n  steps  verdict\n'
    "$HERE/steps.sh" '(a{10,20}){10,50}' \
        95,99,100,101,105,110,120,130,140,145,149,150,151,160,200,300
} > "$OUT/steps_curve.txt"

{
    hdr 'The closed-form law, checked against measurement' 'model.py --check'
    python3 "$HERE/model.py" --check
    printf '\n'
    hdr 'Where the law crosses the 10^6 default budget' 'model.py --grid'
    python3 "$HERE/model.py" --grid
} > "$OUT/model.txt"

{
    hdr 'Baseline vs MRL-prune vs memoization' 'head2head.sh'
    printf '\n== (a{10,20}){10,50} ==\n'
    "$HERE/head2head.sh" '(a{10,20}){10,50}' 10 10 1 99,100,101,110,150,300 4096 2>&1
    printf '\n== (a{11,22}){11,50} ==\n'
    "$HERE/head2head.sh" '(a{11,22}){11,50}' 11 11 1 120,121,122,130,200 4096 2>&1
} > "$OUT/head2head.txt"

{
    hdr 'Clamp cost on the common path, with the placebo control' 'throughput.sh'
    for spec in '(a{10,20}){10,50} 10 10 1 300 200000' \
                '(a{2,4}){10,50} 10 2 1 200 200000' \
                '(a{1,2}){10,50} 10 1 1 60 500000'; do
        printf '\n== %s ==\n' "$spec"
        # shellcheck disable=SC2086
        "$HERE/throughput.sh" $spec 9 2>/dev/null
    done
} > "$OUT/throughput.txt"

{
    hdr 'python re on the K23 family: the same tree, no pruning rule' 'archive.sh'
    printf '# NOTE: the last row costs ~6.4 minutes. That is the finding.\n#\n'
    timeout 1800 python3 -u -c "
import re, time
for m, M, p, P, n in [(10,12,10,50,100),(10,15,10,40,100),(10,20,10,50,100),
                      (11,22,11,50,121),(12,24,12,50,144),(13,26,13,50,169)]:
    pat = '(a{%d,%d}){%d,%d}' % (m, M, p, P)
    t = time.time(); r = re.match(pat, 'a'*n); d = time.time() - t
    print('%-22s n=%-4d %12.2f ms  %s' % (pat, n, d*1000, r.span() if r else None))
"
} > "$OUT/python_growth.txt"

if [ "$1" = "--all" ]; then
    python3 "$HERE/diff3.py" --cases "$HERE/cases_prune.tsv" \
        --out "$OUT/diff3_prune.tsv"
    python3 "$HERE/diff3.py" --cases "$HERE/cases_random.tsv" \
        --out "$OUT/diff3_random.tsv"
fi
echo "archive.sh: wrote $OUT" >&2
