#!/usr/bin/env python3
"""Generate a randomized case file for diff3.py over the K23 SHAPE FAMILY.

The hand-written cases_prune.tsv is chosen around known boundaries, which
means it inherits the alphabet of whoever chose them -- D27's standing
lesson. This generator instead samples `(BODY{m,M}){p,P}` from a declared
parameter box and takes, for every sampled shape, the subject lengths that
MATTER structurally: the exact minimum, its immediate neighbours, the
maximum, and points between. Seeded, so the sweep is re-runnable and the
note's population count is reproducible.

TWO AXES ADDED AFTER R26 E1/E2, and they are the point of this file's
second version. The first version drew every inner body from a SINGLE-BYTE
alphabet, so every cursor rung it produced had stride 1 -- and the clamp's
lattice bug is invisible at stride 1, where rounding onto the lattice is the
identity. 855 cells could not see it.

  * STRIDE: bodies of width 1, 2 and 3 (`a`, `[ab]`, `(?:ab)`, `(?:abc)`,
    `(?:[ab][cd])`), so the cursor's retreat lattice has a spacing the clamp
    can land off.
  * RESIDUE: subject lengths that are NOT multiples of the stride, and
    PREFIX OFFSETS that shift the lattice origin away from 0. A corpus
    without a residue axis cannot see a parity bug -- every length a
    multiple of W agrees with the unrounded clamp by accident.

This is the note's own §11.1 lesson applied to the generator that taught it.

The box is bounded by what the SLOWEST arm can stand, and that arm is python
`re` (see k23_design.md §3: python explores the same tree). The bound is on
the ITERATION product p*m, not on bytes, because the step count depends on
iterations and the byte length is that times the stride.

Usage: gen_cases.py [--seed N] [--shapes N] > cases_random.tsv
"""
import argparse
import random
import sys

# (body spelling, stride in bytes, subject unit that the body matches)
BODIES = [
    ('a', 1, 'a'),
    ('a', 1, 'a'),
    ('[ab]', 1, 'a'),
    ('[ab]', 1, 'b'),
    ('(?:ab)', 2, 'ab'),
    ('(?:ab)', 2, 'ab'),
    ('(?:abc)', 3, 'abc'),
    ('(?:[ab][cd])', 2, 'ac'),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--seed', type=int, default=23)
    ap.add_argument('--shapes', type=int, default=120)
    ap.add_argument('--max-min-iters', type=int, default=60,
                    help='cap on p*m (ITERATIONS, not bytes)')
    ap.add_argument('--max-width', type=int, default=8)
    a = ap.parse_args()
    rnd = random.Random(a.seed)

    print('# generated by gen_cases.py --seed %d --shapes %d '
          '--max-min-iters %d --max-width %d'
          % (a.seed, a.shapes, a.max_min_iters, a.max_width))
    print('# columns: pattern | outer_min | inner_min | stride | lengths | '
          'unit | prefix | suffix')
    print('# the subject is prefix + (unit repeated, truncated to len) + suffix,'
          ' so a\n# length that is not a multiple of the stride is a RESIDUE'
          ' case and a\n# non-empty prefix SHIFTS THE LATTICE ORIGIN (R26 E2).')
    seen = set()
    n_emitted = 0
    guard = 0
    while n_emitted < a.shapes and guard < 100000:
        guard += 1
        body, W, unit = rnd.choice(BODIES)
        m = rnd.randint(0, 12)
        M = m + rnd.randint(0, a.max_width)
        p = rnd.randint(1, 12)
        P = p + rnd.randint(0, 40)
        if P > 64:                      # the emitter's replica ceiling
            continue
        if p * m > a.max_min_iters or M == 0:
            continue
        pat = '(%s{%d,%d}){%d,%d}' % (body, m, M, p, P)
        if pat in seen:
            continue
        seen.add(pat)
        lo = p * m * W                  # the exact-minimum boundary, in BYTES
        hi = min(p * M * W, (a.max_min_iters + 40) * W)
        lens = {0, lo, hi}
        # neighbours of the boundary at EVERY residue mod W (this is the
        # residue axis: at W=1 it degenerates to the old +-2 window)
        for d in range(-2, 3):
            if lo + d >= 0:
                lens.add(lo + d)
        for r in range(W):
            lens.add(lo + W + r)
        lens.add((lo + hi) // 2)
        lens.add(hi + 7)
        # a prefix of length r shifts the lattice origin off 0
        pre = '' if W == 1 else 'z' * rnd.randrange(W)
        print('%s\t%d\t%d\t%d\t%s\t%s\t%s\t'
              % (pat, p, m, W, ','.join(str(x) for x in sorted(lens)),
                 unit, pre))
        n_emitted += 1
    print('# %d shapes' % n_emitted, file=sys.stderr)


if __name__ == '__main__':
    main()
