#!/usr/bin/env python3
"""Generate a randomized case file for diff3.py over the K23 SHAPE FAMILY.

The hand-written cases_prune.tsv is chosen around known boundaries, which
means it inherits the alphabet of whoever chose them -- D27's standing
lesson. This generator instead samples `(C{m,M}){p,P}` uniformly from a
declared parameter box and takes, for every sampled shape, the subject
lengths that MATTER structurally: the exact minimum p*m, its immediate
neighbours, the maximum p*M, and a few in between. Seeded, so the sweep is
re-runnable and the note's population count is reproducible.

The box is bounded by what the SLOWEST arm can stand, and that arm is python
`re` (see k23_design.md section 3.3: python explores the same tree and is
~1.2x slower per node than pcrec). p*m <= 60 and M-m <= 8 keep every cell
under a second.

Usage: gen_cases.py [--seed N] [--shapes N] > cases_random.tsv
"""
import argparse
import random
import sys


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--seed', type=int, default=23)
    ap.add_argument('--shapes', type=int, default=120)
    ap.add_argument('--max-min-total', type=int, default=60)
    ap.add_argument('--max-width', type=int, default=8)
    a = ap.parse_args()
    rnd = random.Random(a.seed)

    print('# generated by gen_cases.py --seed %d --shapes %d '
          '--max-min-total %d --max-width %d'
          % (a.seed, a.shapes, a.max_min_total, a.max_width))
    print('# columns: pattern | outer_min | inner_min | stride | lengths | '
          'char | prefix | suffix')
    seen = set()
    n_emitted = 0
    while n_emitted < a.shapes:
        m = rnd.randint(0, 12)
        M = m + rnd.randint(0, a.max_width)
        p = rnd.randint(1, 12)
        P = p + rnd.randint(0, 40)
        if P > 64:                      # the emitter's replica ceiling
            continue
        if p * m > a.max_min_total:
            continue
        if M == 0:                      # `a{0,0}` is a degenerate body
            continue
        body = rnd.choice(['a', '[ab]', 'a'])
        pat = '(%s{%d,%d}){%d,%d}' % (body, m, M, p, P)
        if pat in seen:
            continue
        seen.add(pat)
        lo = p * m
        hi = min(p * M, a.max_min_total + 40)
        lens = sorted({0, max(0, lo - 2), max(0, lo - 1), lo, lo + 1, lo + 2,
                       (lo + hi) // 2, hi, hi + 1, hi + 7})
        print('%s\t%d\t%d\t1\t%s\ta\t\t'
              % (pat, p, m, ','.join(str(x) for x in lens)))
        n_emitted += 1
    print('# %d shapes' % n_emitted, file=sys.stderr)


if __name__ == '__main__':
    main()
