#!/usr/bin/env python3
"""Applies the S1 census PROBE to a scratch source tree (argv[1]): one
`S1\t...` stderr line per compile, gated on $S1PROBE, at the REQ_WHY stamp
site of src/gen/emit_dfa.c. SCRATCH ONLY: never applied to a tracked tree.
Usage: git archive BASE | tar -x -C $SCR/probe && probe_patch.py $SCR/probe
       && make -C $SCR/probe CC=gcc-16 build/pcrec"""
import sys
p = sys.argv[1] + "/src/gen/emit_dfa.c"
s = open(p).read()
anchor = '    ReqAdmit admit = req_admit(cx);\n    if (admit == REQ_ADMIT_EMITTED) need_string_h = true;\n'
assert s.count(anchor) == 1, "anchor moved: re-derive the probe site"
BLOCK = '\n    if (getenv("S1PROBE")) {\n        const ReqRun *rr = &cx->job->req_run;\n        char runhex[64] = "-"; int L = rr->len;\n        if (L >= 2) { for (int i = 0; i < L; i++) sprintf(runhex + 2*i, "%02x", rr->bytes[i]); }\n        const char *pfn = "-"; int nsel = 0, nwalk = 0, pin = -1, implies = 0, scank = -1, pfbyte = -1;\n        char walk[128] = ""; char sel[64] = "";\n        bool dscan = pcrec_artifact_has_dfa_scan(cx);\n        if (dscan && cx->job->engine == PCREC_ENG_UNANCH) {\n            UnanchStart us; unanch_start(cx, &us);\n            if (!us.empty) {\n                const DfaPf *pf = dfa_pf_of(cx, &us); pfn = pf->c.name;\n                pfbyte = us.cand.use_memchr ? us.cand.byte : -1;\n                nwalk = us.ofsk.nwalk; nsel = us.ofsk.nsel;\n                for (int j = 0; j < nwalk && j < 20; j++) {\n                    char t[8]; if (us.ofsk.k[j].count == 1) sprintf(t, "%02x.", us.ofsk.k[j].byte); else sprintf(t, "*%d.", us.ofsk.k[j].count);\n                    strcat(walk, t);\n                }\n                for (int i = 0; i < nsel; i++) { char t[8]; sprintf(t, "%d%s,", us.ofsk.k[us.ofsk.sel[i]].k, i == us.ofsk.scan ? "*" : ""); strcat(sel, t); }\n                if (nsel) scank = us.ofsk.k[us.ofsk.sel[us.ofsk.scan]].k;\n                if (L >= 2) {\n                    for (int o = 0; o + L <= nwalk && pin < 0; o++) {\n                        int ok = 1;\n                        for (int i = 0; i < L && ok; i++) ok = us.ofsk.k[o+i].count == 1 && us.ofsk.k[o+i].byte == rr->bytes[i];\n                        if (ok) pin = o;\n                    }\n                    if (pin >= 0 && nsel > 0 && strcmp(pfn, "offset-set") == 0 ? 1 : (pin >= 0 && nsel > 0 && strcmp(pfn, "offset-set-bounded") == 0)) {\n                        int all = 1;\n                        for (int i = 0; i < L && all; i++) {\n                            int f = 0;\n                            for (int t = 0; t < nsel; t++) if (us.ofsk.k[us.ofsk.sel[t]].k == pin + i && us.ofsk.k[us.ofsk.sel[t]].count == 1) f = 1;\n                            all = f;\n                        }\n                        implies = all;\n                    }\n                }\n            }\n        }\n        fprintf(stderr, "S1\\t%s\\tvm=%d\\teng=%d\\tdscan=%d\\twhy=%s\\trb=%d\\trun=%s\\tidx=%d\\tpf=%s\\tpfbyte=%d\\tnwalk=%d\\twalk=%s\\tsel=%s\\tscank=%d\\tpin=%d\\timplies=%d\\n",\n                getenv("S1PROBE"), cx->job->fit.chosen == ENGM_VM, (int)cx->job->engine, dscan, req_why_name(admit), cx->job->req_byte, runhex, rr->idx,\n                pfn, pfbyte, nwalk, walk, sel, scank, pin, implies);\n    }\n'
open(p, "w").write(s.replace(anchor, anchor + BLOCK, 1))
