#!/usr/bin/env bash
# time_twins.sh -- form0's owed TIMING run for families B, C (small), D of
# docs/dev/form_char_step0.md (family A is closed by the compiler-equivalence
# check, §2 of that note -- no stopwatch needed there).
#
# Protocol, copied from studies/scan_edge_ladder/run_ladder.sh's shape and
# docs/dev/lanes/isl1_report.md §12 (the source §1 of the note cites
# verbatim): <prefix>_search in a find-all loop (bench_twin.c), N=11 rounds,
# arms INTERLEAVED round by round (never all-A-then-all-B), /proc/loadavg's
# 1-minute figure gating at < 0.5 -- REFUSE and wait, never caveat -- median
# ns/call and ns/byte reported with the per-round range, and every round's
# answer (hit count + checksum) is compared across arms, not sampled.
#
# Binaries and subjects are built by the caller (see README.md / this
# study's Makefile `make time`) into .tbin/ and subjects/ -- both
# gitignored, regenerated byte-for-byte from timing_base/+timing_twins/
# (themselves regenerated from build/pcrec, same discipline as base/twins).
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="$HERE/.tbin"
SUBJ="$HERE/subjects"
ROUNDS="${ROUNDS:-11}"
SWEEPS="${SWEEPS:-20}"
LOADMAX="${LOADMAX:-0.5}"
QUIETWAIT="${QUIETWAIT:-60}"
OUT="${OUT:-$HERE/results/timing_raw.tsv}"

# families: name  subject  arm-list (base first == reference for the checksum compare)
declare -A FAM_SUBJ=(
  [B_general]="$SUBJ/B_text.bin"
  [B_sparse]="$SUBJ/B_text.bin"
  [C_small]="$SUBJ/C_small.bin"
  [D_n16]="$SUBJ/D_n16.bin"
)
declare -A FAM_ARMS=(
  [B_general]="base table rangecmp"
  [B_sparse]="base table rangecmp"
  [C_small]="base range fold"
  [D_n16]="base table atom"
)

loadok() { awk -v m="$LOADMAX" '{exit !($1 < m)}' /proc/loadavg; }

wait_for_quiet() {
  local waited=0
  while ! loadok; do
    local l1
    l1="$(cut -d' ' -f1 /proc/loadavg)"
    echo "REFUSED: load1 $l1 >= $LOADMAX -- waiting (${waited}s so far, re-check every ${QUIETWAIT}s)" >&2
    sleep "$QUIETWAIT"
    waited=$((waited + QUIETWAIT))
  done
}

mkdir -p "$(dirname "$OUT")"
echo -e "family\tarm\tround\tload1\tns_per_call\tns_per_byte\thits\tcalls\tchecksum" > "$OUT"

for fam in B_general B_sparse C_small D_n16; do
    subj="${FAM_SUBJ[$fam]}"
    arms="${FAM_ARMS[$fam]}"
    echo "=== $fam  subject=$subj  arms=[$arms]  rounds=$ROUNDS sweeps=$SWEEPS ===" >&2
    for r in $(seq 1 "$ROUNDS"); do
        wait_for_quiet
        l1="$(cut -d' ' -f1 /proc/loadavg)"
        base_checksum=""
        for arm in $arms; do   # arms INTERLEAVED inside the round, never all-A-then-all-B
            bin="$BIN/${fam}_${arm}"
            [ -x "$bin" ] || { echo "MISSING BINARY: $bin" >&2; continue; }
            read -r ns_call ns_byte hits calls checksum < <("$bin" "$subj" "$SWEEPS")
            if [ "$arm" = base ]; then
                base_checksum="$hits:$checksum"
            elif [ "$hits:$checksum" != "$base_checksum" ]; then
                echo "MISMATCH round $r fam $fam arm $arm: $hits:$checksum != base $base_checksum" >&2
            fi
            printf "%s\t%s\t%d\t%s\t%s\t%s\t%s\t%s\t%s\n" \
                "$fam" "$arm" "$r" "$l1" "$ns_call" "$ns_byte" "$hits" "$calls" "$checksum" >> "$OUT"
        done
    done
done

echo "time_twins.sh: done -- raw rows in $OUT" >&2
