#!/usr/bin/env bash
# tests/recursion/run_specimen_identity.sh — [DD-14.G]'s BAR, as a check.
#
# ON DEMAND, not part of `make test`: it regenerates 85 subjects and three 1 MB
# throughput subjects, builds seven matchers and times three of them five times
# each. That is a minute of work to defend one claim, and the claim is about a
# SPECIMEN rather than about the compiler's whole population — `make test`'s job
# is the population.
#
# =========================================================================
# THE CLAIM
# =========================================================================
# `docs/design/subroutines_measurements/email_specimen/README.md` measured, on
# wave B+C, that factoring the widely copied RFC 5322 email pattern with
# subroutine calls was STRICTLY WORSE than the hand-inlined original on every
# axis except readability:
#
#   - the VM was forced (the `{0}` definitions' named groups are CAPTURES),
#   - so there was no prefilter — ~23x on a megabyte with no `@` in it,
#   - so there were no rungs — a PCREC_ERR_STEPS give-up after ~6 s on a
#     megabyte of `a`, where the DFA answers in 4 ms,
#   - and every `(?&x)` iteration cost a resume frame that SURVIVED its return,
#     so five deep-repetition subjects gave up with PCREC_ERR_FRAMES.
#
# ONE CAUSE: the callee was a CALL. Wave G's two cures are §6.3's SPLICE (for an
# acyclic callee) and the DEAD-CAPTURE ELISION (a group no emitted code can
# write does not force the capture-recording engine). The bar this file checks:
#
#   **the factored pattern's artifact is the same artifact as the hand-inlined
#   original's, modulo the pattern-text stamp and the capture declaration PCRE2
#   requires to differ — and every subject agrees, on every spelling.**
#
# =========================================================================
# WHAT "MODULO" IS ALLOWED TO COVER, AND WHY IT IS ENUMERATED
# =========================================================================
# A gate that FILTERS its way to identity is the check-design failure this
# project has recorded twice, so the exclusions are not a regex over "lines that
# look like noise". They are four NAMED facts, each with a reason a reader can
# check, and the check asserts that NOTHING ELSE differs:
#
#   1. THE PATTERN TEXT. `.pattern`, `.pattern_len`, the `Generated by pcrec`
#      header and the file-map echo. The two patterns ARE different text; the
#      bar says so in its own wording ("modulo the pattern-text stamp").
#   2. THE CAPTURE DECLARATION. `RX_NCAPS`, `rx_info.ngroups`/`.nnames`/
#      `.groups`, the `rx_group_names[]` table and the permanently-unset fill
#      loop. MEASURED on libpcre2 10.46: `(?(DEFINE)(?<g>a))(?&g)` has
#      CAPTURECOUNT 1 and reports g1 UNSET after a match, and
#      `(?(DEFINE)(?<g>a))(x)(?&g)` reports g1 UNSET / g2 SET. The factored
#      pattern NAMES four groups and PCRE2 counts them, so an artifact that
#      declared none would be diverging from the oracle to win a diff. This is
#      the residue the bar cannot remove without lying.
#   3. `RX_ALTCLS_FACTORED`. A count of how many alternation runs
#      `src/opt/altcls.c` factored. That pass runs BEFORE the splice, so it
#      cannot factor across a call boundary and its count is a property of the
#      TEXT. It changes no answer, and the minimised DFAs come out identical
#      anyway — which this file proves by comparing everything else.
#   4. Nothing. There is no fourth.
#
# =========================================================================
# THE FOUR SPELLINGS
# =========================================================================
#   orig.rx             the hand-inlined original — the REFERENCE
#   factored.rx         `(?:(?<name>...)){0}` definitions + `(?&name)` calls
#   factored_x.rx       the same under `(?x)`
#   factored_define.rx  the same with `(?(DEFINE)...)` definitions
#
# The last one is why the `(?(DEFINE)` spelling is checked at all rather than
# assumed: `mod_recursion.c` lowers a DEFINE to an `A_REP{0,0}`, so it SHOULD be
# the same tree — and "should be" is the kind of claim that is worth one line of
# assertion.
#
# Usage: bash tests/recursion/run_specimen_identity.sh
# Env: PCREC, CC, GENCFLAGS, KEEP=1, SKIP_THROUGHPUT=1

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
PCREC="${PCREC:-$ROOT_DIR/build/pcrec}"
CC="${CC:-gcc}"
KEEP="${KEEP:-0}"
GENCFLAGS="${GENCFLAGS:--O2 -std=gnu11}"
SPEC="$ROOT_DIR/docs/design/subroutines_measurements/email_specimen"
PROBES="$ROOT_DIR/docs/design/subroutines_measurements/probes"
FEATS="all"

WORKDIR="$(mktemp -d)"
cleanup() {
    if [ "$KEEP" = "1" ]; then echo "specimen: KEEP=1, temp dir: $WORKDIR" >&2
    else rm -rf "$WORKDIR"; fi
}
trap cleanup EXIT

pass=0; fail=0
ok()  { echo "PASS: $1"; pass=$((pass + 1)); }
bad() { echo "FAIL: $1" >&2; fail=$((fail + 1)); }
finish() { echo; echo "checks passed: $pass"; echo "checks failed: $fail"; \
           [ "$fail" -eq 0 ] || exit 1; exit 0; }
die()    { bad "$1"; finish; }

[ -x "$PCREC" ] || die "compiler $PCREC is missing or not executable — run \`make\` first"
for f in orig.rx factored.rx factored_x.rx factored_define.rx; do
    [ -f "$SPEC/$f" ] || die "the specimen's $f is missing from $SPEC"
done

SPELLINGS="orig factored factored_x factored_define"

# =========================================================================
# §1 THE ARTIFACTS, AND WHAT MAY DIFFER
# =========================================================================
# THE STRIP IS ASSERTED, NEVER TRUSTED — `run_recursion_identity.sh`'s own rule.
# Each excluded family has a COUNT this file states, and a family that stopped
# matching (leaving a real difference in) or started over-matching (hiding one)
# is a named failure rather than a quieter comparison.
strip_named() {
    # 1: the pattern text, four sites.  2: the capture declaration.
    # 3: RX_ALTCLS_FACTORED.  Everything else survives.
    #
    # THE TWO BLOCKS ARE DELETED AS RANGES, not line by line, and that is the
    # safer half of this filter rather than the looser one. The
    # permanently-unset fill ends with a bare `        }` and the name table
    # with a bare `};`, and BOTH of those match other lines in a 700-line file;
    # a `grep -v` on them would silently remove code this bar exists to
    # compare. Each range is anchored on its block's own first line, which is
    # unique, and `sed` deletes from there to the block's end exactly once.
    sed -e '/^    if (capture_spans)$/,/^        }$/d' \
        -e '/^static const rx_group_entry rx_group_names\[\] = {$/,/^};$/d' \
    | grep -v -e '^/\* Generated by pcrec\. Pattern:' \
              -e '^ \*     ' \
              -e '^    \.pattern = ' \
              -e '^    \.pattern_len = ' \
              -e '^#define RX_NCAPS ' \
              -e '^#define RX_ALTCLS_FACTORED ' \
              -e '^    \.ngroups = ' \
              -e '^    \.nnames = ' \
              -e '^    \.groups = '
}

for sp in $SPELLINGS; do
    # THE SAME OUTPUT BASENAME FOR EVERY SPELLING, in its own directory: pcrec
    # derives the paired header's name from the output path and emits an
    # `#include "<base>.h"` line, so four different basenames would put four
    # different includes into an otherwise identical artifact and the bar would
    # fail on the file NAME rather than on the code.
    mkdir -p "$WORKDIR/$sp"
    if ! "$PCREC" --features "$FEATS" -p rx -o "$WORKDIR/$sp/rx.c" \
            -- "$(cat "$SPEC/$sp.rx")" 2>"$WORKDIR/$sp.err"; then
        die "the specimen spelling '$sp' does not compile: $(head -2 "$WORKDIR/$sp.err")"
    fi
    strip_named < "$WORKDIR/$sp/rx.c" > "$WORKDIR/$sp.stripped"
done

# EVERY SPELLING MUST BE THE DFA ENGINE WITH A PREFILTER, stated separately from
# the byte comparison because "identical" is also what two identically-WRONG
# artifacts are. `orig.rx` has been the DFA since before this module existed, so
# this line is a claim about the other three.
for sp in $SPELLINGS; do
    eng="$(grep -m1 '^    \.engine = ' "$WORKDIR/$sp/rx.c")"
    case "$eng" in
        *PCREC_ENGINE_DFA*) ;;
        *) bad "[engine] the specimen spelling '$sp' compiled to $eng, not the DFA engine — wave G's whole claim for this specimen is that it reaches the same engine the hand-inlined original does" ;;
    esac
done
if grep -q '^        // Prefilter: nothing found yet' "$WORKDIR/orig/rx.c"; then
    ok "[engine] all four spellings compile to the DFA engine, and the reference carries its byte-class skip prefilter"
else
    bad "[engine] the REFERENCE artifact orig.c carries no prefilter, so this file is comparing against the wrong baseline"
fi

for sp in factored factored_x factored_define; do
    if diff -q "$WORKDIR/orig.stripped" "$WORKDIR/$sp.stripped" >/dev/null; then
        ok "[identity] '$sp' emits the SAME artifact as the hand-inlined 'orig', past the pattern text, the capture declaration and RX_ALTCLS_FACTORED — every byte of the DFA tables, the prefilter and the search loop identical"
    else
        n=$(diff "$WORKDIR/orig.stripped" "$WORKDIR/$sp.stripped" | grep -c '^[<>]')
        bad "[identity] '$sp' differs from 'orig' in $n lines OUTSIDE the three named exclusions:"
        diff "$WORKDIR/orig.stripped" "$WORKDIR/$sp.stripped" | head -12 >&2
    fi
done

# =========================================================================
# §1b EXACT BYTE-IDENTITY ON THE `--no-captures` AXIS (manager ruling,
#     2026-08-24)
# =========================================================================
# THE RESIDUE §1 ALLOWS IS THE CAPTURE DECLARATION, AND `--no-captures` REMOVES
# THE REASON FOR IT — almost. Under the flag neither artifact promises a group,
# so `RX_NCAPS` is 1 on both, there is no unset fill and `rx_info.ngroups` is 0.
# What SURVIVES is the NAME TABLE: `cx->n_named_groups` is a LEXICAL fact
# recorded regardless of `want_caps` (src/parse/mod_named_groups.c says so at
# the site), so a `--no-captures` artifact still ships `rx_group_names[]` with
# each entry's slot set to -1, and libpcre2 still reports the four names too.
#
# So this section asserts the STRONGEST form the two patterns permit: identical
# past the PATTERN TEXT, the NAME TABLE and `RX_ALTCLS_FACTORED` — no
# `RX_NCAPS`, no `.ngroups`, no unset fill, because on this axis those lines are
# equal rather than excused. The exclusion list is SHORTER here than in §1, and
# that is the point: an exclusion that is not needed is not taken.
strip_nocaps() {
    sed -e '/^static const rx_group_entry rx_group_names\[\] = {$/,/^};$/d' \
    | grep -v -e '^/\* Generated by pcrec\. Pattern:' \
              -e '^ \*     ' \
              -e '^    \.pattern = ' \
              -e '^    \.pattern_len = ' \
              -e '^#define RX_ALTCLS_FACTORED ' \
              -e '^    \.nnames = ' \
              -e '^    \.groups = '
}

for sp in $SPELLINGS; do
    mkdir -p "$WORKDIR/nc_$sp"
    if ! "$PCREC" --features "$FEATS" --no-captures -p rx \
            -o "$WORKDIR/nc_$sp/rx.c" -- "$(cat "$SPEC/$sp.rx")" \
            2>"$WORKDIR/nc_$sp.err"; then
        die "'$sp' does not compile under --no-captures: $(head -2 "$WORKDIR/nc_$sp.err")"
    fi
    strip_nocaps < "$WORKDIR/nc_$sp/rx.c" > "$WORKDIR/nc_$sp.stripped"
done

# THE CAPTURE DECLARATION IS GONE ON THIS AXIS, ASSERTED RATHER THAN ASSUMED —
# otherwise `--no-captures` could be hiding a difference by removing a line
# §1 was comparing.
for sp in $SPELLINGS; do
    n="$(grep -c '^#define RX_NCAPS 1$' "$WORKDIR/nc_$sp/rx.c")"
    [ "$n" -eq 1 ] || bad "[nocaps] '$sp' does not report RX_NCAPS 1 under --no-captures"
    if grep -q 'rx_g' "$WORKDIR/nc_$sp/rx.c"; then
        bad "[nocaps] '$sp' still carries the permanently-unset fill under --no-captures, where no group is promised at all"
    fi
done

for sp in factored factored_x factored_define; do
    if diff -q "$WORKDIR/nc_orig.stripped" "$WORKDIR/nc_$sp.stripped" >/dev/null; then
        ok "[nocaps] '$sp' emits the SAME artifact as 'orig' under --no-captures, past the pattern text, the NAME TABLE (a lexical fact the flag does not touch) and RX_ALTCLS_FACTORED — the capture declaration §1 has to excuse is EQUAL here, not excused"
    else
        n=$(diff "$WORKDIR/nc_orig.stripped" "$WORKDIR/nc_$sp.stripped" | grep -c '^[<>]')
        bad "[nocaps] '$sp' differs from 'orig' under --no-captures in $n lines OUTSIDE the three named exclusions:"
        diff "$WORKDIR/nc_orig.stripped" "$WORKDIR/nc_$sp.stripped" | head -12 >&2
    fi
done

# THE STRIP'S OWN CONTROL, in the direction that can go wrong: the exclusions
# must remove a BOUNDED amount, or a filter that grew could hide anything. The
# reference loses only the pattern text (it declares no group and factors its
# own alternations), so its own strip is the tightest measurement available.
orig_lines=$(wc -l < "$WORKDIR/orig/rx.c")
orig_kept=$(wc -l < "$WORKDIR/orig.stripped")
orig_dropped=$((orig_lines - orig_kept))
if [ "$orig_dropped" -ge 1 ] && [ "$orig_dropped" -le 40 ]; then
    ok "[strip] the named exclusions remove $orig_dropped of the reference's $orig_lines lines — bounded, so they cannot be hiding a difference in the 51 KB that remain"
else
    bad "[strip] the named exclusions removed $orig_dropped of the reference's $orig_lines lines, outside the 1..40 this file is computed against — the filter has grown and is no longer a named exclusion list"
fi

# =========================================================================
# §2 THE 85 SUBJECTS, AGREEING FOUR WAYS AND WITH THE ORACLE
# =========================================================================
python3 "$SPEC/gen_subjects.py" >/dev/null 2>&1 || die "gen_subjects.py failed"
SUBJ="$SPEC/subjects"
# `gen_subjects.py` writes its manifest INTO the subject directory, so the
# subjects are the `.bin` files and nothing else — counted that way rather than
# by subtracting one, which is how such a count silently absorbs a stray file.
NSUBJ=$(find "$SUBJ" -name '*.bin' -type f | wc -l)
[ "$NSUBJ" -eq 85 ] || die "the specimen's subject set is $NSUBJ files, not the 85 manifest.tsv describes — a shrunken population is how this section passes while measuring less"

for sp in $SPELLINGS; do
    "$PCREC" --features "$FEATS" -p rx --emit-main -o "$WORKDIR/m_$sp.c" \
        -- "$(cat "$SPEC/$sp.rx")" >/dev/null 2>&1 \
        || die "could not build a driver for '$sp'"
    # shellcheck disable=SC2086
    $CC $GENCFLAGS -o "$WORKDIR/m_$sp" "$WORKDIR/m_$sp.c" 2>"$WORKDIR/m_$sp.cerr" \
        || die "the '$sp' driver does not compile: $(head -3 "$WORKDIR/m_$sp.cerr")"
done

# THE DRIVER TAKES ITS SUBJECT ON argv, WHICH TRUNCATES AT A NUL — and four of
# the 85 subjects carry one, so bash warns and those four are shortened before
# they reach the matcher. It is reported here rather than hidden because it
# WEAKENS what §2 measures: all four spellings get the SAME truncated bytes, so
# the four-way agreement is still a real comparison, but on four cells it is a
# comparison over a shorter subject than manifest.tsv describes. The ORACLE
# section below reads the files directly and so covers the true 85; if this
# section is ever wanted at full fidelity, the fix is a stdin-reading driver
# (tests/backrefs/bref_batch.c is one), not a change to the subjects.
run_all() { # run_all <spelling> -> one line per subject
    local sp="$1"
    : > "$WORKDIR/ans.$sp"
    for f in "$SUBJ"/*.bin; do
        "$WORKDIR/m_$sp" "$(cat "$f")" 2>&1 | head -1 >> "$WORKDIR/ans.$sp"
    done
}
for sp in $SPELLINGS; do run_all "$sp"; done

agree=1
for sp in factored factored_x factored_define; do
    if ! diff -q "$WORKDIR/ans.orig" "$WORKDIR/ans.$sp" >/dev/null; then
        agree=0
        bad "[subjects] '$sp' disagrees with 'orig' on $(diff "$WORKDIR/ans.orig" "$WORKDIR/ans.$sp" | grep -c '^<') of $NSUBJ subjects"
        diff "$WORKDIR/ans.orig" "$WORKDIR/ans.$sp" | head -8 >&2
    fi
done
if grep -q 'frames\|steps\|work\|recurse\|internal' "$WORKDIR/ans.factored"; then
    agree=0
    bad "[subjects] the factored spelling still GIVES UP on some subject — wave G's claim is that a splice consumes no frame:"
    grep -n 'frames\|steps\|work\|recurse\|internal' "$WORKDIR/ans.factored" | head -6 >&2
fi
[ "$agree" -eq 1 ] && ok "[subjects] all $NSUBJ subjects agree across all four spellings, with no give-up on any of them (wave B+C measured FIVE PCREC_ERR_FRAMES give-ups on this same set)"

# THE ORACLE, and it SKIPS LOUDLY rather than silently (PC-3's pattern).
if python3 -c "import sys; sys.path.insert(0, '$PROBES'); import sr_oracle" 2>/dev/null; then
    python3 - "$SPEC" "$SUBJ" "$PROBES" > "$WORKDIR/oracle.out" 2>"$WORKDIR/oracle.err" <<'PYEOF'
import os, sys
spec, subj, probes = sys.argv[1], sys.argv[2], sys.argv[3]
sys.path.insert(0, probes)
import sr_oracle as o
pats = {}
for sp in ("orig", "factored", "factored_x", "factored_define"):
    pats[sp] = open(os.path.join(spec, sp + ".rx"), "rb").read().strip()
bad = 0
n = 0
for fn in sorted(f for f in os.listdir(subj) if f.endswith(".bin")):
    s = open(os.path.join(subj, fn), "rb").read()
    ref = o.search(pats["orig"], s)
    ref = None if ref is None else ref[0]
    for sp in ("factored", "factored_x", "factored_define"):
        got = o.search(pats[sp], s)
        got = None if got is None else got[0]
        if got != ref:
            bad += 1
            print("ORACLE-DISAGREE", fn, sp, ref, got)
    n += 1
print("cells", n * 3, "bad", bad)
PYEOF
    line="$(tail -1 "$WORKDIR/oracle.out")"
    case "$line" in
        "cells 255 bad 0")
            ok "[oracle] libpcre2 10.46 agrees that all four spellings describe ONE language: 255 cells (85 subjects x 3 factored spellings against the original), 0 disagreements — so the identity above is between artifacts for the same pattern, not two compilers agreeing about the wrong thing" ;;
        *)
            bad "[oracle] the libpcre2 self-check reported '$line' (want 'cells 255 bad 0'):"
            head -8 "$WORKDIR/oracle.out" >&2 ;;
    esac
else
    echo "SKIP: [oracle] libpcre2 is not reachable through $PROBES/sr_oracle.py — the four-way pcrec agreement above still ran, but nothing checked that the four spellings describe one language" >&2
fi

# =========================================================================
# §3 THROUGHPUT — THE THREE MEGABYTE SUBJECTS THE README MEASURED
# =========================================================================
if [ "${SKIP_THROUGHPUT:-0}" = "1" ]; then
    echo "SKIP: [throughput] SKIP_THROUGHPUT=1" >&2
    finish
fi
python3 "$SPEC/gen_throughput_subjects.py" >/dev/null 2>&1 \
    || die "gen_throughput_subjects.py failed"
TP="$SPEC/throughput"

median_ms() { # median_ms <binary> <subject-file>, 5 runs
    local bin="$1" f="$2" i t
    : > "$WORKDIR/times"
    for i in 1 2 3 4 5; do
        t=$( { TIMEFORMAT=%R; time "$bin" "$(cat "$f")" >/dev/null 2>&1; } 2>&1 )
        echo "$t" >> "$WORKDIR/times"
    done
    sort -g "$WORKDIR/times" | sed -n '3p'
}

TP_FAIL=0
for f in "$TP"/*.bin; do
    b="$(basename "$f")"
    to="$(median_ms "$WORKDIR/m_orig" "$f")"
    tf="$(median_ms "$WORKDIR/m_factored" "$f")"
    # WITHIN NOISE means "the same artifact", and the artifacts ARE the same
    # past §1's three named lines, so anything but a small ratio would mean §1
    # is comparing the wrong files. 1.5x is generous for a wall clock on a
    # shared box and still an order of magnitude below the 23x wave B+C
    # measured on the no-`@` subject.
    r="$(python3 -c "print('%.2f' % (float('$tf') / max(float('$to'), 1e-6)))")"
    echo "  throughput $b: orig ${to}s  factored ${tf}s  ratio ${r}x"
    if python3 -c "import sys; sys.exit(0 if float('$r') <= 1.5 else 1)"; then
        :
    else
        TP_FAIL=1
        bad "[throughput] $b: the factored spelling is ${r}x the original's time, past the 1.5x this file allows for wall-clock noise on identical artifacts"
    fi
done
[ "$TP_FAIL" -eq 0 ] && ok "[throughput] all three 1 MB subjects (median of 5): the factored spelling matches the hand-inlined original within noise — wave B+C measured 23x on the no-\`@\` subject and a PCREC_ERR_STEPS give-up after ~6 s on the megabyte of \`a\`"

finish
