#!/bin/sh
# memfn R4b: is tb_r4b.c's `emit` still the emitted gate, VERBATIM?
#
#     sh gates_sync.sh PCREC_BIN BENCH_ROOT OUTDIR      # from the repo root
#
# Re-emits the four cells (`--features all -p rx`, as alpha_k82.sh) and
# cls-n-uc at -fno-req-set-lead with PCREC_BIN, reading the patterns from
# BENCH_ROOT/bench (read-only); writes only under OUTDIR. Then:
#   (1) each artifact's abi is 61;
#   (2) its rx_reqrun definition, with the rx_wN helper line directly in
#       front of it when there is one, equals gates_d4d9ed90/<cell>_def.inc
#       byte for byte (extracted here by pattern, not by the line numbers
#       the .inc files were cut at);
#   (3) its pre-check lines in the entry (the set-leads memchr test, the
#       rx_reqrun call and the handoff test) equal <cell>_use.txt;
#   (4) cls-n-uc's default and -fno-req-set-lead artifacts differ by
#       exactly the three set-leads lines (K85's off arm).
# Last line: "GATES-SYNC ok" or "GATES-SYNC FAIL <n>".
set -u
PCREC=${1:?usage: gates_sync.sh PCREC_BIN BENCH_ROOT OUTDIR}
BENCH=${2:?}
O=${3:?}
G=docs/design/memfn/probes/twins/gates_d4d9ed90
[ -f "$G/us_def.inc" ] || { echo "run from the pcrec repo root" >&2; exit 2; }
mkdir -p "$O"
F=0
fail() { echo "FAIL $*"; F=$((F + 1)); }

emit() { # emit <cell> <bench pattern> [flags]: -> $O/<cell>[.nosl]/art.c
    d=$O/$1
    [ $# -gt 2 ] && d=$O/$1.nosl
    mkdir -p "$d"
    "$PCREC" --features all -p rx ${3:-} -o "$d/art.c" --pattern "$(cat "$BENCH/bench/$2")" 2>"$d/emit.err" \
        || fail "emit $1: $(head -1 "$d/emit.err")"
}
emit us capability/patterns/wild-waf-crs-942270-union-select.rx
emit up capability/patterns/wild-secrets-username-password-pair.rx
emit mi syntax/patterns/mod-i.rx
emit cn syntax/patterns/cls-n-uc.rx
emit cn syntax/patterns/cls-n-uc.rx -fno-req-set-lead

for c in us up mi cn; do
    a=$O/$c/art.c
    grep -q '^/\* Generated by pcrec .*(abi 61)' "$a" || fail "$c: not abi 61: $(head -1 "$a")"
    # (2) the definition: from the helper (two lines up, if it is one) to the
    # first closing brace after `static inline size_t rx_reqrun(`
    awk '{ l[NR] = $0 }
         /^static inline size_t rx_reqrun\(/ && !s { s = NR }
         s && !e && NR > s && /^}/ { e = NR }
         END { b = s
               if (l[s - 2] ~ /^static inline uint(16|32|64)_t rx_w[248]\(/) b = s - 2
               for (i = b; i <= e; i++) print l[i] }' "$a" > "$O/$c.def"
    cmp -s "$O/$c.def" "$G/${c}_def.inc" || { fail "$c: definition differs"; diff "$G/${c}_def.inc" "$O/$c.def" | head -20; }
    # (3) the use lines: the set-leads test (3 lines), the rx_reqrun call,
    # and the handoff test after an assignment
    awk '/^    if \(subject_length <= search_from \|\|$/ { k = 3 }
         k { print; k--; next }
         /^    .*rx_reqrun\(subject, subject_length, search_from\)/ { print; if (/handoff_position =/) h = 1; next }
         h { print; h = 0 }' "$a" > "$O/$c.use"
    cmp -s "$O/$c.use" "$G/${c}_use.txt" || { fail "$c: use lines differ"; diff "$G/${c}_use.txt" "$O/$c.use" | head -20; }
done

# (4) K85's off arm: the same artifact minus the three set-leads lines
diff "$O/cn/art.c" "$O/cn.nosl/art.c" > "$O/cn.nosl.diff"
if [ "$(grep -c '^<' "$O/cn.nosl.diff")" != 3 ] || grep -q '^>' "$O/cn.nosl.diff" \
    || ! grep -q '^< .*memchr(subject + search_from, 109' "$O/cn.nosl.diff"; then
    fail "cn: -fno-req-set-lead is not exactly the three set-leads lines"
    cat "$O/cn.nosl.diff"
fi
if [ $F = 0 ]; then echo "GATES-SYNC ok"; else echo "GATES-SYNC FAIL $F"; fi
[ $F = 0 ]
