#!/usr/bin/env python3
"""emit.py — compose one bespoke straight-line C matcher from a sectioning.

Emits, for a set and a chosen sectioning:

    static inline int <fn>(unsigned cp)
    {
        if ((unsigned)(cp - LO) > SPAN) return 0;     /* global bound */
        ... balanced binary dispatch tree over section boundaries ...
        ... at each leaf, that section's kit-member test ...
    }

The dispatch tree is a BALANCED binary search over the section boundaries,
emitted as nested `if`s — not a loop, not a table.  That is the whole point of
compiling a statically-known set: the matcher IS the set.

`cls_bsearch` is the one out-of-line helper (only emitted when some leaf
chose BSEARCH), because a binary search over a table is the one kit member
whose body is a loop.
"""

import kit

PRELUDE = r"""/* GENERATED by studies/cls_tree_study/emit.py — do not edit. */
#include <stdint.h>

static inline int cls_bsearch(const unsigned *lo, const unsigned *hi,
                              int n, unsigned x)
{
    int a = 0, b = n - 1;
    while (a <= b) {
        int m = (a + b) >> 1;
        if (x < lo[m])      b = m - 1;
        else if (x > hi[m]) a = m + 1;
        else                return 1;
    }
    return 0;
}
"""


def emit(fn, iv, secs, forms, static=True):
    """Return (c_source_text, rodata_bytes)."""
    members = []
    for (i, j), nm in zip(secs, forms):
        sec = iv[i:j + 1]
        cls = {F.name: F for F in kit.KIT}[nm]
        members.append(cls(sec))

    tabs, ro = [], 0
    for idx, f in enumerate(members):
        t = "%s_t%d" % (fn, idx)
        s = f.tables(t)
        if s:
            tabs.append(s)
        ro += f.rodata()

    lo0 = iv[secs[0][0]][0]
    hiN = iv[secs[-1][1]][1]

    body = []
    body.append("    if ((unsigned)(cp - %uu) > %uu) return 0;"
                % (lo0, hiN - lo0))

    def leaf(k, ind):
        f = members[k]
        t = "%s_t%d" % (fn, k)
        x = "(cp - %uu)" % f.base if f.base else "cp"
        if isinstance(f, kit.FormAll):
            body.append("%sreturn 1;" % ind)
            return
        body.append("%sreturn (int)%s;" % (ind, f.expr(x, t)))

    def tree(a, b, ind):
        """Sections a..b.  INVARIANT on entry: base[a] <= cp <= top[b].

        Established for the root by the global bound test, and maintained by
        both arms below — which is why a leaf needs NO bound test of its own,
        only the gap test INSIDE its span that its kit member performs."""
        if a == b:
            leaf(a, ind)
            return
        m = (a + b) // 2
        body.append("%sif (cp <= %uu) {" % (ind, members[m].top))
        tree(a, m, ind + "    ")
        body.append("%s}" % ind)
        body.append("%sif (cp < %uu) return 0;" % (ind, members[m + 1].base))
        tree(m + 1, b, ind)

    tree(0, len(members) - 1, "    ")

    sig = "static inline int %s(unsigned cp)" % fn if static \
        else "int %s(unsigned cp)" % fn
    src = "".join(tabs) + sig + "\n{\n" + "\n".join(body) + "\n}\n"
    return src, ro


def reference(fn, iv):
    """The ORACLE matcher: a plain binary search over the whole interval list.
    Deliberately the dumbest correct thing, so a disagreement is never both
    sides making the same mistake."""
    n = len(iv)
    lo = ", ".join("%uu" % l for l, _ in iv)
    hi = ", ".join("%uu" % h for _, h in iv)
    return ("static const unsigned %s_lo[%d] = { %s };\n"
            "static const unsigned %s_hi[%d] = { %s };\n"
            "static int %s(unsigned cp)\n{ return cls_bsearch(%s_lo, %s_hi, %d, cp); }\n"
            % (fn, n, lo, fn, n, hi, fn, fn, fn, n))
