/* varexp.c — [VAR] M1: THE EXPANSION GRAMMAR, parsed once, shared by both
 * consumers.
 *
 * Design: docs/design/variables_common.md §1 (the survey and the production),
 * §1.3 (the one place the two consumers differ), §1.7 (nesting) and §2.2 (the
 * UNSET/EMPTY value model the operators are defined against). Read §1.1's
 * table before touching this file: every operator here is a row in it, and
 * every row NOT here is declined there with its own reason.
 *
 * WHAT THIS FILE IS, in one sentence: a pure function from TEXT to a small
 * tree, with no subject, no automaton, no match and no environment. That is
 * `variables_common.md` §5's EXPANSION half, and the seam is what makes the
 * file testable on its own (tests/core/varexp_check.c) below any artifact.
 *
 * WHAT IT IS NOT. It does NOT evaluate. Evaluation needs the caller's
 * environment, which arrives at MATCH time, so the evaluator is EMITTED C
 * generated by walking this tree (src/gen/emit_vm.c's entry wrapper) rather
 * than a function here that nothing on the compile path could call. There is
 * deliberately no `pcrec_varexp_eval` in this tree: it would have no
 * production caller, and a second evaluator kept alive by its own unit test
 * is the parallel mechanism memory `pcrec-general-mechanisms-not-special-
 * cases` names. What IS checked below the artifact is the GRAMMAR, through
 * `pcrec_varexp_render`'s canonical text; the emitted evaluator's SEMANTICS
 * are checked by tests/vars/'s oracle (variables_common.md §3.6).
 *
 * THE PRODUCTION, from §1.3:
 *
 *     ${ [!] selector [ operator word ] }
 *
 * with five operators and no more (`variables_roadmap.md` §2.1 M1): `:-`,
 * `-`, `:+`, `+`, `:?`. The COLON is not part of the operator's identity — it
 * is the flag that folds EMPTY in with UNSET (§2.2), which is why it is a
 * `bool` here and not four more enumerators.
 *
 * IT TAKES AN `Arena *` AND NOTHING ELSE, the same shape and for the same
 * reason as `pcrec_sb_fragf` (D108's data-in / text-out rule): a refusal is
 * RETURNED in a `VarExpErr` rather than raised through `pcrec_ctx_fail`, so
 * the caller — the `vars` parse hook, which alone knows the doorway's own
 * diagnostic conventions — decides how it is reported. Allocation failure is
 * the one exception and needs no code here: `pcrec_arena_alloc` already routes
 * through the arena's own `.cx` (coding_guide.md §1.1).
 *
 * THE ONE SPELLING DECISION THIS FILE MAKES, flagged rather than buried: a
 * BACKSLASH inside an operator's WORD makes the next byte literal. Without
 * it neither `}` nor `$` is spellable in a default value, which would make
 * `${v:-a}b}` unwritable and `${v:-$}` ambiguous — a grammar with unspellable
 * values. The design notes do not rule on it (§4.1 covers a literal `$`
 * OUTSIDE `${...}`, where nothing new is needed). The alternative — no
 * escape at all, `}` simply unspellable in a word — is named here so a later
 * ruling can take it without re-deriving the question. */

#include <string.h>

#include "core/internal.h"

/* How many bytes of `text` are left at `i`. */
static size_t vx_left(size_t n, size_t i) { return i < n ? n - i : 0; }

/* Record a refusal at `at` and return NULL, the one failure shape every
 * production below uses. `msg` is a static string: every refusal this grammar
 * can raise names a rule, never a byte of the caller's pattern, so none of
 * them needs formatting or arena storage. */
static const VarExp *vx_fail(VarExpErr *err, size_t at, const char *msg)
{
    if (err) { err->at = at; err->msg = msg; }
    return NULL;
}

/* Is `c` legal as the FIRST byte of a selector? The shell's own rule, and
 * narrower than "anything up to the operator" on purpose: a name that can
 * start with a digit cannot be told apart from a capture-group selector on
 * the REPLACEMENT side, where `${1}` is ruled to be group 1 (D38), and one
 * grammar serving two consumers cannot afford that ambiguity in either. */
static bool vx_name_start(int c)
{
    return (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || c == '_';
}

/* Is `c` legal in a selector after the first byte? */
static bool vx_name_cont(int c)
{
    return vx_name_start(c) || (c >= '0' && c <= '9');
}

/* Growable `VarWord` list, arena-backed. A word's piece count is bounded only
 * by the pattern's own length, so it cannot be a fixed array; the doubling
 * shape is the tree's usual one and the arena never frees, which is correct
 * here because every piece lives for the whole compile. */
typedef struct {
    VarWord *v;
    size_t   n, cap;
} VxWords;

/* Append one piece, growing the list if it is full. */
static void vx_words_push(Arena *a, VxWords *w, VarWord piece)
{
    if (w->n == w->cap) {
        size_t ncap = w->cap ? w->cap * 2 : 4;
        VarWord *nv = pcrec_arena_alloc(a, ncap * sizeof *nv);
        if (w->n) memcpy(nv, w->v, w->n * sizeof *nv);
        w->v = nv;
        w->cap = ncap;
    }
    w->v[w->n++] = piece;
}

static const VarExp *vx_parse_at(Arena *a, const char *text, size_t n,
                                 size_t *pos, int depth, VarExpErr *err);

/* Read an operator's WORD: every byte up to the expansion's own closing `}`,
 * with `\<byte>` taken literally and a nested `${...}` taken as a piece of its
 * own. Leaves `*pos` ON the closing `}`. Literal runs are coalesced, so
 * `a\}b` is ONE piece and not three — which is what makes the emitted
 * evaluator one `memcpy` per run rather than one per byte.
 *
 * `at` is the ENCLOSING reference's own `$`, and it is a parameter rather
 * than a local because that is where an "unterminated" diagnostic must
 * point: the thing that is unterminated is the reference, not the byte the
 * scan happened to stop on, and on `${v:-${a}` the reference that is
 * unterminated is the OUTER one even though the inner one parsed cleanly. */
static bool vx_parse_word(Arena *a, const char *text, size_t n, size_t *pos,
                          size_t at, int depth, VxWords *out, VarExpErr *err)
{
    size_t i = *pos;
    /* The coalescing buffer: literal bytes are copied here as they are read,
     * because an escape means the run is not a contiguous slice of `text`. */
    size_t     cap = 16, len = 0;
    unsigned char *buf = pcrec_arena_alloc(a, cap);

    for (;;) {
        if (i >= n) { vx_fail(err, at, "unterminated ${...} variable reference"); return false; }
        unsigned char c = (unsigned char)text[i];

        if (c == '}') break;

        if (c == '\\' && vx_left(n, i) >= 2) {
            /* The next byte, whatever it is, is that byte. */
            i++;
            c = (unsigned char)text[i];
        } else if (c == '$' && vx_left(n, i) >= 2 && text[i + 1] == '{') {
            /* Flush the literal run, then recurse. */
            if (len) {
                VarWord piece = { buf, len, NULL };
                vx_words_push(a, out, piece);
                cap = 16; len = 0;
                buf = pcrec_arena_alloc(a, cap);
            }
            const VarExp *nest = vx_parse_at(a, text, n, &i, depth + 1, err);
            if (!nest) return false;
            VarWord piece = { NULL, 0, nest };
            vx_words_push(a, out, piece);
            continue;    /* vx_parse_at left `i` past the nested `}` */
        }

        if (len == cap) {
            size_t ncap = cap * 2;
            unsigned char *nb = pcrec_arena_alloc(a, ncap);
            memcpy(nb, buf, len);
            buf = nb;
            cap = ncap;
        }
        buf[len++] = c;
        i++;
    }

    if (len) {
        VarWord piece = { buf, len, NULL };
        vx_words_push(a, out, piece);
    }
    *pos = i;
    return true;
}

/* Parse ONE `${...}` expansion whose `$` sits at `text[*pos]`, leaving `*pos`
 * one past the closing `}`. `depth` is 0 for the outermost expansion and one
 * more per nesting level; PCREC_MAX_VAR_NEST_DEPTH bounds it, which bounds
 * this function's own recursion too (§1.7's "no run-time recursion in either
 * consumer" is about the EMITTED code; this recursion is the compiler's and
 * is what the row exists to bound). */
static const VarExp *vx_parse_at(Arena *a, const char *text, size_t n,
                                 size_t *pos, int depth, VarExpErr *err)
{
    size_t at = *pos;

    if (depth > PCREC_MAX_VAR_NEST_DEPTH)
        return vx_fail(err, at, "${...} nesting is deeper than the limit "
                                "(see --list-limits, PCREC_MAX_VAR_NEST_DEPTH)");

    if (vx_left(n, at) < 2 || text[at] != '$' || text[at + 1] != '{')
        return vx_fail(err, at, "internal error: not a ${...} variable reference");

    size_t i = at + 2;

    VarExp *x = pcrec_arena_alloc(a, sizeof *x);
    x->at = at;

    if (i < n && text[i] == '!') { x->explicit_var = true; i++; }

    /* ---- the selector ---------------------------------------------------- */
    size_t nstart = i;
    if (i >= n || !vx_name_start((unsigned char)text[i]))
        return vx_fail(err, i, "a ${...} variable name must start with a letter "
                               "or an underscore");
    while (i < n && vx_name_cont((unsigned char)text[i])) i++;

    size_t nlen = i - nstart;
    if (nlen > PCREC_MAX_VAR_NAME_LEN)
        return vx_fail(err, nstart, "the ${...} variable name is longer than the "
                                    "limit (see --list-limits, PCREC_MAX_VAR_NAME_LEN)");

    char *nm = pcrec_arena_alloc(a, nlen + 1);
    memcpy(nm, text + nstart, nlen);
    nm[nlen] = '\0';
    x->name = nm;

    if (i >= n) return vx_fail(err, at, "unterminated ${...} variable reference");

    /* ---- the operator, or the closing brace ------------------------------ */
    if (text[i] == '}') { *pos = i + 1; return x; }

    if (text[i] == ':') {
        x->colon = true;
        i++;
        if (i >= n) return vx_fail(err, at, "unterminated ${...} variable reference");
    }

    switch ((unsigned char)text[i]) {
    case '-': x->op = VXOP_DEFAULT; break;
    case '+': x->op = VXOP_ALT;     break;
    case '?':
        /* `:?` only. The bare `${name?word}` bash also has is NOT in this
         * grammar (variables_common.md §1.1's table lists the colon form
         * alone), and refusing it BY NAME is what stops a caller reading
         * bash's meaning into a spelling this grammar does not carry. */
        if (!x->colon)
            return vx_fail(err, i, "the ${name?word} form is not supported; "
                                   "write ${name:?word}");
        x->op = VXOP_REQUIRE;
        break;
    default:
        return vx_fail(err, i, x->colon
                       ? "expected ':-', ':+' or ':?' after ':' in a ${...} "
                         "variable reference"
                       : "expected an operator (':-' '-' ':+' '+' ':?') or '}' "
                         "in a ${...} variable reference");
    }
    i++;

    VxWords w = { NULL, 0, 0 };
    if (!vx_parse_word(a, text, n, &i, at, depth, &w, err)) return NULL;
    x->word  = w.v;
    x->nword = w.n;

    /* vx_parse_word leaves `i` on the `}` it stopped at. */
    *pos = i + 1;
    return x;
}

/* THE ENTRY POINT. Parse the `${...}` at `text[*pos]` and advance `*pos` past
 * its closing brace; on refusal return NULL with `*err` filled and `*pos`
 * untouched, so the caller's own diagnostic can cite `err->at` and the caller
 * can leave the cursor where it chooses. */
const VarExp *pcrec_varexp_parse(Arena *a, const char *text, size_t n,
                                 size_t *pos, VarExpErr *err)
{
    if (err) { err->at = *pos; err->msg = NULL; }
    size_t i = *pos;
    const VarExp *x = vx_parse_at(a, text, n, &i, 0, err);
    if (!x) return NULL;
    *pos = i;
    return x;
}

/* ---- the canonical rendering ------------------------------------------- */

/* Append one escaped word byte. The inverse of vx_parse_word's escape rule,
 * and it must stay the inverse: the render is what tests/core/varexp_check.c
 * compares against, and what `--emit-ir` prints, so a render that does not
 * re-parse to the same tree would make both of them assert a falsehood. */
static void vx_render_byte(StrBuf *b, unsigned char c)
{
    if (c == '}' || c == '\\' || c == '$') pcrec_sb_putc(b, '\\');
    pcrec_sb_putc(b, (char)c);
}

static void vx_render_into(StrBuf *b, const VarExp *x)
{
    pcrec_sb_puts(b, "${");
    if (x->explicit_var) pcrec_sb_putc(b, '!');
    pcrec_sb_puts(b, x->name);
    if (x->op != VXOP_NONE) {
        if (x->colon) pcrec_sb_putc(b, ':');
        pcrec_sb_putc(b, x->op == VXOP_DEFAULT ? '-'
                       : x->op == VXOP_ALT     ? '+' : '?');
        for (size_t k = 0; k < x->nword; k++) {
            const VarWord *w = &x->word[k];
            if (w->nest) { vx_render_into(b, w->nest); continue; }
            for (size_t j = 0; j < w->litlen; j++) vx_render_byte(b, w->lit[j]);
        }
    }
    pcrec_sb_putc(b, '}');
}

/* Render `x` back to its CANONICAL spelling — arena-owned text, the shape
 * `--emit-ir`'s listing row carries and the shape the grammar's unit check
 * asserts against. Canonical rather than verbatim: the source's own escapes
 * are re-derived from the bytes, so `${v:-\a}` and `${v:-a}` render alike
 * because they ARE alike, which is the property that makes this a check on
 * the PARSE rather than on the input text. */
const char *pcrec_varexp_render(Arena *a, const VarExp *x)
{
    StrBuf b;
    memset(&b, 0, sizeof b);
    b.cx = a->cx;
    vx_render_into(&b, x);
    const char *out = pcrec_sb_fragf(a, "%s", b.p ? b.p : "");
    pcrec_sb_free(&b);
    return out;
}
