#!/bin/sh
# scripts/embed_text.sh OUT FILE... — embeds each FILE's bytes, unmodified,
# as a C array in OUT, with a name index ([FINDINGS] B1; findings design §8.1).
#
# Writes the embedded findings store, src/core/findings_store.inc, from the
# committed src/findings/<name>.rxt (`make gen-findings`). The .inc is a
# mechanical ENCODING of committed text; it is committed too, on the
# GEN_TABLES precedent, so a source tree compiles with no build step (the
# Makefile's [FINDINGS] B1 comment says why), and tests/findings/ reads each
# name back through the library and compares it with its source byte for
# byte, which is what makes a stale copy red.
#
# THE INVOCATION IS PINNED [r2 A-8]: `LC_ALL=C od -An -v -tx1` prints the same
# hex pairs under BSD and GNU od (`-v` so a repeated line is never collapsed
# to `*`), and this script consumes only those pairs, never od's column
# spacing. POSIX sh and od only: a clone with no python still builds.
#
# A name is the file's basename without `.rxt`. Each array carries a
# terminating NUL beyond its stated length, so a reader may also treat it as
# a C string; the length is the file's own byte count.
set -eu
out=$1
shift
tmp="$out.tmp.$$"
{
    echo "/* GENERATED by scripts/embed_text.sh from src/findings/<name>.rxt (make gen-findings)."
    echo " * Never edit by hand; committed, and checked by tests/findings/ §2. */"
    i=0
    for f in "$@"; do
        echo "static const char pcrec_find_store_text_$i[] = {"
        LC_ALL=C od -An -v -tx1 "$f" | tr -s ' \t' '\n\n' | sed -n 's/^\([0-9a-f][0-9a-f]\)$/0x\1,/p'
        echo "0x00 };"
        i=$((i + 1))
    done
    echo "static const PcrecFindStoreEntry pcrec_find_store[] = {"
    i=0
    for f in "$@"; do
        n=$(basename "$f" .rxt)
        len=$(LC_ALL=C wc -c < "$f" | tr -d ' ')
        echo "    { \"$n\", pcrec_find_store_text_$i, $len },"
        i=$((i + 1))
    done
    echo "};"
} > "$tmp"
mv "$tmp" "$out"
