/* scripts/findgen.c — THE STORE'S BUILD-TIME PRE-PARSE: `findgen OUT
 * FILE...` parses each shipped bundle with the one `.rxt` reader, in the
 * no-filesystem buffer mode the store is read in, and writes every data
 * block it finds as a C table (`src/core/findings_table.inc`, committed,
 * regenerated by `make gen-findings`) that
 * `src/core/findings.c` compiles in ([FINDINGS] B1; findings design §13 B1
 * acceptance (3)).
 *
 * WHY IT EXISTS. B1 measured parsing `default.rxt` on every compile at ~47 us,
 * about 20% of a minimal compile — above noise — and the design's own rule
 * for that case is a table generated FROM THE SAME TEXT at build time with
 * an agreement check, never a second source. The text stays the source of
 * truth: this program reads nothing else, and tests/findings/ re-parses the
 * embedded text through the library and checks it agrees with the table.
 *
 * It links a STAGE-0 library (findings.o built with PCREC_FIND_STAGE0, whose
 * own table is empty) because the real findings.o includes this program's
 * output; it only parses, so it never reads a table. Not part of libpcrec.
 *
 * Each FILE must define exactly one bundle, named for the file's basename:
 * the store looks a bundle up by that name. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "core/internal.h"

/* Refuses a string that would need escaping inside a C literal. Every
 * string written here is a name the reader already validated (a bundle
 * name, a kind, a query, an encoding list, a derivation), so this never
 * fires on a file that parsed; it is the generator's own guard. */
static void check_plain(const char *s, const char *what)
{
    for (const char *c = s; *c; c++)
        if (*c == '"' || *c == '\\' || (unsigned char)*c < 0x20 ||
            (unsigned char)*c >= 0x7f) {
            fprintf(stderr, "findgen: %s '%s' holds a byte a C literal would "
                    "have to escape\n", what, s);
            exit(1);
        }
}

/* Reads `path` whole into a malloc'd buffer. */
static char *slurp(const char *path, size_t *len)
{
    FILE *f = fopen(path, "rb");
    char *buf;
    long sz;
    if (!f || fseek(f, 0, SEEK_END) != 0 || (sz = ftell(f)) < 0) {
        fprintf(stderr, "findgen: cannot read %s\n", path);
        exit(1);
    }
    rewind(f);
    buf = malloc((size_t)sz + 1);
    if (!buf || fread(buf, 1, (size_t)sz, f) != (size_t)sz) {
        fprintf(stderr, "findgen: cannot read %s\n", path);
        exit(1);
    }
    fclose(f);
    *len = (size_t)sz;
    return buf;
}

int main(int argc, char **argv)
{
    FILE *out;
    size_t nb = 0;
    if (argc < 2) {
        fprintf(stderr, "usage: findgen OUT FILE...\n");
        return 2;
    }
    out = fopen(argv[1], "w");
    if (!out) { fprintf(stderr, "findgen: cannot write %s\n", argv[1]); return 1; }
    fprintf(out, "/* GENERATED by scripts/findgen.c from src/findings/<name>.rxt:\n"
                 " * the store PRE-PARSED by the one .rxt reader (make gen-findings).\n"
                 " * Never edit by hand; committed, checked by tests/findings/ §3. */\n");
    for (int a = 2; a < argc; a++) {
        const char *path = argv[a], *base = strrchr(path, '/');
        char name[256];
        size_t len, nlen, nbundles = 0;
        char *text = slurp(path, &len);
        pcrec_error err;
        RxtSource *src;
        base = base ? base + 1 : path;
        nlen = strlen(base);
        if (nlen < 5 || nlen - 4 >= sizeof name || strcmp(base + nlen - 4, ".rxt")) {
            fprintf(stderr, "findgen: %s is not a <name>.rxt file\n", path);
            return 1;
        }
        memcpy(name, base, nlen - 4);
        name[nlen - 4] = 0;
        src = pcrec_rxt_source_parse_buf(path, text, len, &err);
        if (!src) { fprintf(stderr, "findgen: %s\n", err.msg); return 1; }
        for (size_t r = 0; r < src->nrows; r++)
            if (src->rows[r].kind == RXT_DECL_ANALYSIS) {
                nbundles++;
                if (strcmp(src->rows[r].name, name) != 0) {
                    fprintf(stderr, "findgen: %s defines analysis '%s', not "
                            "'%s'\n", path, src->rows[r].name, name);
                    return 1;
                }
            }
        if (nbundles != 1) {
            fprintf(stderr, "findgen: %s defines %zu analyses; a store file "
                    "defines exactly one\n", path, nbundles);
            return 1;
        }
        for (size_t i = 0; i < src->nfblocks; i++, nb++) {
            const RxtFindBlock *fb = &src->fblocks[i];
            fprintf(out, "static const PcrecFindServe pcrec_find_tbl_serves_%zu[] = {\n", nb);
            for (size_t j = 0; j < fb->nserves; j++) {
                check_plain(fb->serves[j].query, "query");
                check_plain(fb->serves[j].encs, "encoding list");
                check_plain(fb->serves[j].via, "derivation");
                fprintf(out, "    { \"%s\", \"%s\", \"%s\" },\n",
                        fb->serves[j].query, fb->serves[j].encs,
                        fb->serves[j].via);
            }
            fprintf(out, "};\nstatic const unsigned long long pcrec_find_tbl_counts_%zu[256] = {\n", nb);
            for (int b = 0; b < 256; b++)
                fprintf(out, "%lluull,%s", fb->counts[b], (b & 7) == 7 ? "\n" : " ");
            fprintf(out, "};\n");
        }
        pcrec_rxt_source_free(src);
        free(text);
    }
    /* The index, in a second pass so every block's arrays precede it. */
    fprintf(out, "static const PcrecFindTblBlock pcrec_find_tbl[] = {\n");
    nb = 0;
    for (int a = 2; a < argc; a++) {
        size_t len;
        char *text = slurp(argv[a], &len);
        pcrec_error err;
        RxtSource *src = pcrec_rxt_source_parse_buf(argv[a], text, len, &err);
        for (size_t i = 0; i < src->nfblocks; i++, nb++) {
            const RxtFindBlock *fb = &src->fblocks[i];
            check_plain(fb->bundle, "bundle name");
            check_plain(fb->kind, "kind");
            fprintf(out, "    { \"%s\", \"%s\", %zu, pcrec_find_tbl_serves_%zu, %zu, "
                    "pcrec_find_tbl_counts_%zu },\n", fb->bundle, fb->kind,
                    fb->line, nb, fb->nserves, nb);
        }
        pcrec_rxt_source_free(src);
        free(text);
    }
    fprintf(out, "};\n");
    if (fclose(out) != 0) { fprintf(stderr, "findgen: write failed\n"); return 1; }
    return 0;
}
