#!/usr/bin/env python3
"""scripts/spec_toc.py -- rebuild the table of contents of a docs/spec/*.md.

A spec document numbers its sections (docs/spec/CLAUDE.md, "Numbering"): a
heading is `## 3. Title`, `### 3.1 Title`, `#### 3.1.3 Title`, and each one
is preceded by a line `<a id="s3-1-3"></a>` (the number with dots turned
into dashes, prefixed `s`). This script lists those headings, number plus
link, between two marker comments near the top of the document:

    <!-- spec-toc:begin -->
    ... generated; never edited by hand ...
    <!-- spec-toc:end -->

  spec_toc.py FILE...            rewrite each FILE's block in place
  spec_toc.py --check FILE...    change nothing; exit 1 (and show the diff)
                                 if a block is stale or an anchor is missing
  spec_toc.py --init FILE...     as the first form; where the markers are
                                 absent, put them after the document's `# `
                                 title line

Only headings that START with a number are listed (the `# ` title and any
unnumbered heading are not). The title text is the heading's own, minus its
number. A numbered heading with no `<a id="s...">` line anywhere in the file,
or two headings with one number, is an error: a TOC link must resolve and a
number must name one section. Retired sections stay listed (their heading
reads "retired").

Python 3 standard library only.
"""
import difflib
import re
import sys

BEGIN = "<!-- spec-toc:begin -->"
END = "<!-- spec-toc:end -->"
NOTE = ("<!-- generated by scripts/spec_toc.py from the numbered headings; "
        "run it after adding or retiring a section -->")
HEAD = re.compile(r"^(#{2,6})\s+(\d+(?:\.\d+)*[a-z]?)\.?\s+(.*?)\s*$")
ANCHOR = re.compile(r'<a id="(s[0-9a-z-]+)"></a>')


def anchor_of(num):
    return "s" + num.replace(".", "-")


def headings(lines):
    """-> [(level, number, title)] for numbered headings outside code fences."""
    out, fence = [], False
    for line in lines:
        if line.lstrip().startswith("```"):
            fence = not fence
            continue
        if fence:
            continue
        m = HEAD.match(line)
        if m:
            out.append((len(m.group(1)), m.group(2), m.group(3)))
    return out


def build(path, text):
    """-> (new_text, errors)."""
    lines = text.split("\n")
    errors = []
    heads = headings(lines)
    anchors = set(ANCHOR.findall(text))
    seen = {}
    body = [BEGIN, NOTE, ""]
    for level, num, title in heads:
        if num in seen:
            errors.append("%s: section number %s is used twice (%r and %r)"
                          % (path, num, seen[num], title))
        seen[num] = title
        if anchor_of(num) not in anchors:
            errors.append('%s: heading %s has no <a id="%s"></a> line'
                          % (path, num, anchor_of(num)))
        body.append("%s- [§%s](#%s) %s" % ("  " * (level - 2), num,
                                            anchor_of(num), title))
    body.append(END)
    if not heads:
        errors.append("%s: no numbered headings" % path)
    try:
        b = lines.index(BEGIN)
        e = lines.index(END)
    except ValueError:
        return None, errors + ["%s: no %s ... %s block (use --init)" % (path, BEGIN, END)]
    if e < b:
        return None, errors + ["%s: the end marker precedes the begin marker" % path]
    new = lines[:b] + body + lines[e + 1:]
    return "\n".join(new), errors


def init(text):
    """Insert an empty marker block after the `# ` title line."""
    lines = text.split("\n")
    if BEGIN in lines:
        return text
    for i, line in enumerate(lines):
        if line.startswith("# "):
            return "\n".join(lines[:i + 1] + ["", BEGIN, END] + lines[i + 1:])
    sys.exit("spec_toc: FATAL: no '# ' title line to anchor the block after")


def main(argv):
    args = argv[1:]
    check = "--check" in args
    do_init = "--init" in args
    files = [a for a in args if not a.startswith("--")]
    if not files:
        sys.exit(__doc__)
    bad = 0
    for path in files:
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        if do_init:
            text = init(text)
        new, errors = build(path, text)
        for e in errors:
            print("spec_toc: " + e, file=sys.stderr)
        if errors:
            bad += 1
            continue
        if check:
            if new != text:
                bad += 1
                print("spec_toc: %s: the table of contents is stale "
                      "(run scripts/spec_toc.py %s)" % (path, path), file=sys.stderr)
                diff = difflib.unified_diff(text.split("\n"), new.split("\n"),
                                            "current", "regenerated", lineterm="", n=0)
                for k, d in enumerate(diff):
                    if k >= 20:
                        print("  ...", file=sys.stderr)
                        break
                    print("  " + d, file=sys.stderr)
        elif new != text or do_init:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new)
            print("spec_toc: %s: wrote %d entries" % (
                path, len(re.findall(r"(?m)^ *- \[§", new))))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
