"""C17's dynamic half: the corpus-pass census ([MEMFN], integration.md
§R4.3.4 rule 2; R4c, Q3).

RULE 2: a site reaches the kit (`mf_define` / `mf_emit`) with no `delegated`
manifest row. The site is identified by the pcrec FUNCTION that makes the call
(a manifest row names its emitters and companions; after a step's REPLACE the
emitters column names the pcrec site builders, Q4), and the calls are COUNTED
over a corpus compile pass:

  1. static discovery (`find_callers`): every `mf_define(` / `mf_emit(` call
     under src/, attributed to its enclosing function. This is the key the
     rev-3 text got wrong (`mf_emit_site(` names nothing in the API);
  2. a TRACED build (`build_traced`): the caller files are recompiled with a
     shim that logs (kind, file, function) before forwarding to the kit, then
     relinked over a copy of build/libpcrec.a. The shim is this check's own
     (never src/'s), so pcrec grows no tracing hook;
  3. the corpus pass (`corpus_patterns`, `run_corpus`): the patterns of the
     tests' .rxt files, deterministically sampled, compiled by the traced
     binary; the trace file gives the sites rendered per compile;
  4. the verdict (`verdict`): every function seen calling the kit must be
     named by a `delegated` row (an unlisted site), and every `delegated`
     row must be REACHED by at least one call over the corpus (a delegation
     nothing renders is a vacuous row; K35's reach).

UNREACHED, LOUDLY: with no caller under src/ and no `delegated` row the half
has nothing to count; the caller prints that, and it is never a pass.
The mechanism is exercised on a SYNTHETIC caller every run (`selftest`), so
"UNREACHED" says "no pcrec site yet", never "the census machinery is broken".
"""

import os
import re
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from c17_lex import _name_from_header  # noqa: E402

CALL_RX = re.compile(r'\bmf_(define|emit)\s*\(')
CORPUS_CAP = 300            # compiles per pass
CORPUS_FLOOR = 100          # K35: a pass that compiled fewer is not a census


def strip_c(text):
    def blank(m):
        return re.sub(r'[^\n]', ' ', m.group(0))
    return re.sub(r'/\*.*?\*/|//[^\n]*|"(?:\\.|[^"\\\n])*"|\'(?:\\.|[^\'\\\n])*\'',
                  blank, text, flags=re.S)


def callers_in_text(text):
    """{enclosing definition: number of mf_define/mf_emit calls}."""
    code = strip_c(text)
    out, depth, head, name = {}, 0, 0, None
    pos = 0
    events = sorted([(m.start(), 'call') for m in CALL_RX.finditer(code)] +
                    [(i, c) for i, c in enumerate(code) if c in '{};'])
    for at, what in events:
        if what == '{':
            if depth == 0:
                name = _name_from_header(re.sub(r'^\s*#[^\n]*', '', code[head:at], flags=re.M))
            depth += 1
        elif what == '}':
            depth = max(0, depth - 1)
            if depth == 0:
                head, name = at + 1, None
        elif what == ';':
            if depth == 0:
                head = at + 1
        else:
            key = name if depth > 0 and name else '<file scope>'
            out[key] = out.get(key, 0) + 1
    return out


def find_callers(root):
    """{relative file: {function: calls}} for every C file under src/."""
    res = {}
    for dp, _dns, fns in os.walk(os.path.join(root, 'src')):
        for fn in sorted(fns):
            if not fn.endswith('.c'):
                continue
            path = os.path.join(dp, fn)
            with open(path, encoding='utf-8', errors='replace') as fh:
                c = callers_in_text(fh.read())
            if c:
                res[os.path.relpath(path, root)] = c
    return res


SHIM_H = r'''/* C17 census trace shim (generated by tests/memfn/site_census.py) */
#include <stddef.h>
void c17_trace(const char *kind, const char *file, const char *func);
#undef mf_define
#undef mf_emit
#define mf_define(...) (c17_trace("define", __FILE__, __func__), MF_NS(define)(__VA_ARGS__))
#define mf_emit(...)   (c17_trace("emit",   __FILE__, __func__), MF_NS(emit)(__VA_ARGS__))
'''

SHIM_C = r'''#include <stdio.h>
#include <stdlib.h>
void c17_trace(const char *kind, const char *file, const char *func)
{
    const char *p = getenv("C17_TRACE_FILE");
    FILE *f = p ? fopen(p, "a") : NULL;
    if (!f) return;
    fprintf(f, "%s\t%s\t%s\n", kind, file, func);
    fclose(f);
}
'''


def run(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def build_traced(root, cc, files, tmp):
    """Recompile `files` with the shim over a copy of build/libpcrec.a and
    link cli/main.c; returns (binary, None) or (None, why)."""
    lib = os.path.join(root, 'build/libpcrec.a')
    if not os.path.isfile(lib):
        return None, 'build/libpcrec.a is absent: run `make` first'
    hdr = os.path.join(tmp, 'c17_shim.h')
    with open(hdr, 'w') as fh:
        fh.write(SHIM_H)
    shim_c = os.path.join(tmp, 'c17_shim.c')
    with open(shim_c, 'w') as fh:
        fh.write(SHIM_C)
    kit_h = os.path.join(root, 'memfn/include/memfn.h')
    inc = ['-I' + os.path.join(root, 'lib'), '-I' + os.path.join(root, 'src')]
    members = run(['ar', 't', lib]).stdout.split()
    objs = [os.path.join(tmp, 'c17_shim.o')]
    r = run([cc, '-O1', '-std=gnu11', '-c', '-o', objs[0], shim_c])
    if r.returncode:
        return None, 'shim does not compile: ' + r.stderr[:200]
    olds = []
    for f in files:
        base = os.path.splitext(os.path.basename(f))[0] + '.o'
        if members.count(base) != 1:
            return None, 'archive member %s is not unique (%d)' % (base, members.count(base))
        o = os.path.join(tmp, 'tr_' + base)
        r = run([cc, '-O1', '-std=gnu11'] + inc + ['-include', kit_h, '-include', hdr, '-c',
                '-o', o, os.path.join(root, f)])
        if r.returncode:
            return None, '%s does not compile with the shim: %s' % (f, r.stderr[:300])
        shutil.copy(o, os.path.join(tmp, base))
        olds.append(base)
        objs.append(os.path.join(tmp, base))
    tlib = os.path.join(tmp, 'libtraced.a')
    shutil.copy(lib, tlib)
    if run(['ar', 'd', tlib] + olds).returncode:
        return None, 'ar d failed'
    if run(['ar', 'rs', tlib] + objs).returncode:
        return None, 'ar r failed'
    exe = os.path.join(tmp, 'pcrec_traced')
    r = run([cc, '-O1', '-std=gnu11'] + inc + ['-o', exe, os.path.join(root, 'cli/main.c'), tlib])
    if r.returncode:
        return None, 'traced link failed: ' + r.stderr[:300]
    return exe, None


def corpus_patterns(root):
    """Deterministic sample of the .rxt corpus's `pattern` lines."""
    pats = []
    for dp, dns, fns in os.walk(os.path.join(root, 'tests')):
        dns[:] = sorted(d for d in dns if d != 'memfn')
        for fn in sorted(fns):
            if fn.endswith('.rxt'):
                with open(os.path.join(dp, fn), encoding='utf-8', errors='replace') as fh:
                    for line in fh:
                        if line.startswith('pattern '):
                            pats.append(line[8:].rstrip('\n'))
    seen, uniq = set(), []
    for p in pats:
        if p not in seen:
            seen.add(p)
            uniq.append(p)
    step = max(1, len(uniq) // CORPUS_CAP)
    return uniq[::step][:CORPUS_CAP]


def run_corpus(exe, pats, tmp):
    """Compile every pattern; returns (compiles ok, [per-compile trace rows])."""
    trace = os.path.join(tmp, 'trace.tsv')
    out = os.path.join(tmp, 'out.c')
    per, okc = [], 0
    for p in pats:
        if os.path.exists(trace):
            os.remove(trace)
        env = dict(os.environ, C17_TRACE_FILE=trace)
        try:
            r = subprocess.run([exe, '--features', 'all', '-p', 'rx', '-o', out, '--pattern', p],
                               capture_output=True, env=env, timeout=30)
        except subprocess.TimeoutExpired:
            continue
        if r.returncode != 0:
            continue
        okc += 1
        rows = []
        if os.path.exists(trace):
            with open(trace) as fh:
                rows = [l.rstrip('\n').split('\t') for l in fh if l.strip()]
        per.append(rows)
    return okc, per


def verdict(per, deleg):
    """per: per-compile [(kind, file, func)]; deleg: {row id: set of functions}.
    Returns (problems, stats)."""
    probs = []
    seen = {}
    for rows in per:
        for _k, _f, fn in rows:
            seen[fn] = seen.get(fn, 0) + 1
    listed = set().union(*deleg.values()) if deleg else set()
    for fn in sorted(seen):
        if fn not in listed:
            probs.append('rule 2: %s reached the kit %d time(s) over the corpus pass with no '
                         '`delegated` row naming it (an unlisted site)' % (fn, seen[fn]))
    for row in sorted(deleg):
        if not (deleg[row] & set(seen)):
            probs.append('rule 2 (reach): `delegated` row %s was never rendered over the corpus '
                         'pass (none of %s called the kit): a delegation nothing renders is '
                         'vacuous, or the corpus lacks its witness'
                         % (row, ','.join(sorted(deleg[row]))))
    calls = [len(r) for r in per]
    stats = {'compiles': len(per), 'calls': sum(calls), 'max': max(calls) if calls else 0,
             'withsite': sum(1 for c in calls if c), 'seen': seen}
    return probs, stats


def selftest(cc):
    """The mechanism on a SYNTHETIC caller: [(ok, message)]."""
    res = []
    # (a) call discovery, with decoys that must not count
    src = ('/* mf_define( in a comment */\n'
           'static const char *s = "mf_emit(";\n'
           'static void builder(mf_art *a) { mf_define(a); { mf_emit(a); } }\n'
           'int other(void) { return 0; }\n')
    got = callers_in_text(src)
    res.append((got == {'builder': 2}, 'selftest: call discovery attributes 2 calls to `builder`, '
                'ignores a comment and a string (got %r)' % got))
    # (b) verdict logic on synthetic traces
    t = [[('define', 'f.c', 'fake_builder')], [], [('emit', 'f.c', 'fake_builder')]]
    p, st = verdict(t, {'ROW': {'fake_builder'}})
    res.append((not p and st['calls'] == 2 and st['withsite'] == 2,
                'selftest: a listed and reached site passes, 2 calls over 3 compiles'))
    p, _ = verdict(t, {'ROW': {'other_fn'}})
    res.append((len(p) == 2, 'selftest: an unlisted caller AND an unreached delegated row each '
                'fail (%d problems)' % len(p)))
    # (c) the shim, end to end, on a synthetic caller
    if shutil.which(cc) is None:
        res.append((False, 'selftest: compiler %r not found' % cc))
        return res
    tmp = tempfile.mkdtemp(prefix='c17census.', dir=os.environ.get('TMPDIR'))
    try:
        here = os.path.dirname(os.path.abspath(__file__))
        kit_h = os.path.join(here, '../../memfn/include/memfn.h')
        with open(os.path.join(tmp, 'c17_shim.h'), 'w') as fh:
            fh.write(SHIM_H)
        with open(os.path.join(tmp, 'c17_shim.c'), 'w') as fh:
            fh.write(SHIM_C)
        with open(os.path.join(tmp, 'stub.c'), 'w') as fh:
            fh.write('#include "memfn.h"\n'
                     'int mf_define(mf_art *a, const mf_site *s, const mf_hooks *d, mf_sink *f, '
                     'uint32_t *h) { (void)a; (void)s; (void)d; (void)f; (void)h; return 0; }\n'
                     'int mf_emit(mf_art *a, const mf_site *s, const mf_hooks *d, mf_sink *b, '
                     'mf_sink *f, mf_result *r) { (void)a; (void)s; (void)d; (void)b; (void)f; '
                     '(void)r; return 0; }\n')
        with open(os.path.join(tmp, 'fake.c'), 'w') as fh:
            fh.write('#include "memfn.h"\n'
                     'static void fake_builder(mf_art *a) { uint32_t h; mf_define(a, 0, 0, 0, &h); }\n'
                     'static void fake_emitter(mf_art *a) { mf_emit(a, 0, 0, 0, 0, 0); }\n'
                     'int main(void) { fake_builder(0); fake_emitter(0); return 0; }\n')
        exe = os.path.join(tmp, 'fake')
        inc = ['-I' + os.path.join(here, '../../memfn/include')]
        # the stub defines the REAL symbol names (through MF_NS), so it is compiled
        # WITHOUT the shim's macros
        stub_o = os.path.join(tmp, 'stub.o')
        r1 = run([cc, '-std=gnu11', '-c'] + inc + ['-o', stub_o, os.path.join(tmp, 'stub.c')])
        r2 = run([cc, '-std=gnu11', '-O0'] + inc + ['-include', os.path.abspath(kit_h), '-include',
                  os.path.join(tmp, 'c17_shim.h'), '-o', exe, os.path.join(tmp, 'fake.c'),
                  os.path.join(tmp, 'c17_shim.c'), stub_o])
        tr = os.path.join(tmp, 'trace.tsv')
        r3 = run([exe], env=dict(os.environ, C17_TRACE_FILE=tr)) if r2.returncode == 0 else None
        rows = []
        if r3 is not None and os.path.exists(tr):
            with open(tr) as fh:
                rows = [l.rstrip('\n').split('\t') for l in fh if l.strip()]
        want = [('define', 'fake_builder'), ('emit', 'fake_emitter')]
        have = [(k, fn) for k, _f, fn in rows]
        res.append((r1.returncode == 0 and r2.returncode == 0 and have == want,
                    'selftest: the shim logs a synthetic caller\'s define and emit by function '
                    '(%s)' % (have if have else (r1.stderr + r2.stderr)[:160])))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    return res
