/* Generated by pcrec. Pattern: ERROR-[0-9]{3,5}: [a-z]+ */
/* Feature set: std1 (modules: classes,modifiers) */
#define PCREC_FEATURE_SET "std1"
#define PCREC_FEATURE_MODULES "classes,modifiers"
#define RX_ALTCLS_MERGES 0
#define RX_ALTCLS_FACTORED 0
#include "dfa_after.h"
#include <string.h>
#include <stdio.h>
#include <string.h>

/* =====================================================================
 * HOW THIS MATCHER WORKS -- a map of this file
 *
 * This is a complete, dependency-free matcher for ONE pattern:
 *
 *     ERROR-[0-9]{3,5}: [a-z]+
 *
 * There is no pattern parser here and nothing to configure. The
 * pattern was compiled away ahead of time; what is left is two
 * table-driven scanners and the entry points that drive them.
 *
 * ONE SEARCH, END TO END (rx_search, below):
 *
 *   1. FORWARD SCAN. Walk the subject left to right, one byte per
 *      step, moving between numbered states by table lookup. Every
 *      time the scan lands in an ACCEPTING state, remember the
 *      position: a match could end here. Keep going to the end of the
 *      subject, or until the table says no transition exists. This
 *      finds where the match ENDS.
 *
 *   2. PREFILTER SKIP -- a shortcut inside step 1. While the scan is
 *      still in the start state and has found nothing, no byte except
 *      'E' can begin a match, so the loop calls memchr() to jump
 *      straight to the next 'E' instead of stepping over the bytes in
 *      between. Speed only: it can never change the answer.
 *
 *   3. REVERSE SCAN. Walk backwards from the end found in step 1,
 *      through a SECOND set of tables built from the same pattern read
 *      right to left. The furthest-back accepting position is where
 *      the match STARTS. The second pass exists because the forward
 *      tables record only where a match can end, never where the one
 *      that ended there began.
 *
 * rx_search does all of the above. rx_match and rx_match_caps are thin
 * wrappers over it, rx_next_pos is caller-facing encoding residue, and
 * rx_info is a static description of what this artifact is. Each is
 * documented at its definition.
 *
 * READING THE TABLES. Each scanner uses three arrays with the same
 * shape:
 *
 *   *_byte_class     folds all 256 byte values down to the few classes
 *                    this pattern can actually tell apart
 *   *_next_state     one row per state, one column per class; the cell
 *                    is the state to move to, or -1 for "dead, stop"
 *   *_is_accepting   1 where a match may end in that state
 *
 * Every table below carries a legend naming its states or classes.
 * ===================================================================== */

/* The forward tables have 9 byte classes, so each row of the forward
 * transition table is 9 cells wide; likewise for the reverse tables.
 * Both are pattern-derived constants, not tuning knobs. */
#define RX_FORWARD_CLASSES 9
#define RX_REVERSE_CLASSES 9

/* Both scanners start in state 0. */
#define RX_FORWARD_START 0
#define RX_REVERSE_START 0

/* "No position recorded yet" -- the sentinel for the two variables that
 * hold a match boundary before one has been found. Positions are
 * unsigned, so the impossible value is the all-ones one. */
#define RX_NO_POSITION ((size_t)-1)

/* K24: noclone denies gcc's partial-inlining pass the
   .part clone of this function -- the split costs a
   measured 1.33x on a scan-bound pattern, with identical
   instructions, purely from code placement. Do not remove;
   see pcrec docs/dev/known_issues.md K24. */
__attribute__((noclone))
int rx_search(const unsigned char *subject, size_t subject_length,
              size_t search_from, ptrdiff_t (*capture_spans)[2])
{
    /* ---- FORWARD TABLES: find where a match ENDS -------------------
     * Byte class of every possible input byte. The pattern can only
     * distinguish a handful of byte kinds, so all 256 values collapse
     * into 9 classes and the transition table needs 9 columns rather
     * than 256.
     *
     * Class legend:
     *   0  every other byte -- from most states this returns the scan
     *      to the start state; from state 14 it ends the match
     *   1  ' '        5  'E'
     *   2  '-'        6  'O'
     *   3  '0'-'9'    7  'R'
     *   4  ':'        8  'a'-'z'
     */
    static const unsigned char rx_forward_byte_class[256] = {
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   2,   0,   0,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   4,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   5,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0,   0,   7,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,
          8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    };

    /* Forward transitions, indexed [state * 9 + class]; -1 means the
     * pattern cannot continue and the scan stops. 15 rows of 9.
     *
     * State legend -- what the scan has consumed on arrival. `D` stands
     * for one decimal digit; the digit-count states are how the {3,5}
     * bound is spelled out in the table.
     *
     *   0  (start) nothing matched yet
     *   1  E                    8  ERROR-DD
     *   2  ER                   9  ERROR-DDD    -- 3 digits, ':' now allowed
     *   3  ERR                 10  ERROR-DDDD
     *   4  ERRO                11  ERROR-DDD:
     *   5  ERROR               12  ERROR-DDDDD  -- 5 digits, no 6th exists
     *   6  ERROR-              13  ERROR-DDD:' '
     *   7  ERROR-D             14  ERROR-DDD:' 'a  ACCEPTING
     *
     * State 14 loops on itself for every further lowercase letter,
     * which is the `+` in `[a-z]+`.
     */
    static const short rx_forward_next_state[135] = {
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        2, 0, 0, 0, 0, 0, 0, 1, 0, 3, 0, 0, 0, 0, 0, 0,
        1, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 6,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 7, 0, 1, 0, 0, 0, 0,
        0, 0, 8, 0, 1, 0, 0, 0, 0, 0, 0, 9, 0, 1, 0, 0,
        0, 0, 0, 0, 10, 11, 1, 0, 0, 0, 0, 0, 0, 12, 11, 1,
        0, 0, 0, 0, 13, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        11, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 14, -1, -1,
        -1, -1, -1, -1, -1, -1, 14,
    };

    /* 1 where a match may end, indexed by forward state. Only state 14
     * -- the one reached after at least one lowercase letter -- accepts.
     */
    static const unsigned char rx_forward_is_accepting[15] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    };

    /* ---- REVERSE TABLES: find where that match BEGINS ---------------
     * The same three-table shape, built from the pattern read right to
     * left, and walked backwards from the end the forward scan found.
     * The byte classes happen to be identical to the forward ones --
     * the same bytes are distinguishable either way round -- but the
     * two tables are independent and need not agree in general.
     *
     * Class legend: identical to the forward class legend above.
     */
    static const unsigned char rx_reverse_byte_class[256] = {
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   2,   0,   0,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   4,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   5,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0,   0,   7,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,
          8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    };

    /* Reverse transitions, indexed [state * 9 + class]; -1 stops the
     * walk. 15 rows of 9. -1 is much commoner here than in the forward
     * table because this walk starts at a known match end rather than
     * anywhere in the subject, so almost nothing else is reachable.
     *
     * State legend -- the bytes consumed so far, listed IN THE ORDER
     * THIS WALK CONSUMES THEM, i.e. the match read backwards. Reading
     * a row's example right to left spells the tail of the match.
     *
     *   0  (start) at the match end
     *   1  a                    8  a' ':DDDD
     *   2  a' '                 9  a' ':DDD-R
     *   3  a' ':               10  a' ':DDDDD
     *   4  a' ':D              11  a' ':DDD-RO
     *   5  a' ':DD             12  a' ':DDD-ROR
     *   6  a' ':DDD            13  a' ':DDD-RORR
     *   7  a' ':DDD-           14  a' ':DDD-RORRE  ACCEPTING
     *
     * State 1 loops on itself for each further lowercase letter, which
     * is the same `+` seen from the other end.
     */
    static const short rx_reverse_next_state[135] = {
        -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 2, -1, -1, -1, -1, -1,
        -1, 1, -1, -1, -1, -1, 3, -1, -1, -1, -1, -1, -1, -1, 4, -1,
        -1, -1, -1, -1, -1, -1, -1, 5, -1, -1, -1, -1, -1, -1, -1, -1,
        6, -1, -1, -1, -1, -1, -1, -1, 7, 8, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, 9, -1, -1, -1, 7, 10, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, 11, -1, -1, -1, -1, 7, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 12, -1, -1, -1, -1, -1,
        -1, -1, -1, 13, -1, -1, -1, -1, -1, -1, 14, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
    };

    /* 1 where the backwards walk has consumed a whole match, indexed by
     * reverse state. Reaching state 14 means the walk has just consumed
     * the leading 'E'. */
    static const unsigned char rx_reverse_is_accepting[15] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    };

    size_t scan_position = search_from;
    size_t last_accept_position = RX_NO_POSITION;
    int forward_state = RX_FORWARD_START;

    if (search_from > subject_length) return 0;

    /* ---- FORWARD SCAN: where does a match end? ----------------------
     * One byte per iteration. The loop keeps the LAST accepting
     * position rather than stopping at the first, because `[a-z]+` can
     * always run further and the longest run is the answer wanted here.
     */
    for (;;) {
        if (rx_forward_is_accepting[forward_state]) last_accept_position = scan_position;

        // Prefilter: nothing found yet and still at the start, so skip
        // ahead to the next byte that could begin a match.
        if (forward_state == RX_FORWARD_START && last_accept_position == RX_NO_POSITION) {
            if (scan_position >= subject_length) return 0;
            // 69 is 'E', the only byte a match can start with.
            const void *candidate = memchr(subject + scan_position, 69,
                                           subject_length - scan_position);
            if (!candidate) return 0;
            scan_position = (size_t)((const unsigned char *)candidate - subject);
        }

        if (scan_position >= subject_length) break;
        // Consume one byte and follow its transition.
        forward_state = rx_forward_next_state[forward_state * RX_FORWARD_CLASSES
                                              + rx_forward_byte_class[subject[scan_position++]]];
        if (forward_state < 0) break;   // dead: no match can continue
    }
    if (last_accept_position == RX_NO_POSITION) return 0;

    /* ---- REVERSE SCAN: where did that match begin? ------------------
     * Walk backwards from the end just found. As above, the walk keeps
     * going past accepting positions and remembers the last one, so the
     * start reported is the earliest -- the leftmost-longest match.
     */
    {
        size_t match_end_position = last_accept_position;
        size_t match_start_position = RX_NO_POSITION;
        size_t rewind_position = match_end_position;
        int reverse_state = RX_REVERSE_START;

        for (;;) {
            if (rx_reverse_is_accepting[reverse_state]) match_start_position = rewind_position;
            // Never rewind past where the caller allowed the search to
            // begin.
            if (rewind_position <= search_from) break;
            // Step back one byte and follow its reverse transition.
            reverse_state = rx_reverse_next_state[reverse_state * RX_REVERSE_CLASSES
                                                  + rx_reverse_byte_class[subject[--rewind_position]]];
            if (reverse_state < 0) break;
        }
        if (match_start_position == RX_NO_POSITION) return 0;

        // Slot 0 is the whole match; this pattern has no capture groups,
        // so there is nothing else to report.
        if (capture_spans) {
            capture_spans[0][0] = (ptrdiff_t)match_start_position;
            capture_spans[0][1] = (ptrdiff_t)match_end_position;
        }
        return 1;
    }
}

/* D49: the give-up codes PROPAGATE rather than collapsing to -1.
 * Unreachable on this engine — a DFA artifact has no counter to
 * exhaust — but written uniformly on purpose: the contract of
 * rx_matchfn is one contract, and a wrapper that discards codes it
 * merely happens never to see is the shape that goes wrong when a
 * later engine shares this emitter. */
ptrdiff_t rx_match(const rx_ctx *ctx)
{
    // Initialized: gcc -O1 false maybe-uninitialized (pcrec K28).
    ptrdiff_t capture_spans[RX_NCAPS][2] = {{0}};
    int search_result = rx_search(ctx->subject, ctx->len, ctx->pos, capture_spans);
    if (search_result < 0) return (ptrdiff_t)search_result;
    // rx_search is a SEARCH and may report a match starting later in the
    // subject; this entry is ANCHORED, so anything that did not start
    // exactly at ctx->pos is not an answer to the question asked.
    if (search_result != 1 || (size_t)capture_spans[0][0] != ctx->pos) return -1;
    return capture_spans[0][1] - capture_spans[0][0];
}

ptrdiff_t rx_match_caps(const rx_ctx *ctx, ptrdiff_t (*capture_spans_out)[2])
{
    // Initialized: gcc -O1 false maybe-uninitialized (pcrec K28).
    ptrdiff_t capture_spans[RX_NCAPS][2] = {{0}};
    int search_result = rx_search(ctx->subject, ctx->len, ctx->pos, capture_spans);
    if (search_result < 0) return (ptrdiff_t)search_result;
    if (search_result != 1 || (size_t)capture_spans[0][0] != ctx->pos) return -1;
    if (capture_spans_out) {
        for (int slot = 0; slot < RX_NCAPS; slot++) {
            capture_spans_out[slot][0] = capture_spans[slot][0];
            capture_spans_out[slot][1] = capture_spans[slot][1];
        }
    }
    return capture_spans[0][1] - capture_spans[0][0];
}

/* byte encoding: one byte is one character, so the next boundary after
 * position is position + 1 and the subject is never read. */
size_t rx_next_pos(const unsigned char *subject, size_t subject_length, size_t position)
{
    (void)subject; (void)subject_length;
    return position + 1;
}

/* A static description of what this artifact is, for callers that hold
 * several matchers and need to tell them apart at run time. Nothing in
 * this file reads it. */
const struct rx_info rx_info = {
    .abi = 2,
    .flags = 2ULL,
    .encoding = 0,
    .ncaps = RX_NCAPS,
    .ngroups = 0,
    .nnames = 0,
    .engine = 1, /* PCREC_ENGINE_DFA */
    .step_budget = -1,
    .work_budget = -1,
    .frame_capacity = -1,
    .subject_ceiling = 0,
    .pattern = "ERROR-[0-9]{3,5}: [a-z]+",
    .pattern_len = 24,
    .groups = NULL,
    .engine_why = NULL,
};

/* Present only because this artifact was generated with --emit-main:
 * a one-shot driver that searches argv[1] and prints the span. */
int main(int argc, char **argv)
{
    // Initialized: gcc -O1 false maybe-uninitialized (pcrec K28).
    ptrdiff_t capture_spans[RX_NCAPS][2] = {{0}};
    if (argc < 2) { fprintf(stderr, "usage: %s <subject>\n", argv[0]); return 2; }
    int search_result = rx_search((const unsigned char *)argv[1], strlen(argv[1]), 0, capture_spans);
    if (search_result == 1) {
        printf("match %td %td\n", capture_spans[0][0], capture_spans[0][1]);
        return 0;
    }
    if (search_result == 0) {
        printf("nomatch\n");
        return 1;
    }
    // The give-up codes: the engine stopped without deciding. A DFA
    // artifact cannot produce these; the arms exist so every artifact's
    // driver reports the same way.
    if (search_result == PCREC_ERR_STEPS) {
        printf("steps\n");
        return 3;
    }
    if (search_result == PCREC_ERR_FRAMES) {
        printf("frames\n");
        return 3;
    }
    if (search_result == PCREC_ERR_WORK) {
        printf("work\n");
        return 3;
    }
    printf("giveup %d\n", search_result);
    return 3;
}
