/* Generated by pcrec. Pattern: ERROR-[0-9]{3,5}: [a-z]+ */
/* Feature set: std1 (modules: classes,modifiers) */
#define PCREC_FEATURE_SET "std1"
#define PCREC_FEATURE_MODULES "classes,modifiers"
#define RX_ALTCLS_MERGES 0
#define RX_ALTCLS_FACTORED 0
#include "dfa_before.h"
#include <string.h>
#include <stdio.h>
#include <string.h>

/* K24: noclone denies gcc's partial-inlining pass the
   .part clone of this function -- the split costs a
   measured 1.33x on a scan-bound pattern, with identical
   instructions, purely from code placement. Do not remove;
   see pcrec docs/dev/known_issues.md K24. */
__attribute__((noclone))
int rx_search(const unsigned char *s, size_t n, size_t startpos, ptrdiff_t (*caps)[2])
{
    static const unsigned char rx_fcls[256] = {
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   2,   0,   0,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   4,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   5,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0,   0,   7,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,
          8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    };
    static const short rx_ftr[135] = {
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        2, 0, 0, 0, 0, 0, 0, 1, 0, 3, 0, 0, 0, 0, 0, 0,
        1, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 0, 6,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 7, 0, 1, 0, 0, 0, 0,
        0, 0, 8, 0, 1, 0, 0, 0, 0, 0, 0, 9, 0, 1, 0, 0,
        0, 0, 0, 0, 10, 11, 1, 0, 0, 0, 0, 0, 0, 12, 11, 1,
        0, 0, 0, 0, 13, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        11, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 14, -1, -1,
        -1, -1, -1, -1, -1, -1, 14,
    };
    static const unsigned char rx_facc[15] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    };
    static const unsigned char rx_rcls[256] = {
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   2,   0,   0,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   4,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   5,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0,   0,   7,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,
          8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    };
    static const short rx_rtr[135] = {
        -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 2, -1, -1, -1, -1, -1,
        -1, 1, -1, -1, -1, -1, 3, -1, -1, -1, -1, -1, -1, -1, 4, -1,
        -1, -1, -1, -1, -1, -1, -1, 5, -1, -1, -1, -1, -1, -1, -1, -1,
        6, -1, -1, -1, -1, -1, -1, -1, 7, 8, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, 9, -1, -1, -1, 7, 10, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, 11, -1, -1, -1, -1, 7, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 12, -1, -1, -1, -1, -1,
        -1, -1, -1, 13, -1, -1, -1, -1, -1, -1, 14, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
    };
    static const unsigned char rx_racc[15] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    };
    size_t pos = startpos;
    size_t last = (size_t)-1;
    int st = 0;
    if (startpos > n) return 0;
    for (;;) {
        if (rx_facc[st]) last = pos;
        if (st == 0 && last == (size_t)-1) {
            if (pos >= n) return 0;
            const void *q = memchr(s + pos, 69, n - pos);
            if (!q) return 0;
            pos = (size_t)((const unsigned char *)q - s);
        }
        if (pos >= n) break;
        st = rx_ftr[st * 9 + rx_fcls[s[pos++]]];
        if (st < 0) break;
    }
    if (last == (size_t)-1) return 0;
    {
        size_t end = last;
        size_t sfound = (size_t)-1;
        size_t pp = end;
        int rst = 0;
        for (;;) {
            if (rx_racc[rst]) sfound = pp;
            if (pp <= startpos) break;
            rst = rx_rtr[rst * 9 + rx_rcls[s[--pp]]];
            if (rst < 0) break;
        }
        if (sfound == (size_t)-1) return 0;
        if (caps) { caps[0][0] = (ptrdiff_t)sfound; caps[0][1] = (ptrdiff_t)end; }
        return 1;
    }
}

/* D49: the give-up codes PROPAGATE rather than collapsing to -1.
 * Unreachable on this engine — a DFA artifact has no counter to
 * exhaust — but written uniformly on purpose: the contract of
 * rx_matchfn is one contract, and a wrapper that discards codes it
 * merely happens never to see is the shape that goes wrong when a
 * later engine shares this emitter. */
ptrdiff_t rx_match(const rx_ctx *ctx)
{
    /* Initialized: gcc -O1 false maybe-uninitialized (pcrec K28). */
    ptrdiff_t caps[RX_NCAPS][2] = {{0}};
    int found = rx_search(ctx->subject, ctx->len, ctx->pos, caps);
    if (found < 0) return (ptrdiff_t)found;
    if (found != 1 || (size_t)caps[0][0] != ctx->pos) return -1;
    return caps[0][1] - caps[0][0];
}

ptrdiff_t rx_match_caps(const rx_ctx *ctx, ptrdiff_t (*caps_out)[2])
{
    /* Initialized: gcc -O1 false maybe-uninitialized (pcrec K28). */
    ptrdiff_t caps[RX_NCAPS][2] = {{0}};
    int found = rx_search(ctx->subject, ctx->len, ctx->pos, caps);
    if (found < 0) return (ptrdiff_t)found;
    if (found != 1 || (size_t)caps[0][0] != ctx->pos) return -1;
    if (caps_out) {
        for (int k = 0; k < RX_NCAPS; k++) {
            caps_out[k][0] = caps[k][0];
            caps_out[k][1] = caps[k][1];
        }
    }
    return caps[0][1] - caps[0][0];
}

/* byte encoding: one byte is one character, so the next boundary after pos
 * is pos + 1 and the subject is never read. */
size_t rx_next_pos(const unsigned char *s, size_t n, size_t pos)
{
    (void)s; (void)n;
    return pos + 1;
}

const struct rx_info rx_info = {
    .abi = 2,
    .flags = 2ULL,
    .encoding = 0,
    .ncaps = RX_NCAPS,
    .ngroups = 0,
    .nnames = 0,
    .engine = 1, /* PCREC_ENGINE_DFA */
    .step_budget = -1,
    .work_budget = -1,
    .frame_capacity = -1,
    .subject_ceiling = 0,
    .pattern = "ERROR-[0-9]{3,5}: [a-z]+",
    .pattern_len = 24,
    .groups = NULL,
    .engine_why = NULL,
};

int main(int argc, char **argv)
{
    /* Initialized: gcc -O1 false maybe-uninitialized (pcrec K28). */
    ptrdiff_t caps[RX_NCAPS][2] = {{0}};
    if (argc < 2) { fprintf(stderr, "usage: %s <subject>\n", argv[0]); return 2; }
    int rc = rx_search((const unsigned char *)argv[1], strlen(argv[1]), 0, caps);
    if (rc == 1) {
        printf("match %td %td\n", caps[0][0], caps[0][1]);
        return 0;
    }
    if (rc == 0) {
        printf("nomatch\n");
        return 1;
    }
    if (rc == PCREC_ERR_STEPS) {
        printf("steps\n");
        return 3;
    }
    if (rc == PCREC_ERR_FRAMES) {
        printf("frames\n");
        return 3;
    }
    if (rc == PCREC_ERR_WORK) {
        printf("work\n");
        return 3;
    }
    printf("giveup %d\n", rc);
    return 3;
}
