/* Generated by pcrec. Pattern: ERROR-[0-9]{3,5}: [a-z]+ */
/* Feature set: std1 (modules: classes,modifiers) */
#ifndef PCREC_GEN_RX_H
#define PCREC_GEN_RX_H

#include <stddef.h>
#include <stdint.h>

#ifndef PCREC_RX_ABI_H
#define PCREC_RX_ABI_H

typedef struct rx_ctx {
    const unsigned char *subject;   /* whole subject, not a slice */
    size_t                len;      /* subject length */
    size_t                pos;      /* where to match, anchored */
    size_t                ncap;     /* capture slots known so far (watermark
                                        mid-match; ncaps on completion) */
    const ptrdiff_t     (*caps)[2]; /* [start,end); {-1,-1} = unset */
    void                 *user;     /* per-binding user data */
} rx_ctx;

/* returns matched length >= 0 (anchored at ctx->pos), -1 (fail), or a
 * typed give-up code in [PCREC_ERR_FLOOR, -2] -- one per way the
 * engine can give up (PCREC_ERR_STEPS/_FRAMES/_WORK). D49: those
 * codes PROPAGATE, they are not collapsed to -1, and a caller doing
 * an exact `== -1` test sees them as distinct values. Values
 * strictly BELOW PCREC_ERR_FLOOR stay RESERVED for a future abort
 * semantic; no pcrec-emitted matcher produces one today, and a
 * generated call site that invokes an rx_matchfn traps on one.
 * Self-contained: must accept ctx->ncap == 0, ctx->caps == NULL. */
typedef ptrdiff_t rx_matchfn(const rx_ctx *ctx);

#define PCREC_ERR_STEPS  (-2)
#define PCREC_ERR_FRAMES (-3)
#define PCREC_ERR_WORK   (-4)
#define PCREC_ERR_FLOOR  (-4)  /* give-ups: [FLOOR,-2]; below: reserved (D49) */

#define PCREC_UNSET ((ptrdiff_t)-1)

typedef struct rx_callout_ref {
    rx_matchfn *fn;
    void       *user;
} rx_callout_ref;

/* Emitted ONLY when a substitution template names it. Renders one
 * template segment from the same rx_ctx a callout receives. Writes at
 * most outcap bytes to out; returns the number of bytes produced, or
 * -1 to fail. Called with out == NULL and outcap == 0, it returns the
 * length it WOULD produce, writing nothing. */
typedef ptrdiff_t rx_renderfn(const rx_ctx *ctx,
                              unsigned char *out, size_t outcap);

typedef struct {
    const char *name;
    int         number;
    int         slot;   /* caps[] index this entry delivers, or -1 if
                           this build delivers no slot for it */
    const char *ref;    /* NULL/empty for the primary's own groups */
} rx_group_entry;

struct rx_info {
    unsigned      abi;             /* layout version */
    uint64_t      flags;           /* PCREC_* option bits, as compiled */
    int           encoding;        /* PCREC_ENC_* */
    int           ncaps;           /* == this artifact's own
                                       <PREFIX>_NCAPS: its caps[]
                                       slot count, all-in */
    int           ngroups;         /* capturing groups in the pattern's
                                       own TEXT (a lexical fact) */
    int           nnames;          /* entries in groups[], named only */
    unsigned      engine;          /* PCREC_ENGINE_DFA=1 /
                                       PCREC_ENGINE_VM=2 */
    int64_t       step_budget;     /* -1 = none */
    int64_t       work_budget;     /* -1 = none. The THIRD bound (D47
                                       SECOND ADDENDUM): per-iteration
                                       forward work the fail label
                                       never sees, in work units. A
                                       step is a backtrack resumption
                                       and is counted separately. */
    int64_t       frame_capacity;  /* -1 = unbounded */
    int64_t       subject_ceiling; /* 0 = unset/not applicable */
    const char           *pattern;     /* source pattern text */
    size_t                pattern_len; /* companion length (K9-proof) */
    const rx_group_entry *groups;       /* sorted, bsearch-able */
    const char           *engine_why;   /* forcing construct/reason, or NULL */
};

#define PCREC_ENGINE_DFA 1
#define PCREC_ENGINE_VM  2

#define PCREC_VM_RUNG_CURSOR           0x1u
#define PCREC_VM_RUNG_FRAMES_BOUNDED   0x2u
#define PCREC_VM_RUNG_FRAMES_UNBOUNDED 0x4u
#define PCREC_VM_RUNG_REVDET           0x8u
#define PCREC_VM_RUNG_COUNTER          0x10u
#define PCREC_VM_STRAT_POSSESSIVE      0x1u
#define PCREC_VM_STRAT_BACKTRACKING    0x2u
#define PCREC_VM_PRUNE_CLAMPED         0x1u
#define PCREC_VM_PRUNE_UNCLAMPED       0x2u

/* Every generated artifact also exports one RESIDUAL entry per
 * encoding (pcrec DD-12/D58), <prefix>-scoped and therefore declared
 * outside this shared block:
 *
 *   size_t <prefix>_next_pos(const unsigned char *s, size_t n,
 *                            size_t pos);
 *
 * It returns the next CHARACTER boundary strictly after pos (every
 * position >= n counts as a boundary), and it is the one place an
 * artifact's byte-vs-character distinction lives: a find-all loop
 * advances past a zero-length match with it and needs no change when
 * the same pattern is compiled for another encoding. Full contract:
 * that declaration's own comment, and pcrec's
 * docs/spec/match_api.md S3.1. */

#endif /* PCREC_RX_ABI_H */

#define RX_NCAPS 1

int rx_search(const unsigned char *s, size_t n, size_t startpos, ptrdiff_t (*caps)[2]);
ptrdiff_t rx_match(const rx_ctx *ctx);
ptrdiff_t rx_match_caps(const rx_ctx *ctx, ptrdiff_t (*caps_out)[2]);
extern const struct rx_info rx_info;

/* rx_next_pos -- the ENCODING RESIDUAL entry (pcrec DD-12/D58).
 *
 * Returns the smallest position STRICTLY GREATER than pos that is a
 * CHARACTER BOUNDARY of this artifact's encoding, counting every position
 * >= n as a boundary. So the result is in (pos, n] whenever pos < n, and is
 * pos + 1 whenever pos >= n -- which is what lets a find-all loop advance
 * past a zero-length match and still terminate (see pcrec's
 * docs/spec/match_api.md S3.1, which writes that loop out).
 *
 * This entry is the ONE place an artifact's byte-vs-character distinction
 * lives. It reads s only at offsets in [pos, n), so the (s == NULL, n == 0)
 * subject rx_search accepts is legal here too, and it is never called from
 * this artifact's own engine: it is caller-facing residue, not hot-path
 * code.
 *
 * THIS artifact was compiled for the `byte` encoding, where one byte is one
 * character. An artifact compiled for another encoding exports this same
 * entry with that encoding's body and no caller loop changes. */
size_t rx_next_pos(const unsigned char *s, size_t n, size_t pos);

#endif /* PCREC_GEN_RX_H */
