/* Generated by pcrec. Pattern: (\w+)@(\w+)\.(com|org) */
/* Feature set: std1 (modules: classes,modifiers) */
#define PCREC_FEATURE_SET "std1"
#define PCREC_FEATURE_MODULES "classes,modifiers"
#define RX_ALTCLS_MERGES 0
#define RX_ALTCLS_FACTORED 0
#include "vm_after.h"
#include <string.h>
#include <stdio.h>
#include <string.h>

/* =====================================================================
 * HOW THIS MATCHER WORKS -- a map of this file
 *
 * This is a complete, dependency-free matcher for ONE pattern:
 *
 *     (\w+)@(\w+)\.(com|org)
 *
 * The pattern was compiled away ahead of time. Unlike a pure
 * table-driven matcher, this one has to report where each of the three
 * PARENTHESISED GROUPS matched, so it is built in two halves that run
 * one after the other:
 *
 *   HALF 1 -- rx_prefilter(). A pair of table-driven scanners, forward
 *     then reverse, that answer "is there a match at all, and between
 *     which two offsets?" while ignoring the groups entirely. This is
 *     the same machinery a group-free pattern would compile to, and it
 *     is fast: it never backtracks. What it cannot do is say where the
 *     groups fell.
 *
 *   HALF 2 -- rx_match_anchored(). A straight-line program, one label
 *     per position in the pattern, that walks the span half 1 found and
 *     records each group's start and end as it passes them. It runs
 *     ANCHORED inside that span, so it never has to scan the subject
 *     looking for a starting point.
 *
 * Running half 1 first is not merely an optimisation. The program in
 * half 2 can BACKTRACK -- see below -- and on some patterns a search
 * that had to try every starting position would be catastrophically
 * slow. Handing it an exact window is what bounds the work.
 *
 * HOW THE PROGRAM IN HALF 2 IS LAID OUT. Each pattern position is a
 * label `rx_L<N>`; control moves by `goto`. The numbering is shared
 * with `pcrec --emit-ir`, which prints the same program in readable
 * form, so the numbers are deliberately NOT renamed. Three things can
 * happen at a label: consume a byte and move on, record a group
 * boundary, or -- where the pattern offers a choice -- push a RESUME
 * FRAME recording the alternative and take the preferred branch.
 *
 * BACKTRACKING, in one paragraph, because it is the one mechanism in
 * this file that is not local. When any label finds the subject does
 * not match, it jumps to `rx_fail`. That is the ONLY place this program
 * ever goes backwards. It pops the most recent resume frame, restores
 * the subject position to where the frame was pushed, undoes every
 * group boundary written since (that is what the TRAIL is for), and
 * jumps to the alternative the frame named. With no frames left, there
 * is no match.
 *
 * THE THREE BOUNDS. The program carries three counters so that a
 * pathological pattern-and-subject pair cannot run forever: resume
 * frames (capacity RX_RESUME_FRAMES), trail entries (RX_TRAIL_FRAMES),
 * a step budget (RX_STEP_BUDGET, one step per backtrack) and a work
 * budget (RX_WORK_BUDGET, for forward work that backtracking never
 * sees). Exhausting any of them returns a distinct negative code
 * meaning "gave up", which is NOT the same answer as "no match".
 *
 * rx_search drives both halves; rx_match and rx_match_caps are anchored
 * entry points that skip half 1. Each is documented at its definition.
 * ===================================================================== */

/* Engine: vm (forced by: capture group at pattern offset 0) */
/* Step budget: 500000000 backtrack resumptions; backtrack frames: 2 */
#define RX_ENGINE "vm"
#define RX_ENGINE_WHY "capture group at pattern offset 0"
#define RX_VM_PREFILTER "hybrid"
#define RX_VM_RUNGS 0x1u
#define RX_VM_STRATS 0x1u
#define RX_VM_PRUNES 0x1u
#define RX_VM_PRUNE_CEILING "prefilter-window"
#define RX_NSLOTS 8
#define RX_RESUME_FRAMES 2
#define RX_TRAIL_FRAMES 7
#define RX_STEP_BUDGET 500000000LL
#define RX_WORK_BUDGET 1000000000LL

/* SLOT LEGEND -- names for the numbered cells of the slot array below.
 * A capture group occupies a PAIR of slots, its start and its end. The
 * whole-match pair (0,1) is listed for completeness only: the VM never
 * writes it, because the entry point already knows where the attempt
 * began and how long it ran (see rx_report_captures). */
#define RX_SLOT_WHOLE_START  0   /* not written by the VM */
#define RX_SLOT_WHOLE_END    1   /* not written by the VM */
#define RX_SLOT_GROUP1_START 2
#define RX_SLOT_GROUP1_END   3
#define RX_SLOT_GROUP2_START 4
#define RX_SLOT_GROUP2_END   5
#define RX_SLOT_GROUP3_START 6
#define RX_SLOT_GROUP3_END   7

/* Everything one match attempt can change, in one struct, so that no
 * state lives in globals and two attempts can never interfere. Allocated
 * by the caller on the stack; this file never allocates.
 *
 *   slot_values   the group boundaries recorded so far, by slot number
 *                 (see the slot legend above)
 *   resume_stack  alternatives not yet tried, most recent last; each
 *                 frame is "if you get stuck, come back to HERE"
 *   trail         an undo log of slot_values writes, so popping a resume
 *                 frame can restore the groups exactly as they were
 *   *_depth       how many entries of each are currently live
 *   steps_left    backtracks remaining before the attempt gives up
 *   work_left     forward work units remaining, counted separately
 */
typedef struct {
    ptrdiff_t slot_values[RX_NSLOTS];
    struct { const void *resume_label; size_t resume_position; unsigned trail_mark; }
             resume_stack[RX_RESUME_FRAMES];
    struct { unsigned slot_index; ptrdiff_t saved_value; }
             trail[RX_TRAIL_FRAMES];
    unsigned resume_depth, trail_depth;
    long long steps_left;
    long long work_left;
} rx_run_state;

#define RX_R_STEPS  ((ptrdiff_t)PCREC_ERR_STEPS)
#define RX_R_FRAMES ((ptrdiff_t)PCREC_ERR_FRAMES)
#define RX_R_WORK   ((ptrdiff_t)PCREC_ERR_WORK)

/* Charge forward work that the backtracker never sees. A scan that
 * races over a megabyte costs no STEPS -- it never backtracks -- so
 * without this meter a slow attempt could look free. */
#define RX_CHARGE_WORK(units_) do {                          \
        ptrdiff_t charged_ = (ptrdiff_t)(units_);             \
        if (charged_ > 0) {                                   \
            run->work_left -= (long long)charged_;            \
            if (run->work_left < 0) return RX_R_WORK;         \
        }                                                     \
    } while (0)

/* MINIMUM-REMAINING-LENGTH pruning. At each point the compiler knows
 * the fewest bytes any successful continuation must still consume. If
 * fewer than that remain before the window ends, this position cannot
 * lead to a match, so the program can fail immediately instead of
 * exploring from it. RX_CLAMP_SPAN is the same fact used to shorten a
 * scan rather than to abandon it, rounded down to a whole number of
 * loop iterations so the cursor stays on a position the loop could
 * actually have stopped at. */
#define RX_TOO_SHORT(position_, min_rest_) \
    ((rx_window_end) < (size_t)(min_rest_) \
     || (rx_window_end) - (size_t)(min_rest_) < (position_))
#define RX_CLAMP_SPAN(position_, min_rest_, stride_) \
    ((position_) + (size_t)(stride_) \
     * (((rx_window_end) - (size_t)(min_rest_) - (position_)) / (size_t)(stride_)))

/* The four operations the program below performs on the run state.
 * RX_SET writes a group boundary AND logs the old value (RX_TRAIL) so
 * backtracking can put it back; RX_PUSH records an untried alternative;
 * RX_CUT discards frames wholesale where the pattern says an earlier
 * choice may no longer be revisited. Each returns a give-up code rather
 * than overrunning its fixed-size array. */
#define RX_TRAIL(slot_) do {                                       \
        if (run->trail_depth >= RX_TRAIL_FRAMES) return RX_R_FRAMES; \
        run->trail[run->trail_depth].slot_index = (unsigned)(slot_); \
        run->trail[run->trail_depth].saved_value = slot_values[(slot_)]; \
        run->trail_depth++;                                        \
    } while (0)
#define RX_SET(slot_, value_) do {                                 \
        RX_TRAIL(slot_); slot_values[(slot_)] = (value_);          \
    } while (0)
#define RX_PUSH(label_, position_) do {                            \
        if (run->resume_depth >= RX_RESUME_FRAMES) return RX_R_FRAMES; \
        run->resume_stack[run->resume_depth].resume_label = (label_); \
        run->resume_stack[run->resume_depth].resume_position = (position_); \
        run->resume_stack[run->resume_depth].trail_mark = run->trail_depth; \
        run->resume_depth++;                                       \
    } while (0)
#define RX_CUT(slot_) do {                                         \
        run->resume_depth = (unsigned)slot_values[(slot_)];        \
    } while (0)

/* Start a fresh attempt: every group unset, nothing to undo, both
 * budgets full. */
static void rx_run_state_init(rx_run_state *run)
{
    int slot;
    for (slot = 0; slot < RX_NSLOTS; slot++) run->slot_values[slot] = PCREC_UNSET;
    run->resume_depth = 0; run->trail_depth = 0;
    run->steps_left = RX_STEP_BUDGET;
    run->work_left = RX_WORK_BUDGET;
}

/* Roll the run state back to as-if-untouched WITHOUT resetting the
 * budgets, so that retrying at the next starting position cannot buy
 * itself a fresh allowance. */
static void rx_reset_for_next_attempt(rx_run_state *run)
{
    while (run->trail_depth) {
        run->trail_depth--;
        run->slot_values[run->trail[run->trail_depth].slot_index] =
            run->trail[run->trail_depth].saved_value;
    }
    run->resume_depth = 0;
}

/* Membership bitmap for the byte class `\w`, one bit per byte value:
 * bit (b & 7) of byte b >> 3 is set when b is in the class. 32 bytes
 * covers all 256 values, and the test is two shifts and an AND. */
static const unsigned char rx_class_bitmap_0[32] = {
      0,   0,   0,   0,   0,   0, 255,   3,
    254, 255, 255, 135, 254, 255, 255,   7,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
};

/* The forward tables have 9 byte classes, so each row of the forward
 * transition table is 9 cells wide; likewise for the reverse tables.
 * Both are pattern-derived constants, not tuning knobs. */
#define RX_FORWARD_CLASSES 9
#define RX_REVERSE_CLASSES 9

/* Both prefilter scanners start in state 0. */
#define RX_FORWARD_START 0
#define RX_REVERSE_START 0

/* "No position recorded yet" -- the sentinel for a variable holding a
 * match boundary before one has been found. Positions are unsigned, so
 * the impossible value is the all-ones one. */
#define RX_NO_POSITION ((size_t)-1)

/* The capture-erased forward+reverse DFA pair, emitted by the
 * SAME emitter the DFA-only artifact uses (src/gen/emit_dfa.c),
 * under a private name. It is not an over-approximation: D31
 * erases the group at parse time and A_CAP is invisible to the
 * NFA builder, so this IS the machine the capture-erased pattern
 * compiles to (engine_m4.md 6.1, STRUCTURAL). It hands the VM an
 * anchored window so the VM never scans the subject, which is not
 * an optimization but the guard on a measured cliff: bench case
 * (e) is 25.4 GB/s on pcrec today against pcre2-interp's DNF>90s,
 * and adding two parentheses must not move pcrec onto the DNF
 * side. Prefilter-before-VM is therefore an ORDERING RULE (4.7),
 * not a tuning knob: a pattern whose prefilter can answer must
 * never reach the step budget. */
/* K24: noclone denies gcc's partial-inlining pass the
   .part clone of this function -- the split costs a
   measured 1.33x on a scan-bound pattern, with identical
   instructions, purely from code placement. Do not remove;
   see pcrec docs/dev/known_issues.md K24. */
__attribute__((noclone))
static int rx_prefilter(const unsigned char *subject, size_t subject_length,
                        size_t search_from, ptrdiff_t (*capture_spans)[2])
{
    /* Byte class of every input byte, for the forward scan. All 256
     * values fold to 9 classes, so a transition row is 9 cells wide
     * rather than 256. `W` below means a byte in `\w`.
     *
     * Class legend:
     *   0  every other byte      5  'g'
     *   1  '.'                   6  'm'
     *   2  W, except c/g/m/o/r   7  'o'
     *   3  '@'                   8  'r'
     *   4  'c'
     */
    static const unsigned char rx_forward_byte_class[256] = {
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,
          2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   0,   0,   0,   0,   0,   0,
          3,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
          2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   0,   0,   0,   0,   2,
          0,   2,   2,   4,   2,   2,   2,   5,   2,   2,   2,   2,   2,   6,   2,   7,
          2,   2,   8,   2,   2,   2,   2,   2,   2,   2,   2,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    };
    /* Forward transitions, indexed [state * 9 + class]; -1 stops the
     * scan. 10 rows of 9.
     *
     * State legend -- what has been consumed on arrival, with `W` for a
     * run of word bytes:
     *   0  (start) nothing yet    5  W@W.c
     *   1  W                      6  W@W.o
     *   2  W@                     7  W@W.co
     *   3  W@W                    8  W@W.or
     *   4  W@W.                   9  W@W.com or W@W.org   ACCEPTING
     */
    static const short rx_forward_next_state[90] = {
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 1, 1, 1,
        1, 1, 0, 0, 3, 0, 3, 3, 3, 3, 3, 0, 4, 3, 2, 3,
        3, 3, 3, 3, 0, 0, 1, 0, 5, 1, 1, 6, 1, 0, 0, 1,
        2, 1, 1, 1, 7, 1, 0, 0, 1, 2, 1, 1, 1, 1, 8, 0,
        0, 1, 2, 1, 1, 9, 1, 1, 0, 0, 1, 2, 1, 9, 1, 1,
        1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    };
    /* 1 where a match may end, indexed by forward state. */
    static const unsigned char rx_forward_is_accepting[10] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    };
    /* 1 for each byte that could be the FIRST byte of a match. The
     * forward loop uses this to skip over bytes that cannot start one
     * instead of stepping through them; it only affects speed. */
    static const unsigned char rx_can_begin_match[256] = {
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   0,   0,   0,   0,   0,   0,
          0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   0,   0,   0,   0,   1,
          0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    };
    /* The reverse scan's own three tables, built from the pattern read
     * right to left and walked backwards from the end the forward scan
     * found. Class legend: identical to the forward one above. */
    static const unsigned char rx_reverse_byte_class[256] = {
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,
          2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   0,   0,   0,   0,   0,   0,
          3,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
          2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   0,   0,   0,   0,   2,
          0,   2,   2,   4,   2,   2,   2,   5,   2,   2,   2,   2,   2,   6,   2,   7,
          2,   2,   8,   2,   2,   2,   2,   2,   2,   2,   2,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    };
    /* Reverse transitions, indexed [state * 9 + class]; -1 stops the
     * walk. 10 rows of 9.
     *
     * State legend -- bytes consumed IN THIS WALK'S ORDER, i.e. the
     * match read backwards; read a row's example right to left to see
     * the tail of the match it describes:
     *   0  (start) at the match end   5  gro
     *   1  g                          6  gro.
     *   2  m                          7  gro.W
     *   3  gr                         8  gro.W@
     *   4  mo                         9  gro.W@W   ACCEPTING
     */
    static const short rx_reverse_next_state[90] = {
        -1, -1, -1, -1, -1, 1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, 3, -1, -1, -1, -1, -1, -1, -1, 4, -1, -1, -1, -1, -1, -1,
        -1, -1, 5, -1, -1, -1, -1, -1, 5, -1, -1, -1, -1, -1, 6, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, 7, -1, 7, 7, 7, 7, 7, -1,
        -1, 7, 8, 7, 7, 7, 7, 7, -1, -1, 9, -1, 9, 9, 9, 9,
        9, -1, -1, 9, -1, 9, 9, 9, 9, 9,
    };
    /* 1 where the backwards walk has consumed a whole match. */
    static const unsigned char rx_reverse_is_accepting[10] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    };
    size_t scan_position = search_from;
    size_t last_accept_position = RX_NO_POSITION;
    int forward_state = RX_FORWARD_START;

    if (search_from > subject_length) return 0;

    /* FORWARD SCAN: where can a match end? One byte per step; remember
     * every accepting position and keep going, so the last one wins. */
    for (;;) {
        if (rx_forward_is_accepting[forward_state]) last_accept_position = scan_position;
        /* Nothing found yet and still at the start: skip over bytes that
         * cannot begin a match rather than stepping through them. */
        if (forward_state == RX_FORWARD_START && last_accept_position == RX_NO_POSITION) {
            while (scan_position < subject_length
                   && !rx_can_begin_match[subject[scan_position]]) scan_position++;
            if (scan_position >= subject_length) return 0;
        }
        if (scan_position >= subject_length) break;
        forward_state = rx_forward_next_state[forward_state * RX_FORWARD_CLASSES
                            + rx_forward_byte_class[subject[scan_position++]]];
        if (forward_state < 0) break;   /* dead: no match can continue */
    }
    if (last_accept_position == RX_NO_POSITION) return 0;

    /* REVERSE SCAN: where did that match begin? */
    {
        size_t match_end_position = last_accept_position;
        size_t match_start_position = RX_NO_POSITION;
        size_t rewind_position = match_end_position;
        int reverse_state = RX_REVERSE_START;

        for (;;) {
            if (rx_reverse_is_accepting[reverse_state]) match_start_position = rewind_position;
            if (rewind_position <= search_from) break;
            reverse_state = rx_reverse_next_state[reverse_state * RX_REVERSE_CLASSES
                                + rx_reverse_byte_class[subject[--rewind_position]]];
            if (reverse_state < 0) break;
        }
        if (match_start_position == RX_NO_POSITION) return 0;
        if (capture_spans) {
            capture_spans[0][0] = (ptrdiff_t)match_start_position;
            capture_spans[0][1] = (ptrdiff_t)match_end_position;
        }
        return 1;
    }
}

/* HALF 2: the compiled program. Runs ANCHORED at ctx->pos -- it never
 * looks for a starting position -- and records where each group fell.
 * `rx_window_end` is the ceiling half 1 established: no continuation may
 * consume past it, which is what the RX_TOO_SHORT tests measure against.
 *
 * Returns the matched length, -1 for no match, or a give-up code.
 * Control flows label to label by goto; `pcrec --emit-ir` prints the
 * same program with the same label numbers. */
static ptrdiff_t rx_match_anchored(const rx_ctx *ctx, rx_run_state *run,
                                   const size_t rx_window_end)
{
    const unsigned char *const subject = ctx->subject;
    const size_t subject_length = ctx->len;
    size_t position = ctx->pos;
    ptrdiff_t *const slot_values = run->slot_values;
    size_t rx_span_cursor = 0;   /* the span-loop cursor (engine_m4.md 2.5):
                             a plain local, UNTRAILED, whose save
                             point is a resume frame */
    (void)subject; (void)subject_length; (void)slot_values;
    goto rx_L0;

/* group 1 opens */
rx_L0: __attribute__((unused));
    RX_SET(RX_SLOT_GROUP1_START, (ptrdiff_t)position);
    goto rx_L3;
/* group 1's body: `\w+` */
rx_L3: __attribute__((unused));
    /* Run the class as far as it goes. This loop is POSSESSIVE: it takes
     * the longest run and never gives bytes back, so it pushes no resume
     * frame and cannot be backtracked into. The compiler proved that
     * giving a byte back could never rescue a failure here. */
    {
        rx_span_cursor = position;
        while (rx_span_cursor + 1 <= subject_length
               && ((rx_class_bitmap_0[(subject[rx_span_cursor + 0]) >> 3]
                    >> ((subject[rx_span_cursor + 0]) & 7)) & 1)) { rx_span_cursor += 1; }
    }
    /* Pay for the bytes just scanned. */
    RX_CHARGE_WORK(((ptrdiff_t)(rx_span_cursor - (ptrdiff_t)position)) / 1);
    if ((ptrdiff_t)rx_span_cursor < (ptrdiff_t)position + 1) goto rx_fail;
    if (RX_TOO_SHORT(rx_span_cursor, 6)) goto rx_fail;
    position = rx_span_cursor;
    goto rx_L4;
/* group 1 closes */
rx_L4: __attribute__((unused));
    RX_SET(RX_SLOT_GROUP1_END, (ptrdiff_t)position);
    goto rx_L2;
rx_L2: __attribute__((unused));
    /* consume '@' */
    if (position < subject_length && (subject[position] == 64)) { position++; goto rx_L5; }
    goto rx_fail;
/* group 2 opens */
rx_L5: __attribute__((unused));
    RX_SET(RX_SLOT_GROUP2_START, (ptrdiff_t)position);
    goto rx_L7;
/* group 2's body: `\w+` */
rx_L7: __attribute__((unused));
    /* Run the class as far as it goes. This loop is POSSESSIVE: it takes
     * the longest run and never gives bytes back, so it pushes no resume
     * frame and cannot be backtracked into. The compiler proved that
     * giving a byte back could never rescue a failure here. */
    {
        rx_span_cursor = position;
        while (rx_span_cursor + 1 <= subject_length
               && ((rx_class_bitmap_0[(subject[rx_span_cursor + 0]) >> 3]
                    >> ((subject[rx_span_cursor + 0]) & 7)) & 1)) { rx_span_cursor += 1; }
    }
    /* Pay for the bytes just scanned. */
    RX_CHARGE_WORK(((ptrdiff_t)(rx_span_cursor - (ptrdiff_t)position)) / 1);
    if ((ptrdiff_t)rx_span_cursor < (ptrdiff_t)position + 1) goto rx_fail;
    if (RX_TOO_SHORT(rx_span_cursor, 4)) goto rx_fail;
    position = rx_span_cursor;
    goto rx_L8;
/* group 2 closes */
rx_L8: __attribute__((unused));
    RX_SET(RX_SLOT_GROUP2_END, (ptrdiff_t)position);
    goto rx_L6;
rx_L6: __attribute__((unused));
    /* consume '.' */
    if (position < subject_length && (subject[position] == 46)) { position++; goto rx_L9; }
    goto rx_fail;
/* group 3 opens */
rx_L9: __attribute__((unused));
    RX_SET(RX_SLOT_GROUP3_START, (ptrdiff_t)position);
    goto rx_L10;
/* the alternation (com|org): take branch 1, remember branch 2 */
rx_L10: __attribute__((unused));
    RX_PUSH(&&rx_L14, position);
    goto rx_L12;
/* reached only by backtracking: branch 1 failed, try branch 2 */
rx_L14: __attribute__((unused));
    goto rx_L13;
/* branch 1: "com" */
rx_L12: __attribute__((unused));
    /* consume 'c' */
    if (position < subject_length && (subject[position] == 99)) { position++; goto rx_L15; }
    goto rx_fail;
rx_L15: __attribute__((unused));
    /* consume 'o' */
    if (position < subject_length && (subject[position] == 111)) { position++; goto rx_L16; }
    goto rx_fail;
rx_L16: __attribute__((unused));
    /* consume 'm' */
    if (position < subject_length && (subject[position] == 109)) { position++; goto rx_L11; }
    goto rx_fail;
/* branch 2: "org" */
rx_L13: __attribute__((unused));
    /* consume 'o' */
    if (position < subject_length && (subject[position] == 111)) { position++; goto rx_L17; }
    goto rx_fail;
rx_L17: __attribute__((unused));
    /* consume 'r' */
    if (position < subject_length && (subject[position] == 114)) { position++; goto rx_L18; }
    goto rx_fail;
rx_L18: __attribute__((unused));
    /* consume 'g' */
    if (position < subject_length && (subject[position] == 103)) { position++; goto rx_L11; }
    goto rx_fail;
/* group 3 closes */
rx_L11: __attribute__((unused));
    RX_SET(RX_SLOT_GROUP3_END, (ptrdiff_t)position);
    goto rx_L1;
/* the whole pattern is matched */
rx_L1: __attribute__((unused));
    goto rx_accept;

rx_accept: __attribute__((unused));
    /* 3.1: leftmost-first is FIRST COMPLETE MATCH WINS, not compare
     * candidates. The VM returns here immediately and the capture
     * slots at this instant are the answer — no candidate comparison,
     * no longest-wins, no second pass. The caller's caps array is
     * filled by the ENTRY, not here (3.4). */
    return (ptrdiff_t)(position - ctx->pos);

rx_fail: __attribute__((unused));
    /* THE ONLY BACKTRACKER AND THE ONLY INDIRECT JUMP.
     * A step is one backtrack resumption (4.2), counted at exactly
     * this place — so forward progress is FREE (a linear match over
     * 100 MB costs zero steps), the budget is subject-length-
     * independent, and the counter measures precisely the thing it is
     * meant to bound. D22: DD-2 is ROBUSTNESS, not a security
     * boundary, and it must not be traded against execution speed. */
    if (run->resume_depth == 0) return -1;      /* nothing left to try */
    if (--run->steps_left < 0) return RX_R_STEPS;
    {
        const unsigned frame_index = --run->resume_depth;
        /* Rewind the subject cursor to where the frame was pushed... */
        position = run->resume_stack[frame_index].resume_position;
        /* ...and undo every capture-slot write made since then, newest
         * first, so the slots read as they did at the push. */
        while (run->trail_depth > run->resume_stack[frame_index].trail_mark) {
            run->trail_depth--;
            slot_values[run->trail[run->trail_depth].slot_index] =
                run->trail[run->trail_depth].saved_value;
        }
        goto *run->resume_stack[frame_index].resume_label;
    }
}

#undef RX_TRAIL
#undef RX_SET
#undef RX_PUSH

/* Copy the run's slot values out into the caller's caps array. Slot pair
 * 0 -- the whole match -- is never written by the VM (see the slot legend
 * above); it is computed here from the position this attempt started at
 * and the length it returned. Group k lives in the slot PAIR (2k, 2k+1),
 * which is why this loop indexes arithmetically rather than through the
 * RX_SLOT_* names. */
static void rx_report_captures(const rx_run_state *run, ptrdiff_t (*capture_spans)[2],
                               size_t match_start, ptrdiff_t match_length)
{
    int group;
    capture_spans[0][0] = (ptrdiff_t)match_start;
    capture_spans[0][1] = (ptrdiff_t)match_start + match_length;
    for (group = 1; group < RX_NCAPS; group++) {
        capture_spans[group][0] = run->slot_values[2 * group];
        capture_spans[group][1] = run->slot_values[2 * group + 1];
    }
}

int rx_search(const unsigned char *subject, size_t subject_length,
       size_t search_from, ptrdiff_t (*capture_spans)[2])
{
    rx_run_state run;
    rx_ctx ctx;
    ptrdiff_t result;
    size_t attempt_position;
    size_t window_end;

    if (search_from > subject_length) return 0;

    /* Ask the prefilter where the first plausible match lies. It returns
     * a window; the VM is then run ANCHORED inside it and never scans. */
    {
        ptrdiff_t window[1][2];
        if (rx_prefilter(subject, subject_length, search_from, window) != 1) return 0;
        attempt_position = (size_t)window[0][0];
        window_end = (size_t)window[0][1] < subject_length
                   ? (size_t)window[0][1] : subject_length;
    }
    rx_run_state_init(&run);
    ctx.subject = subject; ctx.len = subject_length; ctx.ncap = 0;
    ctx.caps = NULL; ctx.user = NULL;

    /* Try the VM at the window's start. If the whole pattern fails there,
     * advance one position, re-run the prefilter to find the next window,
     * and try again. */
    for (;;) {
        ctx.pos = attempt_position;
        result = rx_match_anchored(&ctx, &run, window_end);
        /* A bound was hit: report WHY rather than "no match" -- the
         * engine stopped without deciding. */
        if (result == RX_R_STEPS)  return PCREC_ERR_STEPS;
        if (result == RX_R_FRAMES) return PCREC_ERR_FRAMES;
        if (result == RX_R_WORK)   return PCREC_ERR_WORK;
        if (result >= 0) break;
        rx_reset_for_next_attempt(&run);
        if (attempt_position >= subject_length) return 0;
        attempt_position++;
        {
            ptrdiff_t window[1][2];
            if (rx_prefilter(subject, subject_length, attempt_position, window) != 1) return 0;
            attempt_position = (size_t)window[0][0];
            window_end = (size_t)window[0][1] < subject_length
                       ? (size_t)window[0][1] : subject_length;
        }
    }
    if (capture_spans) rx_report_captures(&run, capture_spans, attempt_position, result);
    return 1;
}

/* F1's unconditional export, typed rx_matchfn.
 *
 * D49: THE GIVE-UP CODES ARE CARRIED HERE, not collapsed to -1. The
 * return space is >= 0 matched length, -1 no match, and a distinct
 * code in [PCREC_ERR_FLOOR, -2] for each way the engine can give up
 * (PCREC_ERR_STEPS, PCREC_ERR_FRAMES, PCREC_ERR_WORK). Anything BELOW the floor
 * stays reserved for the future abort semantic and is what a callout
 * call site traps on.
 *
 * This SUPERSEDES D42.3, which collapsed every give-up to -1 because
 * D38.4 had reserved the whole < -1 space. Three things moved: pcrec is
 * pre-release, so a 'final' label reads as 'stable absent a reason';
 * the typedef is BIDIRECTIONAL, so under the collapse an
 * embedder-WRITTEN callout had no legal spelling for 'I gave up' at
 * all (anything below -1 traps the process); and the collapse let an
 * inner give-up read as a plain path failure, so an outer match could
 * report an ANSWER where a bound had actually blown. A caller that
 * only asks 'did it match' still writes `r < 0` and is unaffected. */
ptrdiff_t rx_match(const rx_ctx *ctx)
{
    rx_run_state run;
    ptrdiff_t result;
    if (ctx->pos > ctx->len) return -1;
    rx_run_state_init(&run);
    result = rx_match_anchored(ctx, &run, ctx->len);
    /* No translation and no clamp: the impl's return space IS this
     * contract's -- >= 0, -1, or one of the three R_ sentinels, which
     * are the ERR_ codes. A defensive floor test here would be dead
     * code pretending to be a safeguard. */
    return result;
}

/* The capture-delivering sibling. Same D49 return space as
 * <prefix>_match above -- it always had room for the codes (it is not
 * an rx_matchfn), and now the two agree instead of differing over a
 * reservation only one of them was bound by. caps_out is UNTOUCHED on
 * every negative return, give-up included: a caller that gave up has
 * no captures, and A-8's untouched-wins rule does not bend for it. */
ptrdiff_t rx_match_caps(const rx_ctx *ctx, ptrdiff_t (*capture_spans_out)[2])
{
    rx_run_state run;
    ptrdiff_t result;
    if (ctx->pos > ctx->len) return -1;
    rx_run_state_init(&run);
    result = rx_match_anchored(ctx, &run, ctx->len);
    if (result < 0) return result;
    if (capture_spans_out) rx_report_captures(&run, capture_spans_out, ctx->pos, result);
    return result;
}

/* byte encoding: one byte is one character, so the next boundary after
 * `position` is position + 1 and the subject is never read. */
size_t rx_next_pos(const unsigned char *subject, size_t subject_length,
                   size_t position)
{
    (void)subject; (void)subject_length;
    return position + 1;
}

const struct rx_info rx_info = {
    .abi = 2,
    .flags = 2ULL,
    .encoding = 0,
    .ncaps = RX_NCAPS,
    .ngroups = 3,
    .nnames = 0,
    .engine = 2, /* PCREC_ENGINE_VM */
    .step_budget = 500000000,
    .work_budget = 1000000000,
    .frame_capacity = 2,
    .subject_ceiling = 0,
    .pattern = "(\\w+)@(\\w+)\\.(com|org)",
    .pattern_len = 22,
    .groups = NULL,
    .engine_why = "capture group at pattern offset 0",
};

int main(int argc, char **argv)
{
    /* Initialized: gcc -O1 false maybe-uninitialized (pcrec K28). */
    ptrdiff_t capture_spans[RX_NCAPS][2] = {{0}};
    if (argc < 2) { fprintf(stderr, "usage: %s <subject>\n", argv[0]); return 2; }
    int search_result = rx_search((const unsigned char *)argv[1], strlen(argv[1]), 0,
                                  capture_spans);
    if (search_result == 1) {
        printf("match %td %td\n", capture_spans[0][0], capture_spans[0][1]);
        return 0;
    }
    if (search_result == 0) {
        printf("nomatch\n");
        return 1;
    }
    if (search_result == PCREC_ERR_STEPS) {
        printf("steps\n");
        return 3;
    }
    if (search_result == PCREC_ERR_FRAMES) {
        printf("frames\n");
        return 3;
    }
    if (search_result == PCREC_ERR_WORK) {
        printf("work\n");
        return 3;
    }
    printf("giveup %d\n", search_result);
    return 3;
}
