/* Generated by pcrec. Pattern: (\w+)@(\w+)\.(com|org) */
/* Feature set: std1 (modules: classes,modifiers) */
#define PCREC_FEATURE_SET "std1"
#define PCREC_FEATURE_MODULES "classes,modifiers"
#define RX_ALTCLS_MERGES 0
#define RX_ALTCLS_FACTORED 0
#include "vm_before.h"
#include <string.h>
#include <stdio.h>
#include <string.h>

/* Engine: vm (forced by: capture group at pattern offset 0) */
/* Step budget: 500000000 backtrack resumptions; backtrack frames: 2 */
#define RX_ENGINE "vm"
#define RX_ENGINE_WHY "capture group at pattern offset 0"
#define RX_VM_PREFILTER "hybrid"
#define RX_VM_RUNGS 0x1u
#define RX_VM_STRATS 0x1u
#define RX_VM_PRUNES 0x1u
#define RX_VM_PRUNE_CEILING "prefilter-window"
#define RX_NSTATE 8
#define RX_BT_FRAMES 2
#define RX_TRAIL_FRAMES 7
#define RX_STEP_BUDGET 500000000LL
#define RX_WORK_BUDGET 1000000000LL

typedef struct {
    ptrdiff_t stv[RX_NSTATE];
    struct { const void *k; size_t pos; unsigned mark; } bt[RX_BT_FRAMES];
    struct { unsigned slot; ptrdiff_t v; }               tr[RX_TRAIL_FRAMES];
    unsigned btn, trn;
    long long budget;
    long long work;
} rx_work;

#define RX_R_STEPS  ((ptrdiff_t)PCREC_ERR_STEPS)
#define RX_R_FRAMES ((ptrdiff_t)PCREC_ERR_FRAMES)
#define RX_R_WORK   ((ptrdiff_t)PCREC_ERR_WORK)

#define RX_WORK(n_) do {                                    \
        ptrdiff_t nw_ = (ptrdiff_t)(n_);                     \
        if (nw_ > 0) {                                       \
            w->work -= (long long)nw_;                       \
            if (w->work < 0) return RX_R_WORK;               \
        }                                                    \
    } while (0)

#define RX_MRL_SHORT(p_, mr_) \
    ((rx_ceil) < (size_t)(mr_) || (rx_ceil) - (size_t)(mr_) < (p_))
#define RX_MRL_CAP(p_, mr_, w_) \
    ((p_) + (size_t)(w_) * (((rx_ceil) - (size_t)(mr_) - (p_)) / (size_t)(w_)))

#define RX_TRAIL(slot_) do {                                  \
        if (w->trn >= RX_TRAIL_FRAMES) return RX_R_FRAMES;    \
        w->tr[w->trn].slot = (unsigned)(slot_);               \
        w->tr[w->trn].v = stv[(slot_)];                       \
        w->trn++;                                             \
    } while (0)
#define RX_SET(slot_, v_) do {                                \
        RX_TRAIL(slot_); stv[(slot_)] = (v_);                 \
    } while (0)
#define RX_PUSH(lbl_, p_) do {                                \
        if (w->btn >= RX_BT_FRAMES) return RX_R_FRAMES;       \
        w->bt[w->btn].k = (lbl_);                             \
        w->bt[w->btn].pos = (p_);                             \
        w->bt[w->btn].mark = w->trn;                          \
        w->btn++;                                             \
    } while (0)
#define RX_CUT(slot_) do {                                   \
        w->btn = (unsigned)stv[(slot_)];                      \
    } while (0)

static void rx_work_init(rx_work *w)
{
    int i;
    for (i = 0; i < RX_NSTATE; i++) w->stv[i] = PCREC_UNSET;
    w->btn = 0; w->trn = 0;
    w->budget = RX_STEP_BUDGET;
    w->work = RX_WORK_BUDGET;
}

static void rx_unwind(rx_work *w)
{
    while (w->trn) { w->trn--; w->stv[w->tr[w->trn].slot] = w->tr[w->trn].v; }
    w->btn = 0;
}

static const unsigned char rx_k0[32] = {
      0,   0,   0,   0,   0,   0, 255,   3,
    254, 255, 255, 135, 254, 255, 255,   7,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
};

/* The capture-erased forward+reverse DFA pair, emitted by the
 * SAME emitter the DFA-only artifact uses (src/gen/emit_dfa.c),
 * under a private name. It is not an over-approximation: D31
 * erases the group at parse time and A_CAP is invisible to the
 * NFA builder, so this IS the machine the capture-erased pattern
 * compiles to (engine_m4.md 6.1, STRUCTURAL). It hands the VM an
 * anchored window so the VM never scans the subject, which is not
 * an optimization but the guard on a measured cliff: bench case
 * (e) is 25.4 GB/s on pcrec today against pcre2-interp's DNF>90s,
 * and adding two parentheses must not move pcrec onto the DNF
 * side. Prefilter-before-VM is therefore an ORDERING RULE (4.7),
 * not a tuning knob: a pattern whose prefilter can answer must
 * never reach the step budget. */
/* K24: noclone denies gcc's partial-inlining pass the
   .part clone of this function -- the split costs a
   measured 1.33x on a scan-bound pattern, with identical
   instructions, purely from code placement. Do not remove;
   see pcrec docs/dev/known_issues.md K24. */
__attribute__((noclone))
static int rx_prefilter(const unsigned char *s, size_t n, size_t startpos, ptrdiff_t (*caps)[2])
{
    static const unsigned char rx_fcls[256] = {
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,
          2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   0,   0,   0,   0,   0,   0,
          3,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
          2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   0,   0,   0,   0,   2,
          0,   2,   2,   4,   2,   2,   2,   5,   2,   2,   2,   2,   2,   6,   2,   7,
          2,   2,   8,   2,   2,   2,   2,   2,   2,   2,   2,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    };
    static const short rx_ftr[90] = {
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 1, 1, 1,
        1, 1, 0, 0, 3, 0, 3, 3, 3, 3, 3, 0, 4, 3, 2, 3,
        3, 3, 3, 3, 0, 0, 1, 0, 5, 1, 1, 6, 1, 0, 0, 1,
        2, 1, 1, 1, 7, 1, 0, 0, 1, 2, 1, 1, 1, 1, 8, 0,
        0, 1, 2, 1, 1, 9, 1, 1, 0, 0, 1, 2, 1, 9, 1, 1,
        1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    };
    static const unsigned char rx_facc[10] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    };
    static const unsigned char rx_first[256] = {
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   0,   0,   0,   0,   0,   0,
          0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   0,   0,   0,   0,   1,
          0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    };
    static const unsigned char rx_rcls[256] = {
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,
          2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   0,   0,   0,   0,   0,   0,
          3,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
          2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   0,   0,   0,   0,   2,
          0,   2,   2,   4,   2,   2,   2,   5,   2,   2,   2,   2,   2,   6,   2,   7,
          2,   2,   8,   2,   2,   2,   2,   2,   2,   2,   2,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    };
    static const short rx_rtr[90] = {
        -1, -1, -1, -1, -1, 1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, 3, -1, -1, -1, -1, -1, -1, -1, 4, -1, -1, -1, -1, -1, -1,
        -1, -1, 5, -1, -1, -1, -1, -1, 5, -1, -1, -1, -1, -1, 6, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, 7, -1, 7, 7, 7, 7, 7, -1,
        -1, 7, 8, 7, 7, 7, 7, 7, -1, -1, 9, -1, 9, 9, 9, 9,
        9, -1, -1, 9, -1, 9, 9, 9, 9, 9,
    };
    static const unsigned char rx_racc[10] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    };
    size_t pos = startpos;
    size_t last = (size_t)-1;
    int st = 0;
    if (startpos > n) return 0;
    for (;;) {
        if (rx_facc[st]) last = pos;
        if (st == 0 && last == (size_t)-1) {
            while (pos < n && !rx_first[s[pos]]) pos++;
            if (pos >= n) return 0;
        }
        if (pos >= n) break;
        st = rx_ftr[st * 9 + rx_fcls[s[pos++]]];
        if (st < 0) break;
    }
    if (last == (size_t)-1) return 0;
    {
        size_t end = last;
        size_t sfound = (size_t)-1;
        size_t pp = end;
        int rst = 0;
        for (;;) {
            if (rx_racc[rst]) sfound = pp;
            if (pp <= startpos) break;
            rst = rx_rtr[rst * 9 + rx_rcls[s[--pp]]];
            if (rst < 0) break;
        }
        if (sfound == (size_t)-1) return 0;
        if (caps) { caps[0][0] = (ptrdiff_t)sfound; caps[0][1] = (ptrdiff_t)end; }
        return 1;
    }
}

static ptrdiff_t rx_match_impl(const rx_ctx *ctx, rx_work *w, const size_t rx_ceil)
{
    const unsigned char *const s = ctx->subject;
    const size_t n = ctx->len;
    size_t pos = ctx->pos;
    ptrdiff_t *const stv = w->stv;
    size_t rx_cur = 0;   /* the span-loop cursor (engine_m4.md 2.5):
                             a plain local, UNTRAILED, whose save
                             point is a resume frame */
    (void)s; (void)n; (void)stv;
    goto rx_L0;

rx_L0: __attribute__((unused));
    RX_SET(2, (ptrdiff_t)pos);
    goto rx_L3;
rx_L3: __attribute__((unused));
    {
        rx_cur = pos;
        while (rx_cur + 1 <= n && ((rx_k0[(s[rx_cur + 0]) >> 3] >> ((s[rx_cur + 0]) & 7)) & 1)) { rx_cur += 1; }
    }
    RX_WORK(((ptrdiff_t)(rx_cur - (ptrdiff_t)pos)) / 1);
    if ((ptrdiff_t)rx_cur < (ptrdiff_t)pos + 1) goto rx_fail;
    if (RX_MRL_SHORT(rx_cur, 6)) goto rx_fail;
    pos = rx_cur;
    goto rx_L4;
rx_L4: __attribute__((unused));
    RX_SET(3, (ptrdiff_t)pos);
    goto rx_L2;
rx_L2: __attribute__((unused));
    if (pos < n && (s[pos] == 64)) { pos++; goto rx_L5; }
    goto rx_fail;
rx_L5: __attribute__((unused));
    RX_SET(4, (ptrdiff_t)pos);
    goto rx_L7;
rx_L7: __attribute__((unused));
    {
        rx_cur = pos;
        while (rx_cur + 1 <= n && ((rx_k0[(s[rx_cur + 0]) >> 3] >> ((s[rx_cur + 0]) & 7)) & 1)) { rx_cur += 1; }
    }
    RX_WORK(((ptrdiff_t)(rx_cur - (ptrdiff_t)pos)) / 1);
    if ((ptrdiff_t)rx_cur < (ptrdiff_t)pos + 1) goto rx_fail;
    if (RX_MRL_SHORT(rx_cur, 4)) goto rx_fail;
    pos = rx_cur;
    goto rx_L8;
rx_L8: __attribute__((unused));
    RX_SET(5, (ptrdiff_t)pos);
    goto rx_L6;
rx_L6: __attribute__((unused));
    if (pos < n && (s[pos] == 46)) { pos++; goto rx_L9; }
    goto rx_fail;
rx_L9: __attribute__((unused));
    RX_SET(6, (ptrdiff_t)pos);
    goto rx_L10;
rx_L10: __attribute__((unused));
    RX_PUSH(&&rx_L14, pos);
    goto rx_L12;
rx_L14: __attribute__((unused));
    goto rx_L13;
rx_L12: __attribute__((unused));
    if (pos < n && (s[pos] == 99)) { pos++; goto rx_L15; }
    goto rx_fail;
rx_L15: __attribute__((unused));
    if (pos < n && (s[pos] == 111)) { pos++; goto rx_L16; }
    goto rx_fail;
rx_L16: __attribute__((unused));
    if (pos < n && (s[pos] == 109)) { pos++; goto rx_L11; }
    goto rx_fail;
rx_L13: __attribute__((unused));
    if (pos < n && (s[pos] == 111)) { pos++; goto rx_L17; }
    goto rx_fail;
rx_L17: __attribute__((unused));
    if (pos < n && (s[pos] == 114)) { pos++; goto rx_L18; }
    goto rx_fail;
rx_L18: __attribute__((unused));
    if (pos < n && (s[pos] == 103)) { pos++; goto rx_L11; }
    goto rx_fail;
rx_L11: __attribute__((unused));
    RX_SET(7, (ptrdiff_t)pos);
    goto rx_L1;
rx_L1: __attribute__((unused));
    goto rx_accept;

rx_accept: __attribute__((unused));
    /* 3.1: leftmost-first is FIRST COMPLETE MATCH WINS, not compare
     * candidates. The VM returns here immediately and the capture
     * slots at this instant are the answer — no candidate comparison,
     * no longest-wins, no second pass. The caller's caps array is
     * filled by the ENTRY, not here (3.4). */
    return (ptrdiff_t)(pos - ctx->pos);

rx_fail: __attribute__((unused));
    /* THE ONLY BACKTRACKER AND THE ONLY INDIRECT JUMP.
     * A step is one backtrack resumption (4.2), counted at exactly
     * this place — so forward progress is FREE (a linear match over
     * 100 MB costs zero steps), the budget is subject-length-
     * independent, and the counter measures precisely the thing it is
     * meant to bound. D22: DD-2 is ROBUSTNESS, not a security
     * boundary, and it must not be traded against execution speed. */
    if (w->btn == 0) return -1;
    if (--w->budget < 0) return RX_R_STEPS;
    {
        const unsigned b_ = --w->btn;
        pos = w->bt[b_].pos;
        while (w->trn > w->bt[b_].mark) {
            w->trn--;
            stv[w->tr[w->trn].slot] = w->tr[w->trn].v;
        }
        goto *w->bt[b_].k;
    }
}

#undef RX_TRAIL
#undef RX_SET
#undef RX_PUSH

static void rx_caps_out(const rx_work *w, ptrdiff_t (*caps)[2],
                        size_t start, ptrdiff_t len)
{
    int k;
    caps[0][0] = (ptrdiff_t)start;
    caps[0][1] = (ptrdiff_t)start + len;
    for (k = 1; k < RX_NCAPS; k++) {
        caps[k][0] = w->stv[2 * k];
        caps[k][1] = w->stv[2 * k + 1];
    }
}

int rx_search(const unsigned char *s, size_t n, size_t startpos,
       ptrdiff_t (*caps)[2])
{
    rx_work w;
    rx_ctx ctx;
    ptrdiff_t r;
    size_t start;
    size_t ceil_;
    if (startpos > n) return 0;
    {
        ptrdiff_t win[1][2];
        if (rx_prefilter(s, n, startpos, win) != 1) return 0;
        start = (size_t)win[0][0];
        ceil_ = (size_t)win[0][1] < n ? (size_t)win[0][1] : n;
    }
    rx_work_init(&w);
    ctx.subject = s; ctx.len = n; ctx.ncap = 0;
    ctx.caps = NULL; ctx.user = NULL;
    for (;;) {
        ctx.pos = start;
        r = rx_match_impl(&ctx, &w, ceil_);
        if (r == RX_R_STEPS)  return PCREC_ERR_STEPS;
        if (r == RX_R_FRAMES) return PCREC_ERR_FRAMES;
        if (r == RX_R_WORK)   return PCREC_ERR_WORK;
        if (r >= 0) break;
        rx_unwind(&w);
        if (start >= n) return 0;
        start++;
        {
            ptrdiff_t win[1][2];
            if (rx_prefilter(s, n, start, win) != 1) return 0;
            start = (size_t)win[0][0];
            ceil_ = (size_t)win[0][1] < n ? (size_t)win[0][1] : n;
        }
    }
    if (caps) rx_caps_out(&w, caps, start, r);
    return 1;
}

/* F1's unconditional export, typed rx_matchfn.
 *
 * D49: THE GIVE-UP CODES ARE CARRIED HERE, not collapsed to -1. The
 * return space is >= 0 matched length, -1 no match, and a distinct
 * code in [PCREC_ERR_FLOOR, -2] for each way the engine can give up
 * (PCREC_ERR_STEPS, PCREC_ERR_FRAMES, PCREC_ERR_WORK). Anything BELOW the floor
 * stays reserved for the future abort semantic and is what a callout
 * call site traps on.
 *
 * This SUPERSEDES D42.3, which collapsed every give-up to -1 because
 * D38.4 had reserved the whole < -1 space. Three things moved: pcrec is
 * pre-release, so a 'final' label reads as 'stable absent a reason';
 * the typedef is BIDIRECTIONAL, so under the collapse an
 * embedder-WRITTEN callout had no legal spelling for 'I gave up' at
 * all (anything below -1 traps the process); and the collapse let an
 * inner give-up read as a plain path failure, so an outer match could
 * report an ANSWER where a bound had actually blown. A caller that
 * only asks 'did it match' still writes `r < 0` and is unaffected. */
ptrdiff_t rx_match(const rx_ctx *ctx)
{
    rx_work w;
    ptrdiff_t r;
    if (ctx->pos > ctx->len) return -1;
    rx_work_init(&w);
    r = rx_match_impl(ctx, &w, ctx->len);
    /* No translation and no clamp: the impl's return space IS this
     * contract's -- >= 0, -1, or one of the three R_ sentinels, which
     * are the ERR_ codes. A defensive floor test here would be dead
     * code pretending to be a safeguard. */
    return r;
}

/* The capture-delivering sibling. Same D49 return space as
 * <prefix>_match above -- it always had room for the codes (it is not
 * an rx_matchfn), and now the two agree instead of differing over a
 * reservation only one of them was bound by. caps_out is UNTOUCHED on
 * every negative return, give-up included: a caller that gave up has
 * no captures, and A-8's untouched-wins rule does not bend for it. */
ptrdiff_t rx_match_caps(const rx_ctx *ctx, ptrdiff_t (*caps_out)[2])
{
    rx_work w;
    ptrdiff_t r;
    if (ctx->pos > ctx->len) return -1;
    rx_work_init(&w);
    r = rx_match_impl(ctx, &w, ctx->len);
    if (r < 0) return r;
    if (caps_out) rx_caps_out(&w, caps_out, ctx->pos, r);
    return r;
}

/* byte encoding: one byte is one character, so the next boundary after pos
 * is pos + 1 and the subject is never read. */
size_t rx_next_pos(const unsigned char *s, size_t n, size_t pos)
{
    (void)s; (void)n;
    return pos + 1;
}

const struct rx_info rx_info = {
    .abi = 2,
    .flags = 2ULL,
    .encoding = 0,
    .ncaps = RX_NCAPS,
    .ngroups = 3,
    .nnames = 0,
    .engine = 2, /* PCREC_ENGINE_VM */
    .step_budget = 500000000,
    .work_budget = 1000000000,
    .frame_capacity = 2,
    .subject_ceiling = 0,
    .pattern = "(\\w+)@(\\w+)\\.(com|org)",
    .pattern_len = 22,
    .groups = NULL,
    .engine_why = "capture group at pattern offset 0",
};

int main(int argc, char **argv)
{
    /* Initialized: gcc -O1 false maybe-uninitialized (pcrec K28). */
    ptrdiff_t caps[RX_NCAPS][2] = {{0}};
    if (argc < 2) { fprintf(stderr, "usage: %s <subject>\n", argv[0]); return 2; }
    int rc = rx_search((const unsigned char *)argv[1], strlen(argv[1]), 0, caps);
    if (rc == 1) {
        printf("match %td %td\n", caps[0][0], caps[0][1]);
        return 0;
    }
    if (rc == 0) {
        printf("nomatch\n");
        return 1;
    }
    if (rc == PCREC_ERR_STEPS) {
        printf("steps\n");
        return 3;
    }
    if (rc == PCREC_ERR_FRAMES) {
        printf("frames\n");
        return 3;
    }
    if (rc == PCREC_ERR_WORK) {
        printf("work\n");
        return 3;
    }
    printf("giveup %d\n", rc);
    return 3;
}
