#!/usr/bin/env python3
"""THE NULL CONTROL for the [B84] pin pair: which capability artifacts are
PROGRAM-IDENTICAL between b1885a83 (abi 30, BEFORE) and 6ef76820 (abi 31, the
[OPT-PRECHECK-ADMIT] merge)?  b2ledger/nullctl.py's method, re-pointed: both
sides write to the SAME -o basename in their OWN directory; ignored when
comparing are the generated-by comment, the .abi integer, and the fix's own
NEW stamp line RX_REQ_WHY -- everything else is compared.

Expects $SCR/b1885a83/build/pcrec and $SCR/6ef76820/build/pcrec (git archive
REV | tar -x, make CC=gcc-16 build/pcrec).  Writes $SCR/nullctl.json.
"""
import os, re, subprocess, json, collections
SCR=os.environ["SCR"]
PATDIR="/Users/fdicostanzo/pcrec-bench/bench/capability/patterns"
BEFORE=f"{SCR}/b1885a83/build/pcrec"; AFTER=f"{SCR}/6ef76820/build/pcrec"
CONFIGS={"auto-caps":["--features","all"],
         "auto-nocaps":["--features","all","--no-captures"],
         "vm-caps":["--features","all","--engine=vm"]}
def norm(text):
    out=[]
    for ln in text.splitlines():
        if ln.startswith("/* Generated by pcrec"): continue
        if re.match(r'\s*\.abi\s*=', ln): continue
        if ln.startswith("#define RX_REQ_WHY"): continue
        out.append(ln)
    return "\n".join(out)
def stamp(text, name):
    m=re.search(r'^#define RX_%s "([^"]*)"' % name, text, re.M)
    return m.group(1) if m else None
def emit(binp, pat, flags, d):
    os.makedirs(d, exist_ok=True); out=os.path.join(d,"a.c")
    r=subprocess.run([binp,"-p","rx","-o",out,"--pattern",pat]+flags,
                     capture_output=True,timeout=120)
    if r.returncode!=0: return None
    return open(out,errors="replace").read()
res={}
for fn in sorted(os.listdir(PATDIR)):
    if not fn.endswith(".rx"): continue
    name=fn[:-3]
    pat=open(os.path.join(PATDIR,fn),"rb").read().rstrip(b"\n").decode("utf-8","surrogateescape")
    for cfg,flags in CONFIGS.items():
        b=emit(BEFORE,pat,flags,f"{SCR}/n/b"); a=emit(AFTER,pat,flags,f"{SCR}/n/a")
        if b is None or a is None:
            v="refused" if (b is None and a is None) else "refusal-mismatch"
            res[f"{name}|{cfg}"]={"identity":v}
        else:
            res[f"{name}|{cfg}"]={"identity":"identical" if norm(b)==norm(a) else "changed",
                "req_why":stamp(a,"REQ_WHY"),"engine":stamp(a,"ENGINE"),
                "vm_prefilter":stamp(a,"VM_PREFILTER"),
                "vm_prefilter_lang":stamp(a,"VM_PREFILTER_LANG"),
                "vm_start":stamp(a,"VM_START"),"req_byte":stamp(a,"REQ_BYTE")}
c=collections.Counter(v["identity"] for v in res.values()); print(dict(c))
w=collections.Counter(v.get("req_why") for v in res.values() if v["identity"]!="refused")
print("REQ_WHY at 6ef76820 (artifact-configs):",dict(w))
chg=collections.Counter((v.get("req_why"),v["identity"]) for v in res.values() if v["identity"]!="refused")
print("REQ_WHY x identity:",dict(chg))
json.dump(res,open(f"{SCR}/nullctl.json","w"),indent=1,sort_keys=True)
