/* probe_cls_bits.c — MOD-0.3c: GENERATE the classes producer's bitmaps from
 * libpcre2 censuses, so no table byte is ever hand-typed (the R8 rule: a
 * control must not share a source with what it controls — here inverted: the
 * DATA comes from the oracle once, and PC-4 re-measures it against the live
 * oracle every run; a libpcre2 version bump is a re-measurement event, D26
 * addendum).
 *
 * PREDICTOR, stated before the first run (8-bit, options = 0):
 *   \d 10   \s 6    \w 63   \h 3 {\t,' ',0xA0}   \v 5 {\n,\v,\f,\r,0x85}
 *   alnum 62  alpha 52  ascii 128  blank 2  cntrl 33  digit 10  graph 94
 *   lower 26  print 95  punct 32  space 6  upper 26  word 63  xdigit 22
 *   COMPLEMENT LAW: census(\D) is the exact 256-byte complement of \d (same
 *   for \S \W \H \V), and census([[:^name:]]) the complement of [[:name:]]
 *   for all 14 names — so only POSITIVE tables are emitted and the producer
 *   derives negation, leaving half as many bytes to drift.
 *
 * Usage: probe_cls_bits [--emit]   (--emit writes the .inc to stdout;
 *        without it, prints the census/complement summary only)
 * Build: TMPDIR=/var/tmp gcc -I tests/fuzz -o probe_cls_bits \
 *        tests/probes/probe_cls_bits.c -ldl
 */
#include "pcre2_abi.h"
#include <stdio.h>
#include <string.h>

static Pcre2Abi abi;

/* census of one-byte subjects matched by `pat`, as a 32-byte bitmap;
 * returns member count or -1 on compile failure */
static int census(const char *pat, unsigned char bits[32])
{
    int err = 0; PCRE2_SIZE eoff = 0;
    pcre2_code_8 *code = abi.compile((PCRE2_SPTR)pat, strlen(pat), 0,
                                     &err, &eoff, NULL);
    if (!code) { fprintf(stderr, "compile failed (%d): %s\n", err, pat); return -1; }
    pcre2_match_data_8 *md = abi.match_data_create(4, NULL);
    memset(bits, 0, 32);
    int n = 0;
    for (int b = 0; b < 256; b++) {
        unsigned char s[1] = { (unsigned char)b };
        if (abi.match(code, s, 1, 0, 0, md, NULL) >= 0) {
            bits[b >> 3] |= (unsigned char)(1u << (b & 7));
            n++;
        }
    }
    abi.match_data_free(md);
    abi.code_free(code);
    return n;
}

static int complement_ok(const unsigned char pos[32], const unsigned char neg[32])
{
    for (int i = 0; i < 32; i++)
        if ((unsigned char)(pos[i] ^ neg[i]) != 0xFF) return 0;
    return 1;
}

typedef struct { const char *cname; const char *pos_pat; const char *neg_pat; } Ent;

/* ^...$ anchoring is unnecessary for one-byte subjects with these patterns
 * (a class matches exactly one byte), but harmless and explicit. */
static const Ent ents[] = {
    { "digit_esc", "^\\d$",  "^\\D$" },
    { "space_esc", "^\\s$",  "^\\S$" },
    { "word_esc",  "^\\w$",  "^\\W$" },
    { "hspace",    "^\\h$",  "^\\H$" },
    { "vspace",    "^\\v$",  "^\\V$" },
    { "newline",   "^[\\n]$", "^[^\\n]$" },   /* \N's atom set = complement */
    { "px_alnum",  "^[[:alnum:]]$",  "^[[:^alnum:]]$" },
    { "px_alpha",  "^[[:alpha:]]$",  "^[[:^alpha:]]$" },
    { "px_ascii",  "^[[:ascii:]]$",  "^[[:^ascii:]]$" },
    { "px_blank",  "^[[:blank:]]$",  "^[[:^blank:]]$" },
    { "px_cntrl",  "^[[:cntrl:]]$",  "^[[:^cntrl:]]$" },
    { "px_digit",  "^[[:digit:]]$",  "^[[:^digit:]]$" },
    { "px_graph",  "^[[:graph:]]$",  "^[[:^graph:]]$" },
    { "px_lower",  "^[[:lower:]]$",  "^[[:^lower:]]$" },
    { "px_print",  "^[[:print:]]$",  "^[[:^print:]]$" },
    { "px_punct",  "^[[:punct:]]$",  "^[[:^punct:]]$" },
    { "px_space",  "^[[:space:]]$",  "^[[:^space:]]$" },
    { "px_upper",  "^[[:upper:]]$",  "^[[:^upper:]]$" },
    { "px_word",   "^[[:word:]]$",   "^[[:^word:]]$" },
    { "px_xdigit", "^[[:xdigit:]]$", "^[[:^xdigit:]]$" },
};

int main(int argc, char **argv)
{
    int emit = argc > 1 && strcmp(argv[1], "--emit") == 0;
    char why[256], ver[128];
    if (pcre2_abi_load(&abi, why, sizeof why) != PCRE2_ABI_OK) {
        fprintf(stderr, "SKIP: %s\n", why); return 2;
    }
    pcre2_abi_version(&abi, ver, sizeof ver);

    if (emit) {
        printf("/* GENERATED by tests/probes/probe_cls_bits.c --emit against\n"
               " * libpcre2 %s — DO NOT HAND-EDIT (regenerate instead; PC-4\n"
               " * re-measures these against the live oracle every run).\n"
               " * POSITIVE sets only: negation is the exact 256-bit\n"
               " * complement, a law the probe asserts for every pair\n"
               " * before emitting. Bit b of [b>>3] is byte b's membership. */\n",
               ver);
    } else {
        printf("libpcre2: %s\n", ver);
    }

    int bad = 0;
    for (size_t i = 0; i < sizeof ents / sizeof ents[0]; i++) {
        unsigned char pos[32], neg[32];
        int np = census(ents[i].pos_pat, pos);
        int nn = census(ents[i].neg_pat, neg);
        if (np < 0 || nn < 0) { bad++; continue; }
        int comp = complement_ok(pos, neg);
        if (!comp) bad++;
        if (emit) {
            if (!comp) printf("#error \"complement law FAILED for %s\"\n", ents[i].cname);
            printf("const unsigned char pcrec_cls_%s[32] = {", ents[i].cname);
            for (int j = 0; j < 32; j++)
                printf("%s0x%02x%s", j % 8 == 0 ? "\n    " : " ",
                       pos[j], j == 31 ? "" : ",");
            printf("\n}; /* %d members; complement = %d */\n", np, 256 - np);
        } else {
            printf("%-10s members=%-3d neg=%-3d complement_law=%s\n",
                   ents[i].cname, np, nn, comp ? "HOLDS" : "VIOLATED");
        }
    }
    if (emit && !bad) {
        /* THE NAME->BITS MAP, emitted WITH the tables (R16 follow-up,
         * Frank): the pairing is part of the measurement, so a swapped
         * pair cannot be written by hand in a plausible source line —
         * only by editing this generated artifact. Names are the px_
         * entries' own labels; the esc tables need no map (registry rows
         * reference their symbols directly). */
        printf("\nconst PcrecClsNamed pcrec_cls_posix_map[] = {\n");
        for (size_t i = 0; i < sizeof ents / sizeof ents[0]; i++) {
            if (strncmp(ents[i].cname, "px_", 3) != 0) continue;
            printf("    { \"%s\", pcrec_cls_%s },\n",
                   ents[i].cname + 3, ents[i].cname);
        }
        printf("};\nconst size_t pcrec_cls_posix_map_n =\n"
               "    sizeof pcrec_cls_posix_map / sizeof pcrec_cls_posix_map[0];\n");
    }
    if (!emit) printf("bad=%d\n", bad);
    return bad ? 1 : 0;
}
