/* tests/backrefs/fold_agreement_ucp_check.c — [K94] THE `--ucp` BYTE HALF OF
 * THE FOLD AGREEMENT CHECK, sibling of fold_agreement_check.c (plain byte)
 * and fold_agreement_utf8_check.c.
 *
 * UNDER `--ucp` THE BYTE ENCODING READS BYTES AS LATIN-1 (PCRE2_UCP without
 * PCRE2_UTF), and a caseless backreference must fold what the `--ucp` classes
 * fold. Until K94 the residual folded ASCII only, so `(\xe9)\1` -i --ucp
 * missed \xe9\xc9 where libpcre2 10.46 matches.
 *
 * THE TWO SIDES: the residual is read out of an artifact PCREC ACTUALLY
 * EMITTED under --ucp (this file links the generated gen.c and calls its
 * `rx_span_match_caseless`); the compiler side is `pcrec_fold_latin1`, the
 * PcrecFold object the parser widens --ucp classes with, read through its
 * own `partners` entry over a cpset. The residual's table is generated by
 * the seam from `pcrec_fold_latin1_rep`, a different function over the same
 * links, so agreement here is a measured fact and not a shared spelling.
 *
 * SWEPT over all 65,536 ORDERED PAIRS. Then asserted: exactly 52 + 60 = 112
 * bytes fold (the 26 ASCII pairs and the 30 Latin-1 letter pairs, both
 * directions), each with exactly one partner, and 0xB5, 0xDF, 0xFF — whose
 * Unicode partners lie outside Latin-1 — fold to nothing (MEASURED against
 * libpcre2 10.46, all 65,536 pairs, /i,ucp), so a check agreeing over an
 * empty or ASCII-only relation cannot read as a pass. */
#include <stdio.h>

#include "core/internal.h"
#include "gen.h"

int main(void)
{
    Arena ar = {0};
    int bad = 0, partnered = 0, i, j;
    static const unsigned inert[] = { 0xB5, 0xDF, 0xFF, 0xD7, 0xF7 };

    for (i = 0; i < 256; i++) {
        PcrecCpSet in, out;
        int partners = 0;
        pcrec_cpset_init(&in, &ar);
        pcrec_cpset_add(&in, (unsigned)i, (unsigned)i);
        pcrec_cpset_init(&out, &ar);
        pcrec_fold_latin1.partners(&in, &out);
        for (j = 0; j < 256; j++) {
            unsigned char buf[2] = { (unsigned char)i, (unsigned char)j };
            int resid_eq = rx_span_match_caseless(buf, 2, buf + 0, 1, 1) == 1;
            int table_eq = i == j || pcrec_cpset_has(&out, (unsigned)j);
            if (resid_eq != table_eq) {
                if (++bad <= 10)
                    printf("DISAGREE 0x%02x vs 0x%02x: residual says %s, "
                           "pcrec_fold_latin1 says %s\n", i, j,
                           resid_eq ? "equal" : "different",
                           table_eq ? "equal" : "different");
                continue;
            }
            if (i != j && resid_eq) partners++;
        }
        if (partners > 1) {
            printf("DEFECT 0x%02x has %d partners; every folding byte has "
                   "exactly one\n", i, partners);
            bad++;
        }
        if (partners == 1) partnered++;
    }
    if (partnered != 112) {
        printf("DEFECT %d bytes fold, expected exactly 112 (52 ASCII + 60 "
               "Latin-1 letters)\n", partnered);
        bad++;
    }
    for (i = 0; i < (int)(sizeof inert / sizeof *inert); i++) {
        PcrecCpSet in, out;
        pcrec_cpset_init(&in, &ar);
        pcrec_cpset_add(&in, inert[i], inert[i]);
        pcrec_cpset_init(&out, &ar);
        pcrec_fold_latin1.partners(&in, &out);
        for (j = 0; j < 256; j++)
            if ((unsigned)j != inert[i] && pcrec_cpset_has(&out, (unsigned)j)) {
                printf("DEFECT 0x%02x folds to 0x%02x under Latin-1; it has "
                       "no Latin-1 partner\n", inert[i], j);
                bad++;
            }
    }
    pcrec_arena_free(&ar);
    if (bad) {
        printf("fold-agreement (ucp): %d disagreement(s) over 65536 ordered "
               "pairs\n", bad);
        return 1;
    }
    printf("fold-agreement (ucp): 65536 ordered byte pairs, the SHIPPED "
           "$_span_match_caseless under --ucp and pcrec_fold_latin1 induce "
           "the SAME partition; %d bytes fold, each with exactly one "
           "partner; 0xB5/0xDF/0xFF fold to nothing\n", partnered);
    return 0;
}
